using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PMGSY.Areas.EFORMArea.QMBridgeModel
{
    public class EFORM_BRIDGE_QM_VIEWMODEL
    {

      

        #region  vikky 9-15



        public EFORM_BRIDGE_QM_GENERAL_DETAILS BRIDGE_QM_GENERAL_DETAILS { get; set; }

        public EFORM_BRIDGE_QM_ARRANGEMENT_OBS_DETAIL BRIDGE_QM_ARRANGEMENT_OBS_DETAIL { get; set; }

        public EFORM_BRIDGE_QM_QUALITY_ATTENTION BRIDGE_QM_QUALITY_ATTENTION { get; set; }

        public List<EFORM_BRIDGE_QM_QC_TEST_DETAILS> BRIDGE_QM_QC_TEST_DETAILS_LIST { get; set; }

        public List<EFORM_BRIDGE_QM_TEST_RESULT_VERIFICATION_DETAILS> BRIDGE_QM_TEST_RESULT_VERIFICATION_DETAILS_LIST { get; set; }

        public EFORM_BRIDGE_QM_FOUNDATION BRIDGE_QM_FOUNDATION { get; set; }

        public EFORM_BRIDGE_QM_ONGOING_FOUNDATION BRIDGE_QM_ONGOING_FOUNDATION { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_ON_QOM_FOUNDATION> BRIDGE_QM_CHILD_ON_QOM_FOUNDATION_LIST { get; set; }
        public List<EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_FOUNDATION> BRIDGE_QM_CHILD_ON_WORKMENSHIP_FOUNDATION_LIST { get; set; }
        public List<EFORM_BRIDGE_QM_CHILD_COMPL_QOM_FOUNDATION> BRIDGE_QM_CHILD_COMPL_QOM_FOUNDATION_LIST { get; set; }
        public EFORM_BRIDGE_QM_COMPLETED_FOUNDATION BRIDGE_QM_COMPLETED_FOUNDATION { get; set; }


        #endregion

        #region saurabh 15-22
        public EFORM_BRIDGE_QM_SUBSTRUCTURE BRIDGE_QM_SUBSTRUCTURE { get; set; }

        public EFORM_BRIDGE_QM_ONGOING_SUBSTRUCTURE BRIDGE_QM_ONGOING_SUBSTRUCTURE { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_ON_QOM_SUBSTRUCTURE> BRIDGE_QM_CHILD_ON_QOM_SUBSTRUCTURE_LIST { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_SUBSTRUCTURE> BRIDGE_QM_CHILD_ON_WORKMENSHIP_SUBSTRUCTURE_LIST { get; set; }

        public EFORM_BRIDGE_QM_COMPLETED_SUBSTRUCTURE BRIDGE_QM_COMPLETED_SUBSTRUCTURE { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_COMPLETED_SUBSTRUCTURE> BRIDGE_QM_CHILD_COMPLETED_SUBSTRUCTURE_LIST { get; set; }

        // SUPERSTRUCTURE
        public EFORM_BRIDGE_QM_SUPERSTRUCTURE BRIDGE_QM_SUPERSTRUCTURE { get; set; }

        public EFORM_BRIDGE_QM_CHILD_RCC_SUPERSTRUCTURE_ONGOING BRIDGE_QM_CHILD_RCC_SUPERSTRUCTURE { get; set; }

        public EFORM_BRIDGE_QM_CHILD_RCC_SUPERSTRUCTURE_COMPLETED BRIDGE_QM_CHILD_RCC_SUPERSTRUCTURE_COMPLETED { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_ON_QOM_RCC_SUPERSTRUCTURE> BRIDGE_QM_CHILD_ON_QOM_RCC_SUPERSTRUCTURE_LIST { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_COMPL_ACTIVITY_RCC_SUPERSTRUCTURE> BRIDGE_QM_CHILD_COMPL_ACTIVITY_RCC_SUPERSTRUCTURE_LIST { get; set; } // COMPLETED



        public EFORM_BRIDGE_QM_CHILD_STEEL_SUPERSTRUCTURE_ONGOING BRIDGE_QM_CHILD_STEEL_SUPERSTRUCTURE { get; set; }

        public EFORM_BRIDGE_QM_CHILD_STEEL_SUPERSTRUCTURE_COMPLETED BRIDGE_QM_CHILD_STEEL_SUPERSTRUCTURE_COMPLETED { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_ON_QOM_STEEL_SUPERSTRUCTURE> BRIDGE_QM_CHILD_ON_QOM_STEEL_SUPERSTRUCTURE_LIST { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_CO_MATERIAL_STEEL_SUPERSTRUCTURE> BRIDGE_QM_CHILD_CO_MATERIAL_STEEL_SUPERSTRUCTURE_LIST { get; set; }


        public EFORM_BRIDGE_QM_CHILD_BAILEY_BRIDGE_SUPERSTRUCTURE_ONGOING BRIDGE_QM_CHILD_BAILEY_BRIDGE_SUPERSTRUCTURE { get; set; }

        public EFORM_BRIDGE_QM_CHILD_BAILEY_BRIDGE_SUPERSTRUCTURE_COMPLETED BRIDGE_QM_CHILD_BAILEY_BRIDGE_SUPERSTRUCTURE_COMPLETED { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_ON_QOM_BAILEY_SUPERSTRUCTURE> BRIDGE_QM_CHILD_ON_QOM_BAILEY_SUPERSTRUCTURE_LIST { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_CO_MATERIAL_BAILEY_SUPERSTRUCTURE> BRIDGE_QM_CHILD_CO_MATERIAL_BAILEY_SUPERSTRUCTURE_LIST { get; set; }

        #endregion

        #region vikky 23-28
        public EFORM_BRIDGE_QM_LOAD_TEST BRIDGE_QM_LOAD_TEST { get; set; }

        public EFORM_BRIDGE_QM_BEARING BRIDGE_QM_BEARING { get; set; }

        public EFORM_BRIDGE_QM_CHILD_BEARING_TYPE BRIDGE_QM_CHILD_BEARING_TYPE { get; set; }


        public EFORM_BRIDGE_QM_EXPANSION BRIDGE_QM_EXPANSION { get; set; }

        public EFORM_BRIDGE_QM_APPROACH BRIDGE_QM_APPROACH { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_EMBANKMENT_APPROACH> BRIDGE_QM_CHILD_EMBANKMENT_APPROACH_LIST { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_SUB_BASE_APPROACH> BRIDGE_QM_CHILD_SUB_BASE_APPROACH_LIST { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_BASE_COURSE_APPROACH> BRIDGE_QM_CHILD_BASE_COURSE_APPROACH_LIST { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_WEARING_COURSE_APPROACH> BRIDGE_QM_CHILD_WEARING_COURSE_APPROACH_LIST { get; set; }


        public EFORM_BRIDGE_QM_CHILD_PROTECH_APPROACH BRIDGE_QM_CHILD_PROTECH_APPROACH { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_QOM_APPROACH> BRIDGE_QM_CHILD_QOM_APPROACH_LIST { get; set; }

        public List<EFORM_BRIDGE_QM_CHILD_WORKMENSHIP_APPROACH> BRIDGE_QM_CHILD_WORKMENSHIP_APPROACH_LIST { get; set; }

        #endregion



        #region Bhushan 29-35
        public EFORM_BRIDGE_QM_FURNITURE_MARKINGS BRIDGE_QM_FURNITURE_MARKINGS { get; set; }
        public EFORM_BRIDGE_QM_CHILD_OBS_FURNITURE_MARKING BRIDGE_QM_CHILD_OBS_FURNITURE_MARKING { get; set; }
        public EFORM_BRIDGE_QM_DEFICIENCY BRIDGE_QM_DEFICIENCY { get; set; }
        public EFORM_BRIDGE_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_PROG BRIDGE_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_PROG { get; set; }
        public EFORM_BRIDGE_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_COST BRIDGE_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_COST { get; set; }
        public List<EFORM_BRIDGE_QM_ACTION_TAKEN_PIU> BRIDGE_QM_ACTION_TAKEN_PIU_LIST { get; set; }
        public EFORM_BRIDGE_QM_DIFFERENCE_IN_OBSERVATION BRIDGE_QM_DIFFERENCE_IN_OBSERVATION { get; set; }
        public EFORM_BRIDGE_QM_OVERALL_GRADING BRIDGE_QM_OVERALL_GRADING { get; set; }
        public EFORM_BRIDGE_QM_QUALITY_GRADING BRIDGE_QM_QUALITY_GRADING { get; set; }
        #endregion

        public bool ErrorOccured { get; set; }

      public List<string> ErrorList { get; set; }

    }
}