using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PMGSY.Areas.EFORMArea.TestReportPreviewModel
{
    public class EFORM_TR_PREVIEW_MODEL
    {
        public EFORM_TR_PREFILLED_DETAILS PREFILLED_DETAILS { get; set; }

        public EFORM_TR_ITEM_APPLICABLE_DETAILS_VIEW ITEM_APPLICABLE_DETAILS_VIEW { get; set; }

        public List<EFORM_TR_MAIN_ITEM_OPTIONS_SELECTED_DETAIL_VIEW> MAIN_ITEM_OPTIONS_SELECTED_DETAIL_VIEW_List { get; set; }

        public List<EFORM_TR_SUBITEM_OPTIONS_SELECTED_DETAIL_VIEW> SUBITEM_OPTIONS_SELECTED_DETAIL_VIEW_List { get; set; }

        #region

        public EFORM_TR_TYPEA_SUMMARY_PAGE1_SRM_1_VIEW TYPEA_SUMMARY_PAGE1_SRM_1_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE1_SRM_1_VIEW> TYPEA_DETAIL_PAGE1_SRM_1_VIEW_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE1_CCM_2_VIEW TYPEA_SUMMARY_PAGE1_CCM_2_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE1_CCM_2_VIEW> TYPEA_DETAIL_PAGE1_CCM_2_VIEW_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE5_SRM_12_VIEW TYPEA_SUMMARY_PAGE5_SRM_12_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE5_SRM_12_VIEW> TYPEA_DETAIL_PAGE5_SRM_12_VIEW_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE7_SRM_16_VIEW TYPEA_SUMMARY_PAGE7_SRM_16_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE7_SRM_16_VIEW> TYPEA_DETAIL_PAGE7_SRM_16_VIEW_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE7_SRM_17_VIEW TYPEA_SUMMARY_PAGE7_SRM_17_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE7_SRM_17_VIEW> TYPEA_DETAIL_PAGE7_SRM_17_VIEW_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE9_SRM_21_VIEW TYPEA_SUMMARY_PAGE9_SRM_21_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE9_SRM_21_VIEW> TYPEA_DETAIL_PAGE9_SRM_21_VIEW_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE9_SRM_22_VIEW TYPEA_SUMMARY_PAGE9_SRM_22_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE9_SRM_22_VIEW> TYPEA_DETAIL_PAGE9_SRM_22_VIEW_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE11_SRM_26_VIEW TYPEA_SUMMARY_PAGE11_SRM_26_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE11_SRM_26_VIEW> TYPEA_DETAIL_PAGE11_SRM_26_VIEW_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE11_SRM_27_VIEW TYPEA_SUMMARY_PAGE11_SRM_27_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE11_SRM_27_VIEW> TYPEA_DETAIL_PAGE11_SRM_27_VIEW_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE15_SRM_37_VIEW TYPEA_SUMMARY_PAGE15_SRM_37_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE15_SRM_37_VIEW> TYPEA_DETAIL_PAGE15_SRM_37_VIEW_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE16_CCM_38_VIEW TYPEA_SUMMARY_PAGE16_CCM_38_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE16_CCM_38_VIEW> TYPEA_DETAIL_PAGE16_CCM_38_VIEW_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE16_SRM_39_VIEW TYPEA_SUMMARY_PAGE16_SRM_39_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE16_SRM_39_VIEW> TYPEA_DETAIL_PAGE16_SRM_39_VIEW_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE18_SRM_43_VIEW TYPEA_SUMMARY_PAGE18_SRM_43_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE18_SRM_43_VIEW> TYPEA_DETAIL_PAGE18_SRM_43_VIEW_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE19_SRM_44_VIEW TYPEA_SUMMARY_PAGE19_SRM_44_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE19_SRM_44_VIEW> TYPEA_DETAIL_PAGE19_SRM_44_VIEW_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE19_CCM_45_VIEW TYPEA_SUMMARY_PAGE19_CCM_45_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE19_CCM_45_VIEW> TYPEA_DETAIL_PAGE19_CCM_45_VIEW_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE22_SRM_52_VIEW TYPEA_SUMMARY_PAGE22_SRM_52_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE22_SRM_52_VIEW> TYPEA_DETAIL_PAGE22_SRM_52_VIEW_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE22_SRM_53_VIEW TYPEA_SUMMARY_PAGE22_SRM_53_VIEW { get; set; }
        public List<EFORM_TR_UCS_TEST_DETAIL_PAGE22_SRM_53_VIEW> UCS_TEST_DETAIL_PAGE22_SRM_53_VIEW_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE23_SRM_54_VIEW TYPEA_SUMMARY_PAGE23_SRM_54_VIEW { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE23_SRM_54_VIEW> TYPEA_DETAIL_PAGE23_SRM_54_VIEW_List { get; set; }


        #endregion

        #region Saurabh Page Read Model

        // Page -2
        public EFORM_TR_TYPEB_SUMMARY_PAGE2_GS_BASE_1_VIEW TYPEB_SUMMARY_PAGE2_GS_BASE_1_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE2_GS_BASE_1_VIEW TYPEB_SUMMARY_PAGE2_GS_BASE_2_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE2_GS_BASE_1_VIEW TYPEB_SUMMARY_PAGE2_GS_BASE_3_VIEW { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE2_GS_BASE_1_VIEW> TYPEB_DETAIL_PAGE2_GS_BASE_1_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE2_GS_BASE_1_VIEW> TYPEB_DETAIL_PAGE2_GS_BASE_2_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE2_GS_BASE_1_VIEW> TYPEB_DETAIL_PAGE2_GS_BASE_3_List_VIEW { get; set; }

        // Page - 3
        public EFORM_TR_TYPEB_SUMMARY_PAGE3_GRAVEL_SUBBASE_1_VIEW TYPEB_SUMMARY_PAGE3_GRAVEL_SUBBASE_1_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE3_GRAVEL_SUBBASE_1_VIEW TYPEB_SUMMARY_PAGE3_GRAVEL_SUBBASE_2_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE3_GRAVEL_SUBBASE_1_VIEW TYPEB_SUMMARY_PAGE3_GRAVEL_SUBBASE_3_VIEW { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE3_GRAVEL_SUBBASE_1_VIEW> TYPEB_DETAIL_PAGE3_GRAVEL_SUBBASE_1_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE3_GRAVEL_SUBBASE_1_VIEW> TYPEB_DETAIL_PAGE3_GRAVEL_SUBBASE_2_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE3_GRAVEL_SUBBASE_1_VIEW> TYPEB_DETAIL_PAGE3_GRAVEL_SUBBASE_3_List_VIEW { get; set; }

        // Page - 4

        public EFORM_TR_TYPEB_SUMMARY_PAGE4_CS_SUBBASE_1_VIEW TYPEB_SUMMARY_PAGE4_CS_SUBBASE_1_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE4_CS_SUBBASE_1_VIEW TYPEB_SUMMARY_PAGE4_CS_SUBBASE_2_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE4_CS_SUBBASE_1_VIEW TYPEB_SUMMARY_PAGE4_CS_SUBBASE_3_VIEW { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE4_CS_SUBBASE_1_VIEW> TYPEB_DETAIL_PAGE4_CS_SUBBASE_1_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE4_CS_SUBBASE_1_VIEW> TYPEB_DETAIL_PAGE4_CS_SUBBASE_2_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE4_CS_SUBBASE_1_VIEW> TYPEB_DETAIL_PAGE4_CS_SUBBASE_3_List_VIEW { get; set; }

        // Page - 6
        public EFORM_TR_TYPEB_SUMMARY_PAGE6_BASE_COURSE_1_VIEW TYPEB_SUMMARY_PAGE6_BASE_COURSE_1_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE6_BASE_COURSE_1_VIEW TYPEB_SUMMARY_PAGE6_BASE_COURSE_2_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE6_BASE_COURSE_1_VIEW TYPEB_SUMMARY_PAGE6_BASE_COURSE_3_VIEW { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE6_BASE_COURSE_1_VIEW> TYPEB_DETAIL_PAGE6_BASE_COURSE_1_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE6_BASE_COURSE_1_VIEW> TYPEB_DETAIL_PAGE6_BASE_COURSE_2_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE6_BASE_COURSE_1_VIEW> TYPEB_DETAIL_PAGE6_BASE_COURSE_3_List_VIEW { get; set; }

        // Page - 8
        public EFORM_TR_TYPEB_SUMMARY_PAGE8_BASE_COURSE2_1_VIEW TYPEB_SUMMARY_PAGE8_BASE_COURSE2_1_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE8_BASE_COURSE2_1_VIEW TYPEB_SUMMARY_PAGE8_BASE_COURSE2_2_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE8_BASE_COURSE2_1_VIEW TYPEB_SUMMARY_PAGE8_BASE_COURSE2_3_VIEW { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE8_BASE_COURSE2_1_VIEW> TYPEB_DETAIL_PAGE8_BASE_COURSE2_1_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE8_BASE_COURSE2_1_VIEW> TYPEB_DETAIL_PAGE8_BASE_COURSE2_2_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE8_BASE_COURSE2_1_VIEW> TYPEB_DETAIL_PAGE8_BASE_COURSE2_3_List_VIEW { get; set; }

        // Page - 10
        public EFORM_TR_TYPEB_SUMMARY_PAGE10_BASE_COURSE3_1_VIEW TYPEB_SUMMARY_PAGE10_BASE_COURSE3_1_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE10_BASE_COURSE3_1_VIEW TYPEB_SUMMARY_PAGE10_BASE_COURSE3_2_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE10_BASE_COURSE3_1_VIEW TYPEB_SUMMARY_PAGE10_BASE_COURSE3_3_VIEW { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE10_BASE_COURSE3_1_VIEW> TYPEB_DETAIL_PAGE10_BASE_COURSE3_1_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE10_BASE_COURSE3_1_VIEW> TYPEB_DETAIL_PAGE10_BASE_COURSE3_2_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE10_BASE_COURSE3_1_VIEW> TYPEB_DETAIL_PAGE10_BASE_COURSE3_3_List_VIEW { get; set; }

        // Page - 12 == 4
        public EFORM_TR_TYPEB_SUMMARY_PAGE12_CEMENT_SUBBASE_1_VIEW TYPEB_SUMMARY_PAGE12_CEMENT_SUBBASE_1_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE12_CEMENT_SUBBASE_1_VIEW TYPEB_SUMMARY_PAGE12_CEMENT_SUBBASE_2_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE12_CEMENT_SUBBASE_1_VIEW TYPEB_SUMMARY_PAGE12_CEMENT_SUBBASE_3_VIEW { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE12_CEMENT_SUBBASE_1_VIEW> TYPEB_DETAIL_PAGE12_CEMENT_SUBBASE_1_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE12_CEMENT_SUBBASE_1_VIEW> TYPEB_DETAIL_PAGE12_CEMENT_SUBBASE_2_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE12_CEMENT_SUBBASE_1_VIEW> TYPEB_DETAIL_PAGE12_CEMENT_SUBBASE_3_List_VIEW { get; set; }

        // Page - 13
        public EFORM_TR_TYPEB_SUMMARY_PAGE13_CEMENT_FDR_1_VIEW TYPEB_SUMMARY_PAGE13_CEMENT_FDR_1_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE13_CEMENT_FDR_1_VIEW TYPEB_SUMMARY_PAGE13_CEMENT_FDR_2_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE13_CEMENT_FDR_1_VIEW TYPEB_SUMMARY_PAGE13_CEMENT_FDR_3_VIEW { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE13_CEMENT_FDR_1_VIEW> TYPEB_DETAIL_PAGE13_CEMENT_FDR_1_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE13_CEMENT_FDR_1_VIEW> TYPEB_DETAIL_PAGE13_CEMENT_FDR_2_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE13_CEMENT_FDR_1_VIEW> TYPEB_DETAIL_PAGE13_CEMENT_FDR_3_List_VIEW { get; set; }

        // Page - 14
        public EFORM_TR_TYPEB_SUMMARY_PAGE14_BITUMN_COURSE_1_VIEW TYPEB_SUMMARY_PAGE14_BITUMN_COURSE_1_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE14_BITUMN_COURSE_1_VIEW TYPEB_SUMMARY_PAGE14_BITUMN_COURSE_2_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE14_BITUMN_COURSE_1_VIEW TYPEB_SUMMARY_PAGE15_BITUMN_COURSE_3_VIEW { get; set; }

        public EFORM_TR_TYPEC_SUMMARY_PAGE17_OPTION_SELECTED_3_VIEW TYPEB_SUMMARY_PAGE14_OPTION_SELECTED_3_VIEW { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE14_BITUMN_COURSE_1_VIEW> TYPEB_DETAIL_PAGE14_BITUMN_COURSE_1_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE14_BITUMN_COURSE_1_VIEW> TYPEB_DETAIL_PAGE14_BITUMN_COURSE_2_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE14_BITUMN_COURSE_1_VIEW> TYPEB_DETAIL_PAGE15_BITUMN_COURSE_3_List_VIEW { get; set; }



        // Page - 17-18
        public EFORM_TR_TYPEC_SUMMARY_PAGE17_BITUMN_SURFACE_COURSE_1_VIEW TYPEC_SUMMARY_PAGE17_BITUMN_SURFACE_COURSE_1_VIEW { get; set; }
        public EFORM_TR_TYPEC_SUMMARY_PAGE17_BITUMN_SURFACE_COURSE_1_VIEW TYPEC_SUMMARY_PAGE17_BITUMN_SURFACE_COURSE_2_VIEW { get; set; }
        public EFORM_TR_TYPEC_SUMMARY_PAGE17_BITUMN_SURFACE_COURSE_1_VIEW TYPEC_SUMMARY_PAGE18_BITUMN_SURFACE_COURSE_3_VIEW { get; set; }
        public EFORM_TR_TYPEC_SUMMARY_PAGE17_OPTION_SELECTED_3_VIEW TYPEC_SUMMARY_PAGE17_OPTION_SELECTED_3_VIEW { get; set; }

        public List<EFORM_TR_TYPEC_DETAIL_PAGE17_BITUMN_SURFACE_COURSE_1_VIEW> TYPEC_DETAIL_PAGE17_BITUMN_SURFACE_COURSE_1_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEC_DETAIL_PAGE17_BITUMN_SURFACE_COURSE_1_VIEW> TYPEC_DETAIL_PAGE17_BITUMN_SURFACE_COURSE_2_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEC_DETAIL_PAGE17_BITUMN_SURFACE_COURSE_1_VIEW> TYPEC_DETAIL_PAGE18_BITUMN_SURFACE_COURSE_3_List_VIEW { get; set; }

        // Page - 20
        public EFORM_TR_TYPEB_SUMMARY_PAGE20_SHOULDER_1_VIEW TYPEB_SUMMARY_PAGE20_SHOULDER_1_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE20_SHOULDER_1_VIEW TYPEB_SUMMARY_PAGE20_SHOULDER_2_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE20_SHOULDER_1_VIEW TYPEB_SUMMARY_PAGE20_SHOULDER_3_VIEW { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE20_SHOULDER_1_VIEW> TYPEB_DETAIL_PAGE20_SHOULDER_1_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE20_SHOULDER_1_VIEW> TYPEB_DETAIL_PAGE20_SHOULDER_2_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE20_SHOULDER_1_VIEW> TYPEB_DETAIL_PAGE20_SHOULDER_3_List_VIEW { get; set; }

        // Page - 21
        public EFORM_TR_TYPEB_SUMMARY_PAGE21_SHOULDER_1_VIEW TYPEB_SUMMARY_PAGE21_SHOULDER_1_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE21_SHOULDER_1_VIEW TYPEB_SUMMARY_PAGE21_SHOULDER_2_VIEW { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE21_SHOULDER_1_VIEW TYPEB_SUMMARY_PAGE21_SHOULDER_3_VIEW { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE21_SHOULDER_1_VIEW> TYPEB_DETAIL_PAGE21_SHOULDER_1_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE21_SHOULDER_1_VIEW> TYPEB_DETAIL_PAGE21_SHOULDER_2_List_VIEW { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE21_SHOULDER_1_VIEW> TYPEB_DETAIL_PAGE21_SHOULDER_3_List_VIEW { get; set; }


        #endregion








    }
}