using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PMGSY.Areas.EFORMArea.QM_ViewPdf_Model
{
    public class QM_CRASH_BARRIERS_ROAD_SAFETY
    {
        public string IS_DPR_PROVISION { get; set; }
        public decimal TOT_LENGTH_ASPER_DPR { get; set; }
        public decimal TOT_LENGTH_ERECTED { get; set; }
        public decimal TOT_SIGNBOARDS_ASPER_DPR { get; set; }
        public decimal TOT_SIGNBOARDS_ERECTED { get; set; }
        public string ITEM_GRADING_16 { get; set; }
        public string IMPROVE_SUGGESTIONS { get; set; }

    }
}