using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PMGSY.Areas.EFORMArea.TestReportModel
{
    public class EFORM_TR_VIEWMODEL
    {
        
        public List<EFORM_TR_MAIN_ITEM_OPTIONS_SELECTED_DETAIL> MAIN_ITEM_OPTIONS_SELECTED_DETAIL_List { get; set; }

        public List<EFORM_TR_SUBITEM_OPTIONS_SELECTED_DETAIL> SUBITEM_OPTIONS_SELECTED_DETAIL_List { get; set; }

        #region

        public EFORM_TR_TYPEA_SUMMARY_PAGE1_SRM_1 TYPEA_SUMMARY_PAGE1_SRM_1 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE1_SRM_1> TYPEA_DETAIL_PAGE1_SRM_1_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE1_CCM_2 TYPEA_SUMMARY_PAGE1_CCM_2 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE1_CCM_2> TYPEA_DETAIL_PAGE1_CCM_2_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE5_SRM_12 TYPEA_SUMMARY_PAGE5_SRM_12 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE5_SRM_12> TYPEA_DETAIL_PAGE5_SRM_12_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE7_SRM_16 TYPEA_SUMMARY_PAGE7_SRM_16 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE7_SRM_16> TYPEA_DETAIL_PAGE7_SRM_16_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE7_SRM_17 TYPEA_SUMMARY_PAGE7_SRM_17 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE7_SRM_17> TYPEA_DETAIL_PAGE7_SRM_17_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE9_SRM_21 TYPEA_SUMMARY_PAGE9_SRM_21 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE9_SRM_21> TYPEA_DETAIL_PAGE9_SRM_21_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE9_SRM_22 TYPEA_SUMMARY_PAGE9_SRM_22 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE9_SRM_22> TYPEA_DETAIL_PAGE9_SRM_22_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE11_SRM_26 TYPEA_SUMMARY_PAGE11_SRM_26 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE11_SRM_26> TYPEA_DETAIL_PAGE11_SRM_26_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE11_SRM_27 TYPEA_SUMMARY_PAGE11_SRM_27 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE11_SRM_27> TYPEA_DETAIL_PAGE11_SRM_27_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE15_SRM_37 TYPEA_SUMMARY_PAGE15_SRM_37 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE15_SRM_37> TYPEA_DETAIL_PAGE15_SRM_37_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE16_CCM_38 TYPEA_SUMMARY_PAGE16_CCM_38 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE16_CCM_38> TYPEA_DETAIL_PAGE16_CCM_38_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE16_SRM_39 TYPEA_SUMMARY_PAGE16_SRM_39 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE16_SRM_39> TYPEA_DETAIL_PAGE16_SRM_39_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE18_SRM_43 TYPEA_SUMMARY_PAGE18_SRM_43 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE18_SRM_43> TYPEA_DETAIL_PAGE18_SRM_43_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE19_SRM_44 TYPEA_SUMMARY_PAGE19_SRM_44 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE19_SRM_44> TYPEA_DETAIL_PAGE19_SRM_44_List { get; set; }


        public EFORM_TR_TYPEA_SUMMARY_PAGE19_CCM_45 TYPEA_SUMMARY_PAGE19_CCM_45 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE19_CCM_45> TYPEA_DETAIL_PAGE19_CCM_45_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE22_SRM_52 TYPEA_SUMMARY_PAGE22_SRM_52 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE22_SRM_52>  TYPEA_DETAIL_PAGE22_SRM_52_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE22_SRM_53 TYPEA_SUMMARY_PAGE22_SRM_53 { get; set; }
         public List<EFORM_TR_UCS_TEST_DETAIL_PAGE22_SRM_53> UCS_TEST_DETAIL_PAGE22_SRM_53_List { get; set; }

        public EFORM_TR_TYPEA_SUMMARY_PAGE23_SRM_54 TYPEA_SUMMARY_PAGE23_SRM_54 { get; set; }
        public List<EFORM_TR_TYPEA_DETAIL_PAGE23_SRM_54>  TYPEA_DETAIL_PAGE23_SRM_54_List { get; set; }


        #endregion


        #region Saurabh Page Read Model

        // Page -2
        public EFORM_TR_TYPEB_SUMMARY_PAGE2_GS_BASE_1 TYPEB_SUMMARY_PAGE2_GS_BASE_1 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE2_GS_BASE_2 TYPEB_SUMMARY_PAGE2_GS_BASE_2 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE2_GS_BASE_3 TYPEB_SUMMARY_PAGE2_GS_BASE_3 { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE2_GS_BASE_1> TYPEB_DETAIL_PAGE2_GS_BASE_1_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE2_GS_BASE_2> TYPEB_DETAIL_PAGE2_GS_BASE_2_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE2_GS_BASE_3> TYPEB_DETAIL_PAGE2_GS_BASE_3_List { get; set; }

        // Page - 3
        public EFORM_TR_TYPEB_SUMMARY_PAGE3_GRAVEL_SUBBASE_1 TYPEB_SUMMARY_PAGE3_GRAVEL_SUBBASE_1 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE3_GRAVEL_SUBBASE_2 TYPEB_SUMMARY_PAGE3_GRAVEL_SUBBASE_2 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE3_GRAVEL_SUBBASE_3 TYPEB_SUMMARY_PAGE3_GRAVEL_SUBBASE_3 { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE3_GRAVEL_SUBBASE_1> TYPEB_DETAIL_PAGE3_GRAVEL_SUBBASE_1_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE3_GRAVEL_SUBBASE_2> TYPEB_DETAIL_PAGE3_GRAVEL_SUBBASE_2_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE3_GRAVEL_SUBBASE_3> TYPEB_DETAIL_PAGE3_GRAVEL_SUBBASE_3_List { get; set; }

        // Page - 4

        public EFORM_TR_TYPEB_SUMMARY_PAGE4_CS_SUBBASE_1 TYPEB_SUMMARY_PAGE4_CS_SUBBASE_1 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE4_CS_SUBBASE_2 TYPEB_SUMMARY_PAGE4_CS_SUBBASE_2 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE4_CS_SUBBASE_3 TYPEB_SUMMARY_PAGE4_CS_SUBBASE_3 { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE4_CS_SUBBASE_1> TYPEB_DETAIL_PAGE4_CS_SUBBASE_1_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE4_CS_SUBBASE_2> TYPEB_DETAIL_PAGE4_CS_SUBBASE_2_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE4_CS_SUBBASE_3> TYPEB_DETAIL_PAGE4_CS_SUBBASE_3_List { get; set; }

        // Page - 6
        public EFORM_TR_TYPEB_SUMMARY_PAGE6_BASE_COURSE_1 TYPEB_SUMMARY_PAGE6_BASE_COURSE_1 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE6_BASE_COURSE_2 TYPEB_SUMMARY_PAGE6_BASE_COURSE_2 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE6_BASE_COURSE_3 TYPEB_SUMMARY_PAGE6_BASE_COURSE_3 { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE6_BASE_COURSE_1> TYPEB_DETAIL_PAGE6_BASE_COURSE_1_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE6_BASE_COURSE_2> TYPEB_DETAIL_PAGE6_BASE_COURSE_2_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE6_BASE_COURSE_3> TYPEB_DETAIL_PAGE6_BASE_COURSE_3_List { get; set; }

        // Page - 8
        public EFORM_TR_TYPEB_SUMMARY_PAGE8_BASE_COURSE2_1 TYPEB_SUMMARY_PAGE8_BASE_COURSE2_1 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE8_BASE_COURSE2_2 TYPEB_SUMMARY_PAGE8_BASE_COURSE2_2 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE8_BASE_COURSE2_3 TYPEB_SUMMARY_PAGE8_BASE_COURSE2_3 { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE8_BASE_COURSE2_1> TYPEB_DETAIL_PAGE8_BASE_COURSE2_1_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE8_BASE_COURSE2_2> TYPEB_DETAIL_PAGE8_BASE_COURSE2_2_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE8_BASE_COURSE2_3> TYPEB_DETAIL_PAGE8_BASE_COURSE2_3_List { get; set; }

        // Page - 10
        public EFORM_TR_TYPEB_SUMMARY_PAGE10_BASE_COURSE3_1 TYPEB_SUMMARY_PAGE10_BASE_COURSE3_1 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE10_BASE_COURSE3_2 TYPEB_SUMMARY_PAGE10_BASE_COURSE3_2 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE10_BASE_COURSE3_3 TYPEB_SUMMARY_PAGE10_BASE_COURSE3_3 { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE10_BASE_COURSE3_1> TYPEB_DETAIL_PAGE10_BASE_COURSE3_1_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE10_BASE_COURSE3_2> TYPEB_DETAIL_PAGE10_BASE_COURSE3_2_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE10_BASE_COURSE3_3> TYPEB_DETAIL_PAGE10_BASE_COURSE3_3_List { get; set; }

        // Page - 12 == 4
        public EFORM_TR_TYPEB_SUMMARY_PAGE12_CEMENT_SUBBASE_1 TYPEB_SUMMARY_PAGE12_CEMENT_SUBBASE_1 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE12_CEMENT_SUBBASE_2 TYPEB_SUMMARY_PAGE12_CEMENT_SUBBASE_2 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE12_CEMENT_SUBBASE_3 TYPEB_SUMMARY_PAGE12_CEMENT_SUBBASE_3 { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE12_CEMENT_SUBBASE_1> TYPEB_DETAIL_PAGE12_CEMENT_SUBBASE_1_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE12_CEMENT_SUBBASE_2> TYPEB_DETAIL_PAGE12_CEMENT_SUBBASE_2_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE12_CEMENT_SUBBASE_3> TYPEB_DETAIL_PAGE12_CEMENT_SUBBASE_3_List { get; set; }

        // Page - 13
        public EFORM_TR_TYPEB_SUMMARY_PAGE13_CEMENT_FDR_1 TYPEB_SUMMARY_PAGE13_CEMENT_FDR_1 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE13_CEMENT_FDR_2 TYPEB_SUMMARY_PAGE13_CEMENT_FDR_2 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE13_CEMENT_FDR_3 TYPEB_SUMMARY_PAGE13_CEMENT_FDR_3 { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE13_CEMENT_FDR_1> TYPEB_DETAIL_PAGE13_CEMENT_FDR_1_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE13_CEMENT_FDR_2> TYPEB_DETAIL_PAGE13_CEMENT_FDR_2_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE13_CEMENT_FDR_3> TYPEB_DETAIL_PAGE13_CEMENT_FDR_3_List { get; set; }

        // Page - 14
        public EFORM_TR_TYPEB_SUMMARY_PAGE14_BITUMN_COURSE_1 TYPEB_SUMMARY_PAGE14_BITUMN_COURSE_1 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE14_BITUMN_COURSE_2 TYPEB_SUMMARY_PAGE14_BITUMN_COURSE_2 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE15_BITUMN_COURSE_3 TYPEB_SUMMARY_PAGE15_BITUMN_COURSE_3 { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE14_BITUMN_COURSE_1> TYPEB_DETAIL_PAGE14_BITUMN_COURSE_1_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE14_BITUMN_COURSE_2> TYPEB_DETAIL_PAGE14_BITUMN_COURSE_2_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE15_BITUMN_COURSE_3> TYPEB_DETAIL_PAGE15_BITUMN_COURSE_3_List { get; set; }



        // Page - 17-18
        public EFORM_TR_TYPEC_SUMMARY_PAGE17_BITUMN_SURFACE_COURSE_1 TYPEC_SUMMARY_PAGE17_BITUMN_SURFACE_COURSE_1 { get; set; }
        public EFORM_TR_TYPEC_SUMMARY_PAGE17_BITUMN_SURFACE_COURSE_2 TYPEC_SUMMARY_PAGE17_BITUMN_SURFACE_COURSE_2 { get; set; }
        public EFORM_TR_TYPEC_SUMMARY_PAGE18_BITUMN_SURFACE_COURSE_3 TYPEC_SUMMARY_PAGE18_BITUMN_SURFACE_COURSE_3 { get; set; }

        public List<EFORM_TR_TYPEC_DETAIL_PAGE17_BITUMN_SURFACE_COURSE_1> TYPEC_DETAIL_PAGE17_BITUMN_SURFACE_COURSE_1_List { get; set; }
        public List<EFORM_TR_TYPEC_DETAIL_PAGE17_BITUMN_SURFACE_COURSE_2> TYPEC_DETAIL_PAGE17_BITUMN_SURFACE_COURSE_2_List { get; set; }
        public List<EFORM_TR_TYPEC_DETAIL_PAGE18_BITUMN_SURFACE_COURSE_3> TYPEC_DETAIL_PAGE18_BITUMN_SURFACE_COURSE_3_List { get; set; }

        // Page - 20
        public EFORM_TR_TYPEB_SUMMARY_PAGE20_SHOULDER_1 TYPEB_SUMMARY_PAGE20_SHOULDER_1 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE20_SHOULDER_2 TYPEB_SUMMARY_PAGE20_SHOULDER_2 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE20_SHOULDER_3 TYPEB_SUMMARY_PAGE20_SHOULDER_3 { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE20_SHOULDER_1> TYPEB_DETAIL_PAGE20_SHOULDER_1_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE20_SHOULDER_2> TYPEB_DETAIL_PAGE20_SHOULDER_2_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE20_SHOULDER_3> TYPEB_DETAIL_PAGE20_SHOULDER_3_List { get; set; }

        // Page - 21
        public EFORM_TR_TYPEB_SUMMARY_PAGE21_SHOULDER_1 TYPEB_SUMMARY_PAGE21_SHOULDER_1 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE21_SHOULDER_2 TYPEB_SUMMARY_PAGE21_SHOULDER_2 { get; set; }
        public EFORM_TR_TYPEB_SUMMARY_PAGE21_SHOULDER_3 TYPEB_SUMMARY_PAGE21_SHOULDER_3 { get; set; }

        public List<EFORM_TR_TYPEB_DETAIL_PAGE21_SHOULDER_1> TYPEB_DETAIL_PAGE21_SHOULDER_1_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE21_SHOULDER_2> TYPEB_DETAIL_PAGE21_SHOULDER_2_List { get; set; }
        public List<EFORM_TR_TYPEB_DETAIL_PAGE21_SHOULDER_3> TYPEB_DETAIL_PAGE21_SHOULDER_3_List { get; set; }


        #endregion


        public bool ErrorOccured { get; set; }

        public List<string> ErrorList { get; set; }


    }
}