//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABA_MIS_DATA_SERVICE
    {
        public int SL_NO { get; set; }
        public Nullable<int> MAST_PMGSY_SCHEME { get; set; }
        public Nullable<int> MAST_STATE_CODE { get; set; }
        public Nullable<int> MAST_DISTRICT_CODE { get; set; }
        public Nullable<int> LGD_STATE_CODE { get; set; }
        public string STATE_NAME { get; set; }
        public Nullable<int> LGD_DISTRICT_CODE { get; set; }
        public string DISTRICT_NAME { get; set; }
        public Nullable<int> ROADWORKS_ON_GOING_COMMULATIVE { get; set; }
        public Nullable<decimal> EXPENDITURE { get; set; }
        public Nullable<System.DateTime> GENERATED_DATE { get; set; }
    }
}
