//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABA_MIS_DATA
    {
        public int SL_NO { get; set; }
        public Nullable<int> MAST_STATE_LDG_CODE { get; set; }
        public string MAST_STATE_NAME { get; set; }
        public Nullable<int> MAST_DISTRICT_LDG_CODE { get; set; }
        public string Mast_District_Name { get; set; }
        public Nullable<int> ROADS_IN_PROGRESS { get; set; }
        public Nullable<decimal> EXP_TILL_PREV_DAY { get; set; }
        public Nullable<decimal> EXP_TILL_TODAY { get; set; }
        public Nullable<decimal> DIFF_OF_EXP { get; set; }
        public Nullable<System.DateTime> GENERATED_DATE { get; set; }
    }
}
