//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_ATR_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACC_ATR_MASTER()
        {
            this.ACC_ATR_OBSERVATION_DETAILS = new HashSet<ACC_ATR_OBSERVATION_DETAILS>();
        }
    
        public int ACC_ATR_MASTER_ID { get; set; }
        public int MAST_STATE_CODE { get; set; }
        public int MAST_AGENCY_CODE { get; set; }
        public string FUND_TYPE { get; set; }
        public int FIN_YEAR { get; set; }
        public int USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_AGENCY MASTER_AGENCY { get; set; }
        public virtual MASTER_STATE MASTER_STATE { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_ATR_OBSERVATION_DETAILS> ACC_ATR_OBSERVATION_DETAILS { get; set; }
    }
}
