//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_AUTH_REQUEST_TRACKING
    {
        public long REQUEST_ID { get; set; }
        public long AUTH_ID { get; set; }
        public string AUTH_STATUS { get; set; }
        public System.DateTime DATE_OF_OPERATION { get; set; }
        public string REMARKS { get; set; }
        public Nullable<long> BILL_ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual ACC_AUTH_REQUEST_MASTER ACC_AUTH_REQUEST_MASTER { get; set; }
        public virtual ACC_BILL_MASTER ACC_BILL_MASTER { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
