//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_RPT_FINAL_BILL_PAYMENT_PENDING
    {
        public int MAST_STATE_CODE { get; set; }
        public int MAST_DISTRICT_CODE { get; set; }
        public int ADMIN_ND_CODE { get; set; }
        public int IMS_YEAR { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public int MAST_AGENCY_CODE { get; set; }
        public int IMS_COLLABORATION { get; set; }
        public short PHY_COMP { get; set; }
        public short ACC_COMP { get; set; }
        public Nullable<int> FIN_COMPLETION_YEAR { get; set; }
        public Nullable<int> FIN_COMPLETION_MONTH { get; set; }
        public Nullable<System.DateTime> FINANCIAL_COMPLETION_DATE { get; set; }
        public Nullable<int> COMPLETION_YEAR { get; set; }
        public Nullable<int> COMPLETION_MONTH { get; set; }
        public Nullable<System.DateTime> EXEC_COMPLETION_DATE { get; set; }
    
        public virtual ADMIN_DEPARTMENT ADMIN_DEPARTMENT { get; set; }
        public virtual MASTER_AGENCY MASTER_AGENCY { get; set; }
        public virtual MASTER_DISTRICT MASTER_DISTRICT { get; set; }
        public virtual MASTER_FUNDING_AGENCY MASTER_FUNDING_AGENCY { get; set; }
        public virtual MASTER_STATE MASTER_STATE { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
