//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_VOUCHER_NUMBER_MASTER
    {
        public int ADMIN_ND_CODE { get; set; }
        public string FUND_TYPE { get; set; }
        public string BILL_TYPE { get; set; }
        public int FISCAL_YEAR { get; set; }
        public int SLNO { get; set; }
    
        public virtual ACC_MASTER_BILL_TYPE ACC_MASTER_BILL_TYPE { get; set; }
        public virtual ACC_MASTER_FUND_TYPE ACC_MASTER_FUND_TYPE { get; set; }
        public virtual ADMIN_DEPARTMENT ADMIN_DEPARTMENT { get; set; }
    }
}
