//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_EAUTH_AUTHAMT_DETAILS
    {
        public int DETAIL_ID { get; set; }
        public Nullable<int> ADMIN_ND_CODE { get; set; }
        public int MAST_CON_ID { get; set; }
        public int IMS_AGREEMENT_CODE { get; set; }
        public string IMS_PACKAGE_ID { get; set; }
        public decimal AMOUNT_AUTHORIZED { get; set; }
        public System.DateTime AUTHORIZATION_DATE { get; set; }
        public int EAUTH_ID { get; set; }
        public short EAUTH_TXN_NO { get; set; }
        public string FUND_TYPE { get; set; }
        public bool ISACTIVE { get; set; }
        public System.DateTime ENTRYDATE { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual ACC_EAUTH_MASTER ACC_EAUTH_MASTER { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
