//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_EPAY_MAIL_DETAILS
    {
        public long DETAIL_ID { get; set; }
        public long EPAY_ID { get; set; }
        public string BANK_ACC_NO { get; set; }
        public string BILL_NO { get; set; }
        public System.DateTime BILL_DATE { get; set; }
        public string AGREEMENT_NO { get; set; }
        public string PKG_NO { get; set; }
        public string CON_NAME { get; set; }
        public string CON_ACC_NO { get; set; }
        public string CON_BANK_NAME { get; set; }
        public string CON_BANK_IFS_CODE { get; set; }
        public Nullable<decimal> EPAY_AMOUNT { get; set; }
        public int ADMIN_ND_CODE { get; set; }
        public short LVL_ID { get; set; }
        public string CON_PAN_NO { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual ACC_EPAY_MAIL_MASTER ACC_EPAY_MAIL_MASTER { get; set; }
        public virtual UM_Level_Master UM_Level_Master { get; set; }
        public virtual ADMIN_DEPARTMENT ADMIN_DEPARTMENT { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
