//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_TXN_HEAD_MAPPING
    {
        public short MAP_ID { get; set; }
        public short TXN_ID { get; set; }
        public short HEAD_ID { get; set; }
        public string CREDIT_DEBIT { get; set; }
        public string CASH_CHQ { get; set; }
        public bool IS_REQ_AFTER_PORTING { get; set; }
        public bool IS_OPERATIONAL { get; set; }
    
        public virtual ACC_MASTER_HEAD ACC_MASTER_HEAD { get; set; }
        public virtual ACC_MASTER_TXN ACC_MASTER_TXN { get; set; }
    }
}
