//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_AUTH_REQUEST_DETAILS
    {
        public long AUTH_ID { get; set; }
        public short TXN_NO { get; set; }
        public short TXN_ID { get; set; }
        public short HEAD_ID { get; set; }
        public decimal AMOUNT { get; set; }
        public string CREDIT_DEBIT { get; set; }
        public string CASH_CHQ { get; set; }
        public string NARRATION { get; set; }
        public Nullable<int> IMS_PR_ROAD_CODE { get; set; }
        public Nullable<int> IMS_AGREEMENT_CODE { get; set; }
        public Nullable<int> MAS_FA_CODE { get; set; }
        public Nullable<bool> FINAL_PAYMENT { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual ACC_MASTER_HEAD ACC_MASTER_HEAD { get; set; }
        public virtual ACC_MASTER_TXN ACC_MASTER_TXN { get; set; }
        public virtual MASTER_STREAMS MASTER_STREAMS { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual TEND_AGREEMENT_MASTER TEND_AGREEMENT_MASTER { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
