//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_TXN_BANK
    {
        public long BANK_TXN_ID { get; set; }
        public long BILL_ID { get; set; }
        public byte TXN_MONTH { get; set; }
        public short TXN_YEAR { get; set; }
        public string TXN_TYPE_CODE { get; set; }
        public short BANK_CODE { get; set; }
        public string FUND_TYPE { get; set; }
        public string TOOL_NO { get; set; }
        public string TOOL_TYPE { get; set; }
        public System.DateTime TXN_DATE { get; set; }
        public string TXN_REMARKS { get; set; }
        public string SAS_LOGIN_NAME { get; set; }
        public string SAS_REQUEST_IP { get; set; }
        public System.DateTime SAS_DATA_ENTRY_DATE { get; set; }
        public string PAYEE_NAME { get; set; }
        public decimal AMOUNT { get; set; }
        public int ADMIN_ND_CODE { get; set; }
        public Nullable<short> LVL_ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual ACC_BILL_MASTER ACC_BILL_MASTER { get; set; }
        public virtual ACC_MASTER_FUND_TYPE ACC_MASTER_FUND_TYPE { get; set; }
        public virtual ACC_MASTER_LEVEL ACC_MASTER_LEVEL { get; set; }
        public virtual ADMIN_DEPARTMENT ADMIN_DEPARTMENT { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual ACC_BANK_DETAILS ACC_BANK_DETAILS { get; set; }
    }
}
