//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_CANCELLED_CHEQUES
    {
        public long CC_ID { get; set; }
        public long BILL_ID { get; set; }
        public Nullable<System.DateTime> R_BILL_DATE { get; set; }
        public Nullable<long> OLD_BILL_ID { get; set; }
        public Nullable<System.DateTime> OLD_BILL_DATE { get; set; }
        public string R_CHQ_NO { get; set; }
        public Nullable<int> ADMIN_ND_CODE { get; set; }
        public string REASON { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual ACC_BILL_MASTER ACC_BILL_MASTER { get; set; }
        public virtual ACC_BILL_MASTER ACC_BILL_MASTER1 { get; set; }
        public virtual ADMIN_DEPARTMENT ADMIN_DEPARTMENT { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
