//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_HOLDING_SECURITY_AUTO_ENTRIES
    {
        public long ID { get; set; }
        public long BILL_ID { get; set; }
        public long AUTO_BILL_ID { get; set; }
    
        public virtual ACC_BILL_MASTER ACC_BILL_MASTER { get; set; }
        public virtual ACC_BILL_MASTER ACC_BILL_MASTER1 { get; set; }
    }
}
