//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_QUALITY_MONITORS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMIN_QUALITY_MONITORS()
        {
            this.ADMIN_QUALITY_MONITORS_BANK = new HashSet<ADMIN_QUALITY_MONITORS_BANK>();
            this.QM_NQM_NOT_AVAILABLE_INSPECTION = new HashSet<QM_NQM_NOT_AVAILABLE_INSPECTION>();
            this.ADMIN_QUALITY_MONITORS_INTER_STATE = new HashSet<ADMIN_QUALITY_MONITORS_INTER_STATE>();
            this.QM_UNLOCK_DETAILS = new HashSet<QM_UNLOCK_DETAILS>();
            this.QUALITY_QM_AUTO_SCHEDULE = new HashSet<QUALITY_QM_AUTO_SCHEDULE>();
            this.QUALITY_QM_CADRE_STATE = new HashSet<QUALITY_QM_CADRE_STATE>();
            this.QUALITY_QM_LETTER = new HashSet<QUALITY_QM_LETTER>();
            this.QUALITY_QM_LOG = new HashSet<QUALITY_QM_LOG>();
            this.QUALITY_QM_SCHEDULE = new HashSet<QUALITY_QM_SCHEDULE>();
            this.EFORM_PIU_PREVIOUS_INSP_DETAILS = new HashSet<EFORM_PIU_PREVIOUS_INSP_DETAILS>();
            this.QM_PROFICIENCY_TEST_SCORE = new HashSet<QM_PROFICIENCY_TEST_SCORE>();
            this.NQM_TOUR_CLAIM_MASTER = new HashSet<NQM_TOUR_CLAIM_MASTER>();
        }
    
        public int ADMIN_QM_CODE { get; set; }
        public string ADMIN_QM_TYPE { get; set; }
        public Nullable<int> MAST_STATE_CODE { get; set; }
        public string ADMIN_QM_FNAME { get; set; }
        public string ADMIN_QM_MNAME { get; set; }
        public string ADMIN_QM_LNAME { get; set; }
        public int ADMIN_QM_DESG { get; set; }
        public string ADMIN_QM_ADDRESS1 { get; set; }
        public string ADMIN_QM_ADDRESS2 { get; set; }
        public Nullable<int> MAST_DISTRICT_CODE { get; set; }
        public Nullable<int> MAST_STATE_CODE_ADDR { get; set; }
        public string ADMIN_QM_PIN { get; set; }
        public string ADMIN_QM_STD1 { get; set; }
        public string ADMIN_QM_STD2 { get; set; }
        public string ADMIN_QM_PHONE1 { get; set; }
        public string ADMIN_QM_PHONE2 { get; set; }
        public string ADMIN_QM_STD_FAX { get; set; }
        public string ADMIN_QM_FAX { get; set; }
        public string ADMIN_QM_MOBILE1 { get; set; }
        public string ADMIN_QM_MOBILE2 { get; set; }
        public string ADMIN_QM_EMAIL { get; set; }
        public string ADMIN_QM_PAN { get; set; }
        public string ADMIN_QM_PAN_FILE { get; set; }
        public string ADMIN_QM_EMPANELLED { get; set; }
        public Nullable<int> ADMIN_QM_EMPANELLED_YEAR { get; set; }
        public string ADMIN_QM_IMAGE { get; set; }
        public string ADMIN_QM_DOCPATH { get; set; }
        public string ADMIN_QM_AADHAR_NO { get; set; }
        public string ADMIN_QM_REMARKS { get; set; }
        public Nullable<int> ADMIN_USER_ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
        public string ADMIN_QM_SERVICE_TYPE { get; set; }
        public Nullable<System.DateTime> ADMIN_QM_BIRTH_DATE { get; set; }
        public Nullable<int> ADMIN_QM_EMPANELLED_MONTH { get; set; }
        public string ADMIN_QM_DEEMPANEL_REMARKS { get; set; }
        public Nullable<int> ADMIN_QM_DEPARTMENT { get; set; }
        public string ADMIN_QM_EMPANELLED_REASON { get; set; }
        public Nullable<System.DateTime> ADMIN_QM_DEMPANELLED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMIN_QUALITY_MONITORS_BANK> ADMIN_QUALITY_MONITORS_BANK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QM_NQM_NOT_AVAILABLE_INSPECTION> QM_NQM_NOT_AVAILABLE_INSPECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMIN_QUALITY_MONITORS_INTER_STATE> ADMIN_QUALITY_MONITORS_INTER_STATE { get; set; }
        public virtual MASTER_DESIGNATION MASTER_DESIGNATION { get; set; }
        public virtual MASTER_DISTRICT MASTER_DISTRICT { get; set; }
        public virtual MASTER_STATE MASTER_STATE { get; set; }
        public virtual MASTER_STATE MASTER_STATE1 { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual UM_User_Master UM_User_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QM_UNLOCK_DETAILS> QM_UNLOCK_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_AUTO_SCHEDULE> QUALITY_QM_AUTO_SCHEDULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_CADRE_STATE> QUALITY_QM_CADRE_STATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_LETTER> QUALITY_QM_LETTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_LOG> QUALITY_QM_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_SCHEDULE> QUALITY_QM_SCHEDULE { get; set; }
        public virtual MASTER_STATE MASTER_STATE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_PREVIOUS_INSP_DETAILS> EFORM_PIU_PREVIOUS_INSP_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QM_PROFICIENCY_TEST_SCORE> QM_PROFICIENCY_TEST_SCORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NQM_TOUR_CLAIM_MASTER> NQM_TOUR_CLAIM_MASTER { get; set; }
    }
}
