//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_TA_STATE
    {
        public int ADMIN_TA_ID { get; set; }
        public int ADMIN_TA_CODE { get; set; }
        public int MAST_STATE_CODE { get; set; }
        public Nullable<int> MAST_DISTRICT_CODE { get; set; }
        public System.DateTime MAST_START_DATE { get; set; }
        public Nullable<System.DateTime> MAST_END_DATE { get; set; }
        public string MAST_IS_FINALIZED { get; set; }
        public string MAST_IS_ACTIVE { get; set; }
        public string MAST_IS_ENABLED { get; set; }
        public int MAST_SCHEME { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
        public string STR_MAST_SCHEME { get; set; }
    
        public virtual ADMIN_TECHNICAL_AGENCY ADMIN_TECHNICAL_AGENCY { get; set; }
        public virtual MASTER_DISTRICT MASTER_DISTRICT { get; set; }
        public virtual MASTER_STATE MASTER_STATE { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
