//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_AUDIT_LOG_TEMP
    {
        public long AuditId { get; set; }
        public int UserId { get; set; }
        public string ModuleName { get; set; }
        public string RequestType { get; set; }
        public string URLAccessed { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
