//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_TECHNICAL_AGENCY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMIN_TECHNICAL_AGENCY()
        {
            this.IMS_SANCTIONED_PROJECTS = new HashSet<IMS_SANCTIONED_PROJECTS>();
            this.ADMIN_TA_STATE = new HashSet<ADMIN_TA_STATE>();
        }
    
        public int ADMIN_TA_CODE { get; set; }
        public string ADMIN_TA_TYPE { get; set; }
        public string ADMIN_TA_NAME { get; set; }
        public string ADMIN_TA_ADDRESS1 { get; set; }
        public string ADMIN_TA_ADDRESS2 { get; set; }
        public Nullable<int> MAST_DISTRICT_CODE { get; set; }
        public Nullable<int> MAST_STATE_CODE { get; set; }
        public string ADMIN_TA_PIN { get; set; }
        public string ADMIN_TA_STD1 { get; set; }
        public string ADMIN_TA_STD2 { get; set; }
        public string ADMIN_TA_PHONE1 { get; set; }
        public string ADMIN_TA_PHONE2 { get; set; }
        public string ADMIN_TA_STD_FAX { get; set; }
        public string ADMIN_TA_FAX { get; set; }
        public string ADMIN_TA_MOBILE_NO { get; set; }
        public string ADMIN_TA_EMAIL { get; set; }
        public string ADMIN_TA_WEBISTE { get; set; }
        public Nullable<int> ADMIN_TA_CONTACT_DESG { get; set; }
        public string ADMIN_TA_CONTACT_NAME { get; set; }
        public string ADMIN_TA_REMARKS { get; set; }
        public Nullable<int> ADMIN_USER_ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
        public string ADMIN_TA_SERVICE_TAX { get; set; }
    
        public virtual MASTER_DESIGNATION MASTER_DESIGNATION { get; set; }
        public virtual MASTER_DISTRICT MASTER_DISTRICT { get; set; }
        public virtual MASTER_STATE MASTER_STATE { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual UM_User_Master UM_User_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_SANCTIONED_PROJECTS> IMS_SANCTIONED_PROJECTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMIN_TA_STATE> ADMIN_TA_STATE { get; set; }
    }
}
