//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_USER_MASTER_DUMMY
    {
        public int SAS_USER_ID { get; set; }
        public string SAS_LOGIN_NAME { get; set; }
        public int SAS_DEFAULT_ROLE { get; set; }
        public int SAS_PRIMARY_ROLE { get; set; }
        public int SAS_CONTACT_ID { get; set; }
        public string SAS_ORIGINAL_PASSWORD { get; set; }
        public string SAS_STATE_CODE { get; set; }
        public Nullable<int> SAS_DISTRICT_CODE { get; set; }
        public Nullable<int> SAS_DPIU_CODE { get; set; }
        public Nullable<int> SAS_LOCATION_CODE { get; set; }
        public Nullable<System.DateTime> SAS_ACTIVATION_DATE { get; set; }
        public Nullable<System.DateTime> SAS_DEACTIVATION_DATE { get; set; }
        public Nullable<int> SAS_PWDRQ_ID { get; set; }
        public string SAS_PWDR_ANSWER { get; set; }
        public System.DateTime SAS_PREV_PWDCH_DATE { get; set; }
        public int SAS_ACCOUNT_STATUS_FLAG { get; set; }
        public Nullable<int> SAS_ORIGINAL_ENABLE_BIT { get; set; }
        public string MOB_IMEI_NO { get; set; }
        public string SAS_HASH_PASSWORD { get; set; }
        public Nullable<int> ADMIN_EA_CODE { get; set; }
    }
}
