//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACTOR_REGISTRATION_DETAILS
    {
        public int REGISTRATION_ID { get; set; }
        public string CON_FIRM_NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public string MOBILE_NO { get; set; }
        public int USER_ID { get; set; }
        public string BANK_NAME { get; set; }
        public string BRANCH_NAME { get; set; }
        public string IFSC_CODE { get; set; }
        public string BANK_ACCOUNT_NO { get; set; }
        public string PAN_NO { get; set; }
        public string IPADDR { get; set; }
    
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
