//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUPL_PMGSY3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUPL_PMGSY3()
        {
            this.MASTER_PMGSY3_INCLUSION = new HashSet<MASTER_PMGSY3_INCLUSION>();
            this.TR_MRL_EXEMPTION = new HashSet<TR_MRL_EXEMPTION>();
        }
    
        public int CUPL_PMGSY3_ID { get; set; }
        public int CUPL_RANK { get; set; }
        public int MAST_DISTRICT_CODE { get; set; }
        public string MAST_DISTRICT_NAME { get; set; }
        public int MAST_BLOCK_CODE { get; set; }
        public string MAST_BLOCK_NAME { get; set; }
        public int PLAN_CN_ROAD_CODE { get; set; }
        public string PLAN_CN_ROAD_NUMBER { get; set; }
        public decimal PLAN_RD_LENGTH { get; set; }
        public Nullable<decimal> ELIGIBLE_CANDIDATE_LENGTH { get; set; }
        public string PLAN_RD_NAME { get; set; }
        public decimal SCORE { get; set; }
        public decimal SCORE_PER_UNIT_LENGTH { get; set; }
        public decimal MIN_SCORE { get; set; }
        public int MAST_ER_ROAD_CODE { get; set; }
        public string MAST_ER_ROAD_NAME { get; set; }
        public string MAST_ER_ROAD_NUMBER { get; set; }
        public int MAST_ER_ROAD_OWNER { get; set; }
        public decimal PLAN_RD_FROM_CHAINAGE { get; set; }
        public decimal PLAN_RD_TO_CHAINAGE { get; set; }
        public decimal MAST_ER_ROAD_SCORE { get; set; }
        public decimal MEANPCI { get; set; }
        public string PCI_ELIGIBILITY { get; set; }
        public decimal ELIGIBILE_LENGTH { get; set; }
        public string COMPLETED { get; set; }
        public string ELIGIBLE { get; set; }
        public Nullable<decimal> DATE_DIFFETENCR { get; set; }
        public Nullable<int> TOTAL_HAB_SERVER { get; set; }
        public int IMS_YEAR { get; set; }
        public int IMS_BATCH { get; set; }
        public System.DateTime FINALIZED_DATE { get; set; }
        public string APPROVAL { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_DISTRICT MASTER_DISTRICT { get; set; }
        public virtual MASTER_BLOCK MASTER_BLOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_PMGSY3_INCLUSION> MASTER_PMGSY3_INCLUSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_MRL_EXEMPTION> TR_MRL_EXEMPTION { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
