//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_BRIDGE_QM_DEFICIENCY
    {
        public int DEF_ID { get; set; }
        public int EFORM_ID { get; set; }
        public int PR_ROAD_CODE { get; set; }
        public string IS_NO_DEFICIENCY { get; set; }
        public string IS_BOQ_NOT_CLEAR { get; set; }
        public string IS_NO_SPANS_INSUFFICIENT { get; set; }
        public string IS_NO_PROVISION_PROTECTION_WORK { get; set; }
        public string IS_HYDROLIC_DESIGN_DPR { get; set; }
        public string IS_GUARD_STONE_IN_DPR { get; set; }
        public string IS_DEVIATION_ALIGNMENT { get; set; }
        public string OTHER_COMMENT { get; set; }
        public int USER_ID { get; set; }
        public string IPADD { get; set; }
    
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
