//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EFORM_MASTER()
        {
            this.EFORM_PIU_QC_DETAILS = new HashSet<EFORM_PIU_QC_DETAILS>();
            this.EFORM_QM_GEOMETRICS_DETAILS = new HashSet<EFORM_QM_GEOMETRICS_DETAILS>();
            this.EFORM_QM_ITEM_APPLICABLE_DETAILS = new HashSet<EFORM_QM_ITEM_APPLICABLE_DETAILS>();
            this.EFORM_PDF_UPLOAD_DETAIL = new HashSet<EFORM_PDF_UPLOAD_DETAIL>();
            this.EFORM_PIU_GENERAL_INFO = new HashSet<EFORM_PIU_GENERAL_INFO>();
            this.EFORM_PIU_ITEM_APPLICABLE_DETAILS = new HashSet<EFORM_PIU_ITEM_APPLICABLE_DETAILS>();
            this.EFORM_PIU_MIX_DESIGN_DETAILS = new HashSet<EFORM_PIU_MIX_DESIGN_DETAILS>();
            this.EFORM_PIU_NEW_TECHNOLOGY_DETAILS = new HashSet<EFORM_PIU_NEW_TECHNOLOGY_DETAILS>();
            this.EFORM_PIU_PREVIOUS_INSP_DETAILS = new HashSet<EFORM_PIU_PREVIOUS_INSP_DETAILS>();
            this.EFORM_PIU_PRGS_DETAILS = new HashSet<EFORM_PIU_PRGS_DETAILS>();
            this.EFORM_PIU_TECHNOLOGY_DETAIL = new HashSet<EFORM_PIU_TECHNOLOGY_DETAIL>();
            this.EFORM_PREFILLED_DETAILS = new HashSet<EFORM_PREFILLED_DETAILS>();
            this.EFORM_QC_OFFICIAL_DETAILS = new HashSet<EFORM_QC_OFFICIAL_DETAILS>();
            this.EFORM_QM_ACTION_TAKEN_PIU = new HashSet<EFORM_QM_ACTION_TAKEN_PIU>();
            this.EFORM_QM_ARRANGEMENTS_OBS_DETAILS = new HashSet<EFORM_QM_ARRANGEMENTS_OBS_DETAILS>();
            this.EFORM_QM_BASE_COURSE_I = new HashSet<EFORM_QM_BASE_COURSE_I>();
            this.EFORM_QM_BASE_COURSE_II = new HashSet<EFORM_QM_BASE_COURSE_II>();
            this.EFORM_QM_BASE_COURSE_III = new HashSet<EFORM_QM_BASE_COURSE_III>();
            this.EFORM_QM_BITUMINOUS_SURFACE_COURSE = new HashSet<EFORM_QM_BITUMINOUS_SURFACE_COURSE>();
            this.EFORM_QM_CHILD_EARTHWORK_SUBGRADE_CBR_DETAILS = new HashSet<EFORM_QM_CHILD_EARTHWORK_SUBGRADE_CBR_DETAILS>();
            this.EFORM_QM_CC_PUCCA_DRAINS = new HashSet<EFORM_QM_CC_PUCCA_DRAINS>();
            this.EFORM_QM_CC_SR_PVAEMENTS = new HashSet<EFORM_QM_CC_SR_PVAEMENTS>();
            this.EFORM_QM_CDWORKS_SLAB_CULVERTS = new HashSet<EFORM_QM_CDWORKS_SLAB_CULVERTS>();
            this.EFORM_QM_CDWORKS_PIPE_CULVERTS = new HashSet<EFORM_QM_CDWORKS_PIPE_CULVERTS>();
            this.EFORM_QM_CHILD_BASECOURSE_UCS_DETAILS_LAYER1 = new HashSet<EFORM_QM_CHILD_BASECOURSE_UCS_DETAILS_LAYER1>();
            this.EFORM_QM_CHILD_BASECOURSE_UCS_DETAILS_LAYER2 = new HashSet<EFORM_QM_CHILD_BASECOURSE_UCS_DETAILS_LAYER2>();
            this.EFORM_QM_CHILD_BASECOURSE_UCS_DETAILS_LAYER3 = new HashSet<EFORM_QM_CHILD_BASECOURSE_UCS_DETAILS_LAYER3>();
            this.EFORM_QM_CHILD_BITUMINOUS_OBSERVATION_DETAILS = new HashSet<EFORM_QM_CHILD_BITUMINOUS_OBSERVATION_DETAILS>();
            this.EFORM_QM_CHILD_BITUMINOUS_SURFACE_COARSE_DETAILS = new HashSet<EFORM_QM_CHILD_BITUMINOUS_SURFACE_COARSE_DETAILS>();
            this.EFORM_QM_CHILD_CC_AND_SR_PAVEMENTS_OBSERVATION_DETAILS = new HashSet<EFORM_QM_CHILD_CC_AND_SR_PAVEMENTS_OBSERVATION_DETAILS>();
            this.EFORM_QM_CHILD_CC_PUCCA_DRAINS_OBSERVATION_DETAILS = new HashSet<EFORM_QM_CHILD_CC_PUCCA_DRAINS_OBSERVATION_DETAILS>();
            this.EFORM_QM_CHILD_CDWORKS_PIPE_CULVERTS_DETAILS = new HashSet<EFORM_QM_CHILD_CDWORKS_PIPE_CULVERTS_DETAILS>();
            this.EFORM_QM_CHILD_CDWORKS_SLAB_CULVERTS_DETAILS = new HashSet<EFORM_QM_CHILD_CDWORKS_SLAB_CULVERTS_DETAILS>();
            this.EFORM_QM_CHILD_CRASH_BARRIERS_OBSERVATION_DETAILS = new HashSet<EFORM_QM_CHILD_CRASH_BARRIERS_OBSERVATION_DETAILS>();
            this.EFORM_QM_CHILD_CUT_SLOPE_DETAIL = new HashSet<EFORM_QM_CHILD_CUT_SLOPE_DETAIL>();
            this.EFORM_QM_CHILD_DEGREE_OF_COMPAQ = new HashSet<EFORM_QM_CHILD_DEGREE_OF_COMPAQ>();
            this.EFORM_QM_CHILD_GRANULAR_UCS_DETAILS = new HashSet<EFORM_QM_CHILD_GRANULAR_UCS_DETAILS>();
            this.EFORM_QM_CHILD_GROUP_SYMBOL_SOIL = new HashSet<EFORM_QM_CHILD_GROUP_SYMBOL_SOIL>();
            this.EFORM_QM_CHILD_OBSERVATION_WORKMANSHIP_LAYER1 = new HashSet<EFORM_QM_CHILD_OBSERVATION_WORKMANSHIP_LAYER1>();
            this.EFORM_QM_CHILD_OBSERVATION_WORKMANSHIP_LAYER2 = new HashSet<EFORM_QM_CHILD_OBSERVATION_WORKMANSHIP_LAYER2>();
            this.EFORM_QM_CHILD_OBSERVATION_WORKMANSHIP_LAYER3 = new HashSet<EFORM_QM_CHILD_OBSERVATION_WORKMANSHIP_LAYER3>();
            this.EFORM_QM_CHILD_PROT_WORKS_QOM_DETAILS = new HashSet<EFORM_QM_CHILD_PROT_WORKS_QOM_DETAILS>();
            this.EFORM_QM_CHILD_PROT_WORKS_WORKMANSHIP_OF_RS_DETAILS = new HashSet<EFORM_QM_CHILD_PROT_WORKS_WORKMANSHIP_OF_RS_DETAILS>();
            this.EFORM_QM_CHILD_QOM_WORKMENSHIP = new HashSet<EFORM_QM_CHILD_QOM_WORKMENSHIP>();
            this.EFORM_QM_CHILD_ROAD_FURNITURE_MARKINGS_OBSERVATION_DETAILS = new HashSet<EFORM_QM_CHILD_ROAD_FURNITURE_MARKINGS_OBSERVATION_DETAILS>();
            this.EFORM_QM_CHILD_SD_AND_CW_DRAINS_DETAILS = new HashSet<EFORM_QM_CHILD_SD_AND_CW_DRAINS_DETAILS>();
            this.EFORM_QM_CHILD_SHOULDERS_MATERIAL_DETAILS = new HashSet<EFORM_QM_CHILD_SHOULDERS_MATERIAL_DETAILS>();
            this.EFORM_QM_CHILD_SHOULDERS_UCS_DETAILS = new HashSet<EFORM_QM_CHILD_SHOULDERS_UCS_DETAILS>();
            this.EFORM_QM_CHILD_SIDE_SLOPE_DETAIL = new HashSet<EFORM_QM_CHILD_SIDE_SLOPE_DETAIL>();
            this.EFORM_QM_COMPAQ_EMBANKMENT = new HashSet<EFORM_QM_COMPAQ_EMBANKMENT>();
            this.EFORM_QM_CRASH_BARRIERS_ROAD_SAFETY = new HashSet<EFORM_QM_CRASH_BARRIERS_ROAD_SAFETY>();
            this.EFORM_QM_DEFICIENCY_PREPARATION = new HashSet<EFORM_QM_DEFICIENCY_PREPARATION>();
            this.EFORM_QM_DIFFEENCE_IN_OBSERVATION = new HashSet<EFORM_QM_DIFFEENCE_IN_OBSERVATION>();
            this.EFORM_QM_GRANULAR_SUBBASE = new HashSet<EFORM_QM_GRANULAR_SUBBASE>();
            this.EFORM_QM_NEW_TECHNOLOGY_DETAILS = new HashSet<EFORM_QM_NEW_TECHNOLOGY_DETAILS>();
            this.EFORM_QM_PRESENT_WORK_DETAILS = new HashSet<EFORM_QM_PRESENT_WORK_DETAILS>();
            this.EFORM_QM_PROTECTION_WORK = new HashSet<EFORM_QM_PROTECTION_WORK>();
            this.EFORM_QM_QC_TEST_DETAILS = new HashSet<EFORM_QM_QC_TEST_DETAILS>();
            this.EFORM_QM_QUALITY_ATTENTION = new HashSet<EFORM_QM_QUALITY_ATTENTION>();
            this.EFORM_QM_QUALITY_GRADING = new HashSet<EFORM_QM_QUALITY_GRADING>();
            this.EFORM_QM_ROAD_FURNITURE_MARKINGS = new HashSet<EFORM_QM_ROAD_FURNITURE_MARKINGS>();
            this.EFORM_QM_SHOULDERS = new HashSet<EFORM_QM_SHOULDERS>();
            this.EFORM_QM_SIDE_AND_CATCH_DRAINS_EARTHEN = new HashSet<EFORM_QM_SIDE_AND_CATCH_DRAINS_EARTHEN>();
            this.EFORM_QM_SIDE_SLOPES = new HashSet<EFORM_QM_SIDE_SLOPES>();
            this.EFORM_QM_CHILD_EARTHWORK_SUBGRADE_UCS_DETAILS = new HashSet<EFORM_QM_CHILD_EARTHWORK_SUBGRADE_UCS_DETAILS>();
            this.EFORM_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_COST = new HashSet<EFORM_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_COST>();
            this.EFORM_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_PROG = new HashSet<EFORM_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_PROG>();
            this.EFORM_QM_QOM_EMBANKMENT = new HashSet<EFORM_QM_QOM_EMBANKMENT>();
            this.EFORM_QM_BITUMINOUS_BASE_COURSE = new HashSet<EFORM_QM_BITUMINOUS_BASE_COURSE>();
            this.EFORM_BRIDGE_PIU_MIX_DESIGN_DETAILS = new HashSet<EFORM_BRIDGE_PIU_MIX_DESIGN_DETAILS>();
            this.EFORM_BRIDGE_PIU_PRGS_DETAILS = new HashSet<EFORM_BRIDGE_PIU_PRGS_DETAILS>();
            this.EFORM_BRIDGE_PIU_QC_DETAILS = new HashSet<EFORM_BRIDGE_PIU_QC_DETAILS>();
            this.EFORM_BRIDGE_QC_OFFICIAL_DETAILS = new HashSet<EFORM_BRIDGE_QC_OFFICIAL_DETAILS>();
            this.EFORM_BRIDGE_QM_ACTION_TAKEN_PIU = new HashSet<EFORM_BRIDGE_QM_ACTION_TAKEN_PIU>();
            this.EFORM_BRIDGE_QM_APPROACH = new HashSet<EFORM_BRIDGE_QM_APPROACH>();
            this.EFORM_BRIDGE_QM_ARRANGEMENTS_OBS_DETAILS = new HashSet<EFORM_BRIDGE_QM_ARRANGEMENTS_OBS_DETAILS>();
            this.EFORM_BRIDGE_QM_BEARING = new HashSet<EFORM_BRIDGE_QM_BEARING>();
            this.EFORM_BRIDGE_QM_CHILD_BAILEY_BRIDGE_SUPERSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_CHILD_BAILEY_BRIDGE_SUPERSTRUCTURE>();
            this.EFORM_BRIDGE_QM_CHILD_BASE_COURSE_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_BASE_COURSE_APPROACH>();
            this.EFORM_BRIDGE_QM_CHILD_BEARING_TYPE = new HashSet<EFORM_BRIDGE_QM_CHILD_BEARING_TYPE>();
            this.EFORM_BRIDGE_QM_CHILD_CO_MATERIAL_BAILEY_SUPERSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_CHILD_CO_MATERIAL_BAILEY_SUPERSTRUCTURE>();
            this.EFORM_BRIDGE_QM_CHILD_CO_MATERIAL_STEEL_SUPERSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_CHILD_CO_MATERIAL_STEEL_SUPERSTRUCTURE>();
            this.EFORM_BRIDGE_QM_CHILD_COMPL_ACTIVITY_RCC_SUPERSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_CHILD_COMPL_ACTIVITY_RCC_SUPERSTRUCTURE>();
            this.EFORM_BRIDGE_QM_CHILD_COMPL_QOM_FOUNDATION = new HashSet<EFORM_BRIDGE_QM_CHILD_COMPL_QOM_FOUNDATION>();
            this.EFORM_BRIDGE_QM_CHILD_COMPLETED_SUBSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_CHILD_COMPLETED_SUBSTRUCTURE>();
            this.EFORM_BRIDGE_QM_CHILD_EMBANKMENT_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_EMBANKMENT_APPROACH>();
            this.EFORM_BRIDGE_QM_CHILD_OBS_FURNITURE_MARKING = new HashSet<EFORM_BRIDGE_QM_CHILD_OBS_FURNITURE_MARKING>();
            this.EFORM_BRIDGE_QM_CHILD_ON_QOM_BAILEY_SUPERSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_CHILD_ON_QOM_BAILEY_SUPERSTRUCTURE>();
            this.EFORM_BRIDGE_QM_CHILD_ON_QOM_RCC_SUPERSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_CHILD_ON_QOM_RCC_SUPERSTRUCTURE>();
            this.EFORM_BRIDGE_QM_CHILD_ON_QOM_STEEL_SUPERSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_CHILD_ON_QOM_STEEL_SUPERSTRUCTURE>();
            this.EFORM_BRIDGE_QM_CHILD_ON_QOM_SUBSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_CHILD_ON_QOM_SUBSTRUCTURE>();
            this.EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_FOUNDATION = new HashSet<EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_FOUNDATION>();
            this.EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_SUBSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_SUBSTRUCTURE>();
            this.EFORM_BRIDGE_QM_CHILD_PROTECH_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_PROTECH_APPROACH>();
            this.EFORM_BRIDGE_QM_CHILD_QOM_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_QOM_APPROACH>();
            this.EFORM_BRIDGE_QM_CHILD_RCC_SUPERSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_CHILD_RCC_SUPERSTRUCTURE>();
            this.EFORM_BRIDGE_QM_CHILD_STEEL_SUPERSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_CHILD_STEEL_SUPERSTRUCTURE>();
            this.EFORM_BRIDGE_QM_CHILD_SUB_BASE_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_SUB_BASE_APPROACH>();
            this.EFORM_BRIDGE_QM_CHILD_WEARING_COURSE_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_WEARING_COURSE_APPROACH>();
            this.EFORM_BRIDGE_QM_CHILD_WORKMENSHIP_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_WORKMENSHIP_APPROACH>();
            this.EFORM_BRIDGE_QM_COMPLETED_FOUNDATION = new HashSet<EFORM_BRIDGE_QM_COMPLETED_FOUNDATION>();
            this.EFORM_BRIDGE_QM_COMPLETED_SUBSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_COMPLETED_SUBSTRUCTURE>();
            this.EFORM_BRIDGE_QM_DEFICIENCY = new HashSet<EFORM_BRIDGE_QM_DEFICIENCY>();
            this.EFORM_BRIDGE_QM_DIFFERENCE_IN_OBSERVATION = new HashSet<EFORM_BRIDGE_QM_DIFFERENCE_IN_OBSERVATION>();
            this.EFORM_BRIDGE_QM_EXPANSION = new HashSet<EFORM_BRIDGE_QM_EXPANSION>();
            this.EFORM_BRIDGE_QM_FOUNDATION = new HashSet<EFORM_BRIDGE_QM_FOUNDATION>();
            this.EFORM_BRIDGE_QM_FURNITURE_MARKINGS = new HashSet<EFORM_BRIDGE_QM_FURNITURE_MARKINGS>();
            this.EFORM_BRIDGE_QM_GENERAL_DETAILS = new HashSet<EFORM_BRIDGE_QM_GENERAL_DETAILS>();
            this.EFORM_BRIDGE_QM_ITEM_APPLICABLE_DETAILS = new HashSet<EFORM_BRIDGE_QM_ITEM_APPLICABLE_DETAILS>();
            this.EFORM_BRIDGE_QM_LOAD_TEST = new HashSet<EFORM_BRIDGE_QM_LOAD_TEST>();
            this.EFORM_BRIDGE_QM_ONGOING_FOUNDATION = new HashSet<EFORM_BRIDGE_QM_ONGOING_FOUNDATION>();
            this.EFORM_BRIDGE_QM_ONGOING_SUBSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_ONGOING_SUBSTRUCTURE>();
            this.EFORM_BRIDGE_QM_OVERALL_GRADING = new HashSet<EFORM_BRIDGE_QM_OVERALL_GRADING>();
            this.EFORM_BRIDGE_QM_QC_TEST_DETAILS = new HashSet<EFORM_BRIDGE_QM_QC_TEST_DETAILS>();
            this.EFORM_BRIDGE_QM_QUALITY_ATTENTION = new HashSet<EFORM_BRIDGE_QM_QUALITY_ATTENTION>();
            this.EFORM_BRIDGE_QM_QUALITY_GRADING = new HashSet<EFORM_BRIDGE_QM_QUALITY_GRADING>();
            this.EFORM_BRIDGE_QM_SUBSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_SUBSTRUCTURE>();
            this.EFORM_BRIDGE_QM_SUPERSTRUCTURE = new HashSet<EFORM_BRIDGE_QM_SUPERSTRUCTURE>();
            this.EFORM_BRIDGE_QM_TEST_RESULT_VERIFICATION_DETAILS = new HashSet<EFORM_BRIDGE_QM_TEST_RESULT_VERIFICATION_DETAILS>();
            this.EFORM_BRIDGE_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_COST = new HashSet<EFORM_BRIDGE_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_COST>();
            this.EFORM_BRIDGE_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_PROG = new HashSet<EFORM_BRIDGE_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_PROG>();
            this.EFORM_QM_TEST_RESULT_VERIFICATION_DETAILS = new HashSet<EFORM_QM_TEST_RESULT_VERIFICATION_DETAILS>();
            this.EFORM_BRIDGE_PIU_PARTICULARS = new HashSet<EFORM_BRIDGE_PIU_PARTICULARS>();
            this.EFORM_BRIDGE_QM_CHILD_ON_QOM_FOUNDATION = new HashSet<EFORM_BRIDGE_QM_CHILD_ON_QOM_FOUNDATION>();
            this.EFORM_DU_LOG = new HashSet<EFORM_DU_LOG>();
            this.EFORM_TR_ITEM_APPLICABLE_DETAILS = new HashSet<EFORM_TR_ITEM_APPLICABLE_DETAILS>();
            this.EFORM_TR_MAIN_ITEM_OPTIONS_SELECTED_DETAIL = new HashSet<EFORM_TR_MAIN_ITEM_OPTIONS_SELECTED_DETAIL>();
            this.EFORM_TR_SUBITEM_OPTIONS_SELECTED_DETAIL = new HashSet<EFORM_TR_SUBITEM_OPTIONS_SELECTED_DETAIL>();
            this.EFORM_TR_TYPEA_DETAIL = new HashSet<EFORM_TR_TYPEA_DETAIL>();
            this.EFORM_TR_TYPEA_SUMMARY = new HashSet<EFORM_TR_TYPEA_SUMMARY>();
            this.EFORM_TR_TYPEB_DETAIL = new HashSet<EFORM_TR_TYPEB_DETAIL>();
            this.EFORM_TR_TYPEB_SUMMARY = new HashSet<EFORM_TR_TYPEB_SUMMARY>();
            this.EFORM_TR_TYPEC_DETAIL = new HashSet<EFORM_TR_TYPEC_DETAIL>();
            this.EFORM_TR_TYPEC_SUMMARY = new HashSet<EFORM_TR_TYPEC_SUMMARY>();
            this.EFORM_TR_UCS_TEST_DETAILS = new HashSet<EFORM_TR_UCS_TEST_DETAILS>();
            this.EFORM_TEST_REPORT_FILE = new HashSet<EFORM_TEST_REPORT_FILE>();
            this.EFORM_QM_OVERALL_GRADING = new HashSet<EFORM_QM_OVERALL_GRADING>();
        }
    
        public int EFORM_ID { get; set; }
        public string EFORM_NO { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public int ADMIN_SCHEDULE_CODE { get; set; }
        public int ADMIN_SCHEDULE_MONTH { get; set; }
        public int ADMIN_SCHEDULE_YEAR { get; set; }
        public string WORK_STATUS_PER_QUALITY { get; set; }
        public int ADMIN_QM_CODE { get; set; }
        public string IS_COMPLETED { get; set; }
        public string ADMIN_QM_TYPE { get; set; }
        public string IS_VALID { get; set; }
        public string PART1_TEMPLATE_VERSION { get; set; }
        public string PART2_TEMPLATE_VERSION { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string IPADD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_QC_DETAILS> EFORM_PIU_QC_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_GEOMETRICS_DETAILS> EFORM_QM_GEOMETRICS_DETAILS { get; set; }
        public virtual QUALITY_QM_SCHEDULE QUALITY_QM_SCHEDULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_ITEM_APPLICABLE_DETAILS> EFORM_QM_ITEM_APPLICABLE_DETAILS { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PDF_UPLOAD_DETAIL> EFORM_PDF_UPLOAD_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_GENERAL_INFO> EFORM_PIU_GENERAL_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_ITEM_APPLICABLE_DETAILS> EFORM_PIU_ITEM_APPLICABLE_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_MIX_DESIGN_DETAILS> EFORM_PIU_MIX_DESIGN_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_NEW_TECHNOLOGY_DETAILS> EFORM_PIU_NEW_TECHNOLOGY_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_PREVIOUS_INSP_DETAILS> EFORM_PIU_PREVIOUS_INSP_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_PRGS_DETAILS> EFORM_PIU_PRGS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_TECHNOLOGY_DETAIL> EFORM_PIU_TECHNOLOGY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PREFILLED_DETAILS> EFORM_PREFILLED_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QC_OFFICIAL_DETAILS> EFORM_QC_OFFICIAL_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_ACTION_TAKEN_PIU> EFORM_QM_ACTION_TAKEN_PIU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_ARRANGEMENTS_OBS_DETAILS> EFORM_QM_ARRANGEMENTS_OBS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_BASE_COURSE_I> EFORM_QM_BASE_COURSE_I { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_BASE_COURSE_II> EFORM_QM_BASE_COURSE_II { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_BASE_COURSE_III> EFORM_QM_BASE_COURSE_III { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_BITUMINOUS_SURFACE_COURSE> EFORM_QM_BITUMINOUS_SURFACE_COURSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_EARTHWORK_SUBGRADE_CBR_DETAILS> EFORM_QM_CHILD_EARTHWORK_SUBGRADE_CBR_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CC_PUCCA_DRAINS> EFORM_QM_CC_PUCCA_DRAINS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CC_SR_PVAEMENTS> EFORM_QM_CC_SR_PVAEMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CDWORKS_SLAB_CULVERTS> EFORM_QM_CDWORKS_SLAB_CULVERTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CDWORKS_PIPE_CULVERTS> EFORM_QM_CDWORKS_PIPE_CULVERTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_BASECOURSE_UCS_DETAILS_LAYER1> EFORM_QM_CHILD_BASECOURSE_UCS_DETAILS_LAYER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_BASECOURSE_UCS_DETAILS_LAYER2> EFORM_QM_CHILD_BASECOURSE_UCS_DETAILS_LAYER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_BASECOURSE_UCS_DETAILS_LAYER3> EFORM_QM_CHILD_BASECOURSE_UCS_DETAILS_LAYER3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_BITUMINOUS_OBSERVATION_DETAILS> EFORM_QM_CHILD_BITUMINOUS_OBSERVATION_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_BITUMINOUS_SURFACE_COARSE_DETAILS> EFORM_QM_CHILD_BITUMINOUS_SURFACE_COARSE_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_CC_AND_SR_PAVEMENTS_OBSERVATION_DETAILS> EFORM_QM_CHILD_CC_AND_SR_PAVEMENTS_OBSERVATION_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_CC_PUCCA_DRAINS_OBSERVATION_DETAILS> EFORM_QM_CHILD_CC_PUCCA_DRAINS_OBSERVATION_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_CDWORKS_PIPE_CULVERTS_DETAILS> EFORM_QM_CHILD_CDWORKS_PIPE_CULVERTS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_CDWORKS_SLAB_CULVERTS_DETAILS> EFORM_QM_CHILD_CDWORKS_SLAB_CULVERTS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_CRASH_BARRIERS_OBSERVATION_DETAILS> EFORM_QM_CHILD_CRASH_BARRIERS_OBSERVATION_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_CUT_SLOPE_DETAIL> EFORM_QM_CHILD_CUT_SLOPE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_DEGREE_OF_COMPAQ> EFORM_QM_CHILD_DEGREE_OF_COMPAQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_GRANULAR_UCS_DETAILS> EFORM_QM_CHILD_GRANULAR_UCS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_GROUP_SYMBOL_SOIL> EFORM_QM_CHILD_GROUP_SYMBOL_SOIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_OBSERVATION_WORKMANSHIP_LAYER1> EFORM_QM_CHILD_OBSERVATION_WORKMANSHIP_LAYER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_OBSERVATION_WORKMANSHIP_LAYER2> EFORM_QM_CHILD_OBSERVATION_WORKMANSHIP_LAYER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_OBSERVATION_WORKMANSHIP_LAYER3> EFORM_QM_CHILD_OBSERVATION_WORKMANSHIP_LAYER3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_PROT_WORKS_QOM_DETAILS> EFORM_QM_CHILD_PROT_WORKS_QOM_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_PROT_WORKS_WORKMANSHIP_OF_RS_DETAILS> EFORM_QM_CHILD_PROT_WORKS_WORKMANSHIP_OF_RS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_QOM_WORKMENSHIP> EFORM_QM_CHILD_QOM_WORKMENSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_ROAD_FURNITURE_MARKINGS_OBSERVATION_DETAILS> EFORM_QM_CHILD_ROAD_FURNITURE_MARKINGS_OBSERVATION_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_SD_AND_CW_DRAINS_DETAILS> EFORM_QM_CHILD_SD_AND_CW_DRAINS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_SHOULDERS_MATERIAL_DETAILS> EFORM_QM_CHILD_SHOULDERS_MATERIAL_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_SHOULDERS_UCS_DETAILS> EFORM_QM_CHILD_SHOULDERS_UCS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_SIDE_SLOPE_DETAIL> EFORM_QM_CHILD_SIDE_SLOPE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_COMPAQ_EMBANKMENT> EFORM_QM_COMPAQ_EMBANKMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CRASH_BARRIERS_ROAD_SAFETY> EFORM_QM_CRASH_BARRIERS_ROAD_SAFETY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_DEFICIENCY_PREPARATION> EFORM_QM_DEFICIENCY_PREPARATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_DIFFEENCE_IN_OBSERVATION> EFORM_QM_DIFFEENCE_IN_OBSERVATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_GRANULAR_SUBBASE> EFORM_QM_GRANULAR_SUBBASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_NEW_TECHNOLOGY_DETAILS> EFORM_QM_NEW_TECHNOLOGY_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_PRESENT_WORK_DETAILS> EFORM_QM_PRESENT_WORK_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_PROTECTION_WORK> EFORM_QM_PROTECTION_WORK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_QC_TEST_DETAILS> EFORM_QM_QC_TEST_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_QUALITY_ATTENTION> EFORM_QM_QUALITY_ATTENTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_QUALITY_GRADING> EFORM_QM_QUALITY_GRADING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_ROAD_FURNITURE_MARKINGS> EFORM_QM_ROAD_FURNITURE_MARKINGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_SHOULDERS> EFORM_QM_SHOULDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_SIDE_AND_CATCH_DRAINS_EARTHEN> EFORM_QM_SIDE_AND_CATCH_DRAINS_EARTHEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_SIDE_SLOPES> EFORM_QM_SIDE_SLOPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_EARTHWORK_SUBGRADE_UCS_DETAILS> EFORM_QM_CHILD_EARTHWORK_SUBGRADE_UCS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_COST> EFORM_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_COST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_PROG> EFORM_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_PROG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_QOM_EMBANKMENT> EFORM_QM_QOM_EMBANKMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_BITUMINOUS_BASE_COURSE> EFORM_QM_BITUMINOUS_BASE_COURSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_PIU_MIX_DESIGN_DETAILS> EFORM_BRIDGE_PIU_MIX_DESIGN_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_PIU_PRGS_DETAILS> EFORM_BRIDGE_PIU_PRGS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_PIU_QC_DETAILS> EFORM_BRIDGE_PIU_QC_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QC_OFFICIAL_DETAILS> EFORM_BRIDGE_QC_OFFICIAL_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_ACTION_TAKEN_PIU> EFORM_BRIDGE_QM_ACTION_TAKEN_PIU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_APPROACH> EFORM_BRIDGE_QM_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_ARRANGEMENTS_OBS_DETAILS> EFORM_BRIDGE_QM_ARRANGEMENTS_OBS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_BEARING> EFORM_BRIDGE_QM_BEARING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_BAILEY_BRIDGE_SUPERSTRUCTURE> EFORM_BRIDGE_QM_CHILD_BAILEY_BRIDGE_SUPERSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_BASE_COURSE_APPROACH> EFORM_BRIDGE_QM_CHILD_BASE_COURSE_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_BEARING_TYPE> EFORM_BRIDGE_QM_CHILD_BEARING_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_CO_MATERIAL_BAILEY_SUPERSTRUCTURE> EFORM_BRIDGE_QM_CHILD_CO_MATERIAL_BAILEY_SUPERSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_CO_MATERIAL_STEEL_SUPERSTRUCTURE> EFORM_BRIDGE_QM_CHILD_CO_MATERIAL_STEEL_SUPERSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_COMPL_ACTIVITY_RCC_SUPERSTRUCTURE> EFORM_BRIDGE_QM_CHILD_COMPL_ACTIVITY_RCC_SUPERSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_COMPL_QOM_FOUNDATION> EFORM_BRIDGE_QM_CHILD_COMPL_QOM_FOUNDATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_COMPLETED_SUBSTRUCTURE> EFORM_BRIDGE_QM_CHILD_COMPLETED_SUBSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_EMBANKMENT_APPROACH> EFORM_BRIDGE_QM_CHILD_EMBANKMENT_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_OBS_FURNITURE_MARKING> EFORM_BRIDGE_QM_CHILD_OBS_FURNITURE_MARKING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_ON_QOM_BAILEY_SUPERSTRUCTURE> EFORM_BRIDGE_QM_CHILD_ON_QOM_BAILEY_SUPERSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_ON_QOM_RCC_SUPERSTRUCTURE> EFORM_BRIDGE_QM_CHILD_ON_QOM_RCC_SUPERSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_ON_QOM_STEEL_SUPERSTRUCTURE> EFORM_BRIDGE_QM_CHILD_ON_QOM_STEEL_SUPERSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_ON_QOM_SUBSTRUCTURE> EFORM_BRIDGE_QM_CHILD_ON_QOM_SUBSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_FOUNDATION> EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_FOUNDATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_SUBSTRUCTURE> EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_SUBSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_PROTECH_APPROACH> EFORM_BRIDGE_QM_CHILD_PROTECH_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_QOM_APPROACH> EFORM_BRIDGE_QM_CHILD_QOM_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_RCC_SUPERSTRUCTURE> EFORM_BRIDGE_QM_CHILD_RCC_SUPERSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_STEEL_SUPERSTRUCTURE> EFORM_BRIDGE_QM_CHILD_STEEL_SUPERSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_SUB_BASE_APPROACH> EFORM_BRIDGE_QM_CHILD_SUB_BASE_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_WEARING_COURSE_APPROACH> EFORM_BRIDGE_QM_CHILD_WEARING_COURSE_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_WORKMENSHIP_APPROACH> EFORM_BRIDGE_QM_CHILD_WORKMENSHIP_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_COMPLETED_FOUNDATION> EFORM_BRIDGE_QM_COMPLETED_FOUNDATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_COMPLETED_SUBSTRUCTURE> EFORM_BRIDGE_QM_COMPLETED_SUBSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_DEFICIENCY> EFORM_BRIDGE_QM_DEFICIENCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_DIFFERENCE_IN_OBSERVATION> EFORM_BRIDGE_QM_DIFFERENCE_IN_OBSERVATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_EXPANSION> EFORM_BRIDGE_QM_EXPANSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_FOUNDATION> EFORM_BRIDGE_QM_FOUNDATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_FURNITURE_MARKINGS> EFORM_BRIDGE_QM_FURNITURE_MARKINGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_GENERAL_DETAILS> EFORM_BRIDGE_QM_GENERAL_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_ITEM_APPLICABLE_DETAILS> EFORM_BRIDGE_QM_ITEM_APPLICABLE_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_LOAD_TEST> EFORM_BRIDGE_QM_LOAD_TEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_ONGOING_FOUNDATION> EFORM_BRIDGE_QM_ONGOING_FOUNDATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_ONGOING_SUBSTRUCTURE> EFORM_BRIDGE_QM_ONGOING_SUBSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_OVERALL_GRADING> EFORM_BRIDGE_QM_OVERALL_GRADING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_QC_TEST_DETAILS> EFORM_BRIDGE_QM_QC_TEST_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_QUALITY_ATTENTION> EFORM_BRIDGE_QM_QUALITY_ATTENTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_QUALITY_GRADING> EFORM_BRIDGE_QM_QUALITY_GRADING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_SUBSTRUCTURE> EFORM_BRIDGE_QM_SUBSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_SUPERSTRUCTURE> EFORM_BRIDGE_QM_SUPERSTRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_TEST_RESULT_VERIFICATION_DETAILS> EFORM_BRIDGE_QM_TEST_RESULT_VERIFICATION_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_COST> EFORM_BRIDGE_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_COST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_PROG> EFORM_BRIDGE_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_PROG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_TEST_RESULT_VERIFICATION_DETAILS> EFORM_QM_TEST_RESULT_VERIFICATION_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_PIU_PARTICULARS> EFORM_BRIDGE_PIU_PARTICULARS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_ON_QOM_FOUNDATION> EFORM_BRIDGE_QM_CHILD_ON_QOM_FOUNDATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_DU_LOG> EFORM_DU_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_ITEM_APPLICABLE_DETAILS> EFORM_TR_ITEM_APPLICABLE_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_MAIN_ITEM_OPTIONS_SELECTED_DETAIL> EFORM_TR_MAIN_ITEM_OPTIONS_SELECTED_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_SUBITEM_OPTIONS_SELECTED_DETAIL> EFORM_TR_SUBITEM_OPTIONS_SELECTED_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_TYPEA_DETAIL> EFORM_TR_TYPEA_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_TYPEA_SUMMARY> EFORM_TR_TYPEA_SUMMARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_TYPEB_DETAIL> EFORM_TR_TYPEB_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_TYPEB_SUMMARY> EFORM_TR_TYPEB_SUMMARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_TYPEC_DETAIL> EFORM_TR_TYPEC_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_TYPEC_SUMMARY> EFORM_TR_TYPEC_SUMMARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_UCS_TEST_DETAILS> EFORM_TR_UCS_TEST_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TEST_REPORT_FILE> EFORM_TEST_REPORT_FILE { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_OVERALL_GRADING> EFORM_QM_OVERALL_GRADING { get; set; }
    }
}
