//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_TR_ITEM_OPTIONS_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EFORM_TR_ITEM_OPTIONS_MASTER()
        {
            this.EFORM_TR_MAIN_ITEM_OPTIONS_SELECTED_DETAIL = new HashSet<EFORM_TR_MAIN_ITEM_OPTIONS_SELECTED_DETAIL>();
            this.EFORM_TR_SUBITEM_OPTIONS_SELECTED_DETAIL = new HashSet<EFORM_TR_SUBITEM_OPTIONS_SELECTED_DETAIL>();
        }
    
        public int OPTION_ID { get; set; }
        public int MAIN_ITEM_ID { get; set; }
        public Nullable<int> SUBITEM_ID { get; set; }
        public int IS_BELONGS_TO_MAIN_ITEM { get; set; }
        public string OPTION_DESC { get; set; }
    
        public virtual EFORM_TR_MAIN_ITEM_MASTER EFORM_TR_MAIN_ITEM_MASTER { get; set; }
        public virtual EFORM_TR_SUBITEM_MASTER EFORM_TR_SUBITEM_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_MAIN_ITEM_OPTIONS_SELECTED_DETAIL> EFORM_TR_MAIN_ITEM_OPTIONS_SELECTED_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_SUBITEM_OPTIONS_SELECTED_DETAIL> EFORM_TR_SUBITEM_OPTIONS_SELECTED_DETAIL { get; set; }
    }
}
