//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_QM_WORK_COMPLETED_IN_PROGRESS_ASPER_PROG
    {
        public int STATUS_ID { get; set; }
        public int EFORM_ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public string WORK_STATUS { get; set; }
        public string C_IS_COMPLETED_WITH_DELAY { get; set; }
        public Nullable<decimal> C_PERIOD_OF_DELAY { get; set; }
        public string C_AMOUNT_STATUS { get; set; }
        public Nullable<decimal> C_AMOUNT { get; set; }
        public string C_COMMENT { get; set; }
        public string P_IS_AS_PER_SCHEDULE { get; set; }
        public Nullable<decimal> P_EXT_MONTHS { get; set; }
        public string P_IS_AMOUNT_REFUNDED { get; set; }
        public Nullable<decimal> P_AMOUNT { get; set; }
        public Nullable<decimal> P_PANELTY_AMOUNT { get; set; }
        public string P_COMMENT { get; set; }
        public int QM_USER_ID { get; set; }
        public string IPADD { get; set; }
    
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
