//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_PDF_TABLE_MASTER
    {
        public int TABLE_ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public int PDF_PART { get; set; }
        public Nullable<int> PDF_POINT_NO { get; set; }
        public string MAIN_HEADING { get; set; }
        public string SUB_HEADING { get; set; }
        public string TABLE_TYPE { get; set; }
        public string DB_TABLE_NAME { get; set; }
    }
}
