//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_BRIDGE_QM_ONGOING_FOUNDATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EFORM_BRIDGE_QM_ONGOING_FOUNDATION()
        {
            this.EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_FOUNDATION = new HashSet<EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_FOUNDATION>();
            this.EFORM_BRIDGE_QM_CHILD_ON_QOM_FOUNDATION = new HashSet<EFORM_BRIDGE_QM_CHILD_ON_QOM_FOUNDATION>();
        }
    
        public int FOND_ON_ID { get; set; }
        public int EFORM_ID { get; set; }
        public int PR_ROAD_CODE { get; set; }
        public int FOUNDATION_ID { get; set; }
        public Nullable<decimal> FOUNDATION_ABUTMENT1 { get; set; }
        public Nullable<decimal> FOUNDATION_ABUTMENT2 { get; set; }
        public Nullable<decimal> FOUNDATION_PIERS1 { get; set; }
        public Nullable<decimal> FOUNDATION_PIERS2 { get; set; }
        public Nullable<decimal> FOUNDATION_PIERS3 { get; set; }
        public Nullable<decimal> FOUNDATION_PIERS4 { get; set; }
        public Nullable<decimal> FOUNDATION_PIERS5 { get; set; }
        public Nullable<decimal> FOUNDATION_PIERS6 { get; set; }
        public Nullable<decimal> FOUNDATION_PIERS7 { get; set; }
        public Nullable<decimal> FOUNDATION_PIERS8 { get; set; }
        public Nullable<decimal> FOUNDATION_PIERS9 { get; set; }
        public Nullable<decimal> FOUNDATION_RETURN1 { get; set; }
        public Nullable<decimal> FOUNDATION_RETURN2 { get; set; }
        public string IS_TEST_CONDUCTED { get; set; }
        public string IS_REINFORCEMENT_DONE { get; set; }
        public string IS_LAITANCE_PLUGGING { get; set; }
        public string IS_BOTTOM_PLUGGING { get; set; }
        public string IPADD { get; set; }
        public int USER_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_FOUNDATION> EFORM_BRIDGE_QM_CHILD_ON_WORKMENSHIP_FOUNDATION { get; set; }
        public virtual EFORM_BRIDGE_QM_FOUNDATION EFORM_BRIDGE_QM_FOUNDATION { get; set; }
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_ON_QOM_FOUNDATION> EFORM_BRIDGE_QM_CHILD_ON_QOM_FOUNDATION { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
