//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_MASTER_NEW_TECH_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EFORM_MASTER_NEW_TECH_ITEM()
        {
            this.EFORM_PIU_NEW_TECHNOLOGY_DETAILS = new HashSet<EFORM_PIU_NEW_TECHNOLOGY_DETAILS>();
            this.EFORM_QM_BASE_COURSE_I = new HashSet<EFORM_QM_BASE_COURSE_I>();
            this.EFORM_QM_BASE_COURSE_II = new HashSet<EFORM_QM_BASE_COURSE_II>();
            this.EFORM_QM_BASE_COURSE_III = new HashSet<EFORM_QM_BASE_COURSE_III>();
            this.EFORM_QM_BITUMINOUS_SURFACE_COURSE = new HashSet<EFORM_QM_BITUMINOUS_SURFACE_COURSE>();
            this.EFORM_QM_GRANULAR_SUBBASE = new HashSet<EFORM_QM_GRANULAR_SUBBASE>();
            this.EFORM_QM_NEW_TECHNOLOGY_DETAILS = new HashSet<EFORM_QM_NEW_TECHNOLOGY_DETAILS>();
            this.EFORM_QM_SHOULDERS = new HashSet<EFORM_QM_SHOULDERS>();
            this.EFORM_QM_BITUMINOUS_BASE_COURSE = new HashSet<EFORM_QM_BITUMINOUS_BASE_COURSE>();
        }
    
        public short TECH_ID { get; set; }
        public string TECH_NAME { get; set; }
        public string IS_ACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_NEW_TECHNOLOGY_DETAILS> EFORM_PIU_NEW_TECHNOLOGY_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_BASE_COURSE_I> EFORM_QM_BASE_COURSE_I { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_BASE_COURSE_II> EFORM_QM_BASE_COURSE_II { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_BASE_COURSE_III> EFORM_QM_BASE_COURSE_III { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_BITUMINOUS_SURFACE_COURSE> EFORM_QM_BITUMINOUS_SURFACE_COURSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_GRANULAR_SUBBASE> EFORM_QM_GRANULAR_SUBBASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_NEW_TECHNOLOGY_DETAILS> EFORM_QM_NEW_TECHNOLOGY_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_SHOULDERS> EFORM_QM_SHOULDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_BITUMINOUS_BASE_COURSE> EFORM_QM_BITUMINOUS_BASE_COURSE { get; set; }
    }
}
