//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_BRIDGE_QM_CHILD_QOM_APPROACH
    {
        public int QOM_ID { get; set; }
        public int EFORM_ID { get; set; }
        public int PR_ROAD_CODE { get; set; }
        public int APPROACH_ID { get; set; }
        public Nullable<decimal> RD_LOC { get; set; }
        public string STRUCTURE_TYPE { get; set; }
        public string PROTECTION_TYPE { get; set; }
        public string QOM_SPECIFI { get; set; }
        public string DESIGN_SHAPE { get; set; }
        public string QUALITY_ASSESMENT { get; set; }
        public int USER_ID { get; set; }
        public string IPADD { get; set; }
    
        public virtual EFORM_BRIDGE_QM_APPROACH EFORM_BRIDGE_QM_APPROACH { get; set; }
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
