//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_BRIDGE_QM_EXPANSION
    {
        public int EXPANSION_ID { get; set; }
        public int EFORM_ID { get; set; }
        public int PR_ROAD_CODE { get; set; }
        public string BURIED_OF_EXPANSION { get; set; }
        public string FILLER_OF_EXPANSION { get; set; }
        public string ASPHALTIC_OF_EXPANSION { get; set; }
        public string COMPRESSION_OF_EXPANSION { get; set; }
        public string SINGLE_OF_EXPANSION { get; set; }
        public string REINFORCED_OF_EXPANSION { get; set; }
        public string MODULAR_OF_EXPANSION { get; set; }
        public string FINGER_OF_EXPANSION { get; set; }
        public string REINFORCED_COUPLED_OF_EXPANSION { get; set; }
        public string IS_ANY_CRACK_IN_COAT { get; set; }
        public string IS_EXISTING_GAP_IMPROPER { get; set; }
        public string IS_CRACKING_IN_BITUMAN { get; set; }
        public string IS_SPLITTING_IN_NEOPRENE { get; set; }
        public string IS_CORROSION_IS_VISIBLE { get; set; }
        public string IS_DEBRIS_IN_JOINTS { get; set; }
        public string OBSERVATION_FOUND { get; set; }
        public string OTHER_OBSER_FOUND { get; set; }
        public string ITEM_GRADING_9 { get; set; }
        public string IMPROVEMENT_REMARK { get; set; }
        public string IPADD { get; set; }
        public int USER_ID { get; set; }
    
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
