//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_QC_OFFICIAL_DETAILS
    {
        public int OFFICIAL_ID { get; set; }
        public int QC_ID { get; set; }
        public int PR_ROAD_CODE { get; set; }
        public string OFFICIAL_TYPE { get; set; }
        public string OFFICIAL_NAME { get; set; }
        public string PAN { get; set; }
        public string IDENTITY_NUMBER { get; set; }
        public string MOBILE_NO { get; set; }
        public string EMAIL_ID { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string IPADD { get; set; }
        public int EFORM_ID { get; set; }
        public int USERID { get; set; }
    
        public virtual EFORM_PIU_QC_DETAILS EFORM_PIU_QC_DETAILS { get; set; }
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
