//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_BRIDGE_QM_CHILD_ON_QOM_SUBSTRUCTURE
    {
        public int LOC_ID { get; set; }
        public int SUBSTRUCTURE_ID { get; set; }
        public int SUBST_ON_ID { get; set; }
        public int EFORM_ID { get; set; }
        public int PR_ROAD_CODE { get; set; }
        public string WORK_ITEM_LOC { get; set; }
        public string CONCRETE_GRADE { get; set; }
        public string QM_CEMENT_QCR { get; set; }
        public string QM_COARSE_AGGR_QCR { get; set; }
        public string QM_FINE_AGGR_QCR { get; set; }
        public string QM_STEEL_QCR { get; set; }
        public string CONCRETE_TEST_NQM { get; set; }
        public string GRADE { get; set; }
        public string IPADD { get; set; }
        public int USER_ID { get; set; }
    
        public virtual EFORM_BRIDGE_QM_SUBSTRUCTURE EFORM_BRIDGE_QM_SUBSTRUCTURE { get; set; }
        public virtual EFORM_BRIDGE_QM_ONGOING_SUBSTRUCTURE EFORM_BRIDGE_QM_ONGOING_SUBSTRUCTURE { get; set; }
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
