//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_TR_DETAIL_ITEM_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EFORM_TR_DETAIL_ITEM_MASTER()
        {
            this.EFORM_TR_TYPEA_DETAIL = new HashSet<EFORM_TR_TYPEA_DETAIL>();
            this.EFORM_TR_TYPEB_DETAIL = new HashSet<EFORM_TR_TYPEB_DETAIL>();
            this.EFORM_TR_TYPEC_DETAIL = new HashSet<EFORM_TR_TYPEC_DETAIL>();
            this.EFORM_TR_DETAIL_ITEM_MASTER1 = new HashSet<EFORM_TR_DETAIL_ITEM_MASTER>();
        }
    
        public int DETAIL_ITEM_ID { get; set; }
        public int MAIN_ITEM_ID { get; set; }
        public int SUBITEM_ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string DETAIL_ITEM_DESC { get; set; }
        public Nullable<int> OPTION_ID { get; set; }
        public int IS_HEADER { get; set; }
        public int IS_ACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_TYPEA_DETAIL> EFORM_TR_TYPEA_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_TYPEB_DETAIL> EFORM_TR_TYPEB_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_TYPEC_DETAIL> EFORM_TR_TYPEC_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_TR_DETAIL_ITEM_MASTER> EFORM_TR_DETAIL_ITEM_MASTER1 { get; set; }
        public virtual EFORM_TR_DETAIL_ITEM_MASTER EFORM_TR_DETAIL_ITEM_MASTER2 { get; set; }
        public virtual EFORM_TR_MAIN_ITEM_MASTER EFORM_TR_MAIN_ITEM_MASTER { get; set; }
        public virtual EFORM_TR_SUBITEM_MASTER EFORM_TR_SUBITEM_MASTER { get; set; }
    }
}
