//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_BRIDGE_QM_COMPLETED_FOUNDATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EFORM_BRIDGE_QM_COMPLETED_FOUNDATION()
        {
            this.EFORM_BRIDGE_QM_CHILD_COMPL_QOM_FOUNDATION = new HashSet<EFORM_BRIDGE_QM_CHILD_COMPL_QOM_FOUNDATION>();
        }
    
        public int FOND_CO_ID { get; set; }
        public int EFORM_ID { get; set; }
        public int PR_ROAD_CODE { get; set; }
        public int FOUNDATION_ID { get; set; }
        public string IS_CONDUCTED_INDEP_LAB { get; set; }
        public string IS_NDT_CONDUCTED { get; set; }
        public string IPADD { get; set; }
        public int USER_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_COMPL_QOM_FOUNDATION> EFORM_BRIDGE_QM_CHILD_COMPL_QOM_FOUNDATION { get; set; }
        public virtual EFORM_BRIDGE_QM_FOUNDATION EFORM_BRIDGE_QM_FOUNDATION { get; set; }
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
