//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_BRIDGE_QM_APPROACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EFORM_BRIDGE_QM_APPROACH()
        {
            this.EFORM_BRIDGE_QM_CHILD_BASE_COURSE_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_BASE_COURSE_APPROACH>();
            this.EFORM_BRIDGE_QM_CHILD_EMBANKMENT_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_EMBANKMENT_APPROACH>();
            this.EFORM_BRIDGE_QM_CHILD_PROTECH_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_PROTECH_APPROACH>();
            this.EFORM_BRIDGE_QM_CHILD_QOM_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_QOM_APPROACH>();
            this.EFORM_BRIDGE_QM_CHILD_SUB_BASE_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_SUB_BASE_APPROACH>();
            this.EFORM_BRIDGE_QM_CHILD_WEARING_COURSE_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_WEARING_COURSE_APPROACH>();
            this.EFORM_BRIDGE_QM_CHILD_WORKMENSHIP_APPROACH = new HashSet<EFORM_BRIDGE_QM_CHILD_WORKMENSHIP_APPROACH>();
        }
    
        public int APPROACH_ID { get; set; }
        public int EFORM_ID { get; set; }
        public int PR_ROAD_CODE { get; set; }
        public string ITEM_GRADING_10 { get; set; }
        public string IMPROVEMENT_REMARK { get; set; }
        public string IPADD { get; set; }
        public int USER_ID { get; set; }
    
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_BASE_COURSE_APPROACH> EFORM_BRIDGE_QM_CHILD_BASE_COURSE_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_EMBANKMENT_APPROACH> EFORM_BRIDGE_QM_CHILD_EMBANKMENT_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_PROTECH_APPROACH> EFORM_BRIDGE_QM_CHILD_PROTECH_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_QOM_APPROACH> EFORM_BRIDGE_QM_CHILD_QOM_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_SUB_BASE_APPROACH> EFORM_BRIDGE_QM_CHILD_SUB_BASE_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_WEARING_COURSE_APPROACH> EFORM_BRIDGE_QM_CHILD_WEARING_COURSE_APPROACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_CHILD_WORKMENSHIP_APPROACH> EFORM_BRIDGE_QM_CHILD_WORKMENSHIP_APPROACH { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
