//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_QM_CHILD_QOM_WORKMENSHIP
    {
        public int WMS_ID { get; set; }
        public int SUBBASE_ID { get; set; }
        public int EFORM_ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public Nullable<decimal> LOCATION_RD { get; set; }
        public string IS_CONFORM_TO_GRADING { get; set; }
        public string IS_MAT_SUITABLE { get; set; }
        public Nullable<decimal> DRY_DENSITY { get; set; }
        public Nullable<decimal> PERCENT_COMPAQ { get; set; }
        public string IS_COMPAQ_ADIQUATE { get; set; }
        public Nullable<decimal> THICKNESS_ASPER_DPR { get; set; }
        public Nullable<decimal> THICKNESS_MEAS { get; set; }
        public string IS_PRISCRIBED { get; set; }
        public int QM_USER_ID { get; set; }
        public string IPADD { get; set; }
    
        public virtual EFORM_QM_GRANULAR_SUBBASE EFORM_QM_GRANULAR_SUBBASE { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
