//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_BRIDGE_MASTER_WORK_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EFORM_BRIDGE_MASTER_WORK_ITEM()
        {
            this.EFORM_BRIDGE_PIU_PRGS_DETAILS = new HashSet<EFORM_BRIDGE_PIU_PRGS_DETAILS>();
            this.EFORM_BRIDGE_QM_QC_TEST_DETAILS = new HashSet<EFORM_BRIDGE_QM_QC_TEST_DETAILS>();
        }
    
        public int ITEM_ID { get; set; }
        public string ITEM_DESC { get; set; }
        public string ITEM_FLAG { get; set; }
        public string IS_ACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_PIU_PRGS_DETAILS> EFORM_BRIDGE_PIU_PRGS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_BRIDGE_QM_QC_TEST_DETAILS> EFORM_BRIDGE_QM_QC_TEST_DETAILS { get; set; }
    }
}
