//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_TEST_REPORT_FILE
    {
        public int FILE_ID { get; set; }
        public int EFORM_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_PATH { get; set; }
        public System.DateTime FILE_UPLOAD_DATE { get; set; }
        public string IS_FINALISED { get; set; }
        public int USERID { get; set; }
        public string IPADD { get; set; }
        public string TEMPLATE_VERSION { get; set; }
        public string IS_EFORM { get; set; }
    
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
    }
}
