//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_QM_PROTECTION_WORK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EFORM_QM_PROTECTION_WORK()
        {
            this.EFORM_QM_CHILD_PROT_WORKS_QOM_DETAILS = new HashSet<EFORM_QM_CHILD_PROT_WORKS_QOM_DETAILS>();
            this.EFORM_QM_CHILD_PROT_WORKS_WORKMANSHIP_OF_RS_DETAILS = new HashSet<EFORM_QM_CHILD_PROT_WORKS_WORKMANSHIP_OF_RS_DETAILS>();
        }
    
        public int WORK_ID { get; set; }
        public int EFORM_ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public string IS_DPR_PROVISION { get; set; }
        public string IS_RETAINING_WALL { get; set; }
        public string IS_BREAST_WALL { get; set; }
        public string IS_PARAPET_WALL { get; set; }
        public string IS_ANY_OTHER_TYPE { get; set; }
        public Nullable<decimal> RETAINING_WALL_LENGTH { get; set; }
        public Nullable<decimal> BREAST_WALL_LENGTH { get; set; }
        public Nullable<decimal> PARAPET_WALL_LENGTH { get; set; }
        public string OTHER_TYPE1_NAME { get; set; }
        public string OTHER_TYPE2_NAME { get; set; }
        public string OTHER_TYPE3_NAME { get; set; }
        public Nullable<decimal> OTHER_A_WALL_LENGTH { get; set; }
        public Nullable<decimal> OTHER_B_WALL_LENGTH { get; set; }
        public Nullable<decimal> OTHER_C_WALL_LENGTH { get; set; }
        public Nullable<decimal> TOT_LENGTH { get; set; }
        public string IS_STONE_MEASONRY_ACCEPTABLE { get; set; }
        public string IS_BOND_STONE_PROVIDED { get; set; }
        public string ITEM_GRADING_15 { get; set; }
        public string IMPROVE_SUGGESTIONS { get; set; }
        public int QM_USER_ID { get; set; }
        public string IPADD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_PROT_WORKS_QOM_DETAILS> EFORM_QM_CHILD_PROT_WORKS_QOM_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_PROT_WORKS_WORKMANSHIP_OF_RS_DETAILS> EFORM_QM_CHILD_PROT_WORKS_WORKMANSHIP_OF_RS_DETAILS { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
