//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_QM_CDWORKS_PIPE_CULVERTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EFORM_QM_CDWORKS_PIPE_CULVERTS()
        {
            this.EFORM_QM_CHILD_CDWORKS_PIPE_CULVERTS_DETAILS = new HashSet<EFORM_QM_CHILD_CDWORKS_PIPE_CULVERTS_DETAILS>();
        }
    
        public int CDWORKS_ID { get; set; }
        public int EFORM_ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public Nullable<decimal> TOTAL_PIPE_CULVERTS { get; set; }
        public Nullable<decimal> MINIMUM_CUSHION { get; set; }
        public Nullable<decimal> CLASS_OF_PIPES_NP2 { get; set; }
        public Nullable<decimal> CLASS_OF_PIPES_NP3 { get; set; }
        public string GRADE_OF_CONCRETE { get; set; }
        public string IS_PROTECTION_PROVIDED { get; set; }
        public string IS_PIPE_PROPERLY_PLACED { get; set; }
        public string ITEM_GRADING_13 { get; set; }
        public string IMPROVE_SUGGESTIONS { get; set; }
        public int QM_USER_ID { get; set; }
        public string IPADD { get; set; }
    
        public virtual UM_User_Master UM_User_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_CHILD_CDWORKS_PIPE_CULVERTS_DETAILS> EFORM_QM_CHILD_CDWORKS_PIPE_CULVERTS_DETAILS { get; set; }
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
