//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFORM_QM_CHILD_PROT_WORKS_QOM_DETAILS
    {
        public int QOM_ID { get; set; }
        public int WORK_ID { get; set; }
        public int EFORM_ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public Nullable<decimal> LOCATION_RD { get; set; }
        public string STRUCTURE_TYPE { get; set; }
        public string PROTECTION_TYPE { get; set; }
        public string GENERAL_QOM { get; set; }
        public Nullable<decimal> AVG_WIDTH_ASPER_DPR { get; set; }
        public Nullable<decimal> AVG_HEIGHT_ASPER_DPR { get; set; }
        public Nullable<decimal> AVG_WIDTH_ASPER_REC { get; set; }
        public Nullable<decimal> AVG_HEIGHT_ASPER_REC { get; set; }
        public string IS_COMPR_SOM { get; set; }
        public int QM_USER_ID { get; set; }
        public string IPADD { get; set; }
    
        public virtual EFORM_QM_PROTECTION_WORK EFORM_QM_PROTECTION_WORK { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual EFORM_MASTER EFORM_MASTER { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
