//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMARG_ROAD_WISE_BALANCE_WORK_PACKAGE_DETAILS
    {
        public int RECORD_ID { get; set; }
        public int STATE_CODE { get; set; }
        public int DISTRICT_CODE { get; set; }
        public int BLOCK_CODE { get; set; }
        public int ROAD_CODE { get; set; }
        public int PIU_CODE { get; set; }
        public string PACKAGE_NO { get; set; }
        public string EMARG_PACKAGE_NO { get; set; }
        public string CONTRACTOR_PAN { get; set; }
        public string CONTRACTOR_NAME { get; set; }
        public string AGREEMENT_NO { get; set; }
        public System.DateTime AGREEMENT_DATE { get; set; }
        public System.DateTime MAINTENANCE_START_DATE { get; set; }
        public System.DateTime MAINTENANCE_END_DATE { get; set; }
        public string DATA_FLAG { get; set; }
        public Nullable<int> MANE_PR_CONTRACT_CODE { get; set; }
        public Nullable<int> IMS_ROAD_CODE { get; set; }
    
        public virtual ADMIN_DEPARTMENT ADMIN_DEPARTMENT { get; set; }
        public virtual EMARG_ROAD_WISE_BALANCE_WORK_PACKAGE_DETAILS EMARG_ROAD_WISE_BALANCE_WORK_PACKAGE_DETAILS1 { get; set; }
        public virtual EMARG_ROAD_WISE_BALANCE_WORK_PACKAGE_DETAILS EMARG_ROAD_WISE_BALANCE_WORK_PACKAGE_DETAILS2 { get; set; }
        public virtual MANE_IMS_CONTRACT MANE_IMS_CONTRACT { get; set; }
        public virtual MASTER_BLOCK MASTER_BLOCK { get; set; }
        public virtual MASTER_DISTRICT MASTER_DISTRICT { get; set; }
        public virtual MASTER_STATE MASTER_STATE { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
