//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXEC_ROADS_MONTHLY_STATUS_PERIODIC_MAINT_FINANCIAL
    {
        public int MAINT_ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public int MANE_PROG_YEAR { get; set; }
        public int MANE_PROG_MONTH { get; set; }
        public decimal MANE_PROFILE_COST { get; set; }
        public decimal MANE_PERIODIC_COST { get; set; }
        public decimal MANE_OTHER_ITEM_COSE { get; set; }
        public decimal MANE_TOTAL_COST { get; set; }
        public string MANE_ISCOMPLETED { get; set; }
        public Nullable<System.DateTime> MANE_COMPLETION_DATE { get; set; }
        public string MANE_IS_PER_INCENTIVE { get; set; }
        public Nullable<int> MANE_PER_INCENTIVE_YEAR { get; set; }
        public int MANE_IS_RENWAL { get; set; }
        public int MANE_RENEWAL_TYPE { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_RENEWAL_TYPE MASTER_RENEWAL_TYPE { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
