//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXEC_OFFICER_DETAILS
    {
        public int EXEC_OFFICER_ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public int EXEC_YEAR { get; set; }
        public int EXEC_MONTH { get; set; }
        public int MAST_OFFICER_CODE { get; set; }
        public Nullable<int> MAST_DESIG_CODE { get; set; }
    
        public virtual ADMIN_NODAL_OFFICERS ADMIN_NODAL_OFFICERS { get; set; }
        public virtual MASTER_DESIGNATION MASTER_DESIGNATION { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
