//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXEC_LSB_MONTHLY_STATUS
    {
        public int IMS_PR_ROAD_CODE { get; set; }
        public int EXEC_PROG_YEAR { get; set; }
        public int EXEC_PROG_MONTH { get; set; }
        public Nullable<decimal> EXEC_RAFT { get; set; }
        public Nullable<decimal> EXEC_FLOOR_PROTECTION { get; set; }
        public Nullable<decimal> EXEC_SINKING { get; set; }
        public Nullable<int> EXEC_BOTTOM_PLUGGING { get; set; }
        public Nullable<int> EXEC_TOP_PLUGGING { get; set; }
        public Nullable<int> EXEC_WELL_CAP { get; set; }
        public Nullable<decimal> EXEC_PIER_SHAFT { get; set; }
        public Nullable<int> EXEC_PIER_CAP { get; set; }
        public Nullable<int> EXEC_BEARINGS { get; set; }
        public Nullable<int> EXEC_DECK_SLAB { get; set; }
        public Nullable<decimal> EXEC_WEARING_COAT { get; set; }
        public Nullable<decimal> EXEC_POSTS_RAILING { get; set; }
        public Nullable<decimal> EXEC_APP_ROAD_WORK { get; set; }
        public Nullable<int> EXEC_APP_CD_WORKS { get; set; }
        public Nullable<decimal> EXEC_APP_COMPLETED { get; set; }
        public Nullable<decimal> EXEC_BRIDGE_COMPLETED { get; set; }
        public string EXEC_ISCOMPLETED { get; set; }
        public Nullable<System.DateTime> EXEC_COMPLETION_DATE { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
