//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_DROPPED_PROJECTS_PDF
    {
        public int DROP_PROJ_PDF_CODE { get; set; }
        public int DROP_REQ_CODE { get; set; }
        public string IMS_PDF_NAME { get; set; }
        public System.DateTime IMS_GENERATION_DATE { get; set; }
        public Nullable<System.DateTime> IMS_ORDER_DATE { get; set; }
        public string IMS_ORDER_NUMBER { get; set; }
        public string DROP_ORDER_BY { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual IMS_PROPOSAL_DROP_REQUEST IMS_PROPOSAL_DROP_REQUEST { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
