//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_PROPOSAL_DROP_REQUEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_PROPOSAL_DROP_REQUEST()
        {
            this.IMS_DROPPED_PROJECTS_PDF = new HashSet<IMS_DROPPED_PROJECTS_PDF>();
            this.IMS_PROPOSAL_DROP_REQUEST_DETAILS = new HashSet<IMS_PROPOSAL_DROP_REQUEST_DETAILS>();
        }
    
        public int DROP_REQ_CODE { get; set; }
        public System.DateTime REQUEST_DATE_TIME { get; set; }
        public int REQUEST_USERID { get; set; }
        public string REQUEST_IPADD { get; set; }
        public string REQUEST_LETTER_NO { get; set; }
        public Nullable<int> NO_WORKS_REQUESTED { get; set; }
        public Nullable<int> NO_WORKS_APPROVED { get; set; }
        public string DROP_LETTER_NO { get; set; }
        public Nullable<System.DateTime> DROP_APPROVED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_DROPPED_PROJECTS_PDF> IMS_DROPPED_PROJECTS_PDF { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_PROPOSAL_DROP_REQUEST_DETAILS> IMS_PROPOSAL_DROP_REQUEST_DETAILS { get; set; }
    }
}
