//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_PROPOSAL_CHANGE_PIU_LOG
    {
        public int ID { get; set; }
        public int ROAD_CODE { get; set; }
        public byte PMGSY_SCHEME { get; set; }
        public string PACKAGE_NUMBER { get; set; }
        public System.DateTime DATE_OF_UPDATION { get; set; }
        public int OLD_PIU_ID { get; set; }
        public int NEW_PIU_ID { get; set; }
        public int OLD_SRRDA_ID { get; set; }
        public int NEW_SRRDA_ID { get; set; }
    
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
