//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_PROPOSAL_SPLIT
    {
        public int IMS_PR_ROAD_CODE { get; set; }
        public int IMS_TOTAL_SPLIT { get; set; }
        public string IMS_SPLIT_STATUS { get; set; }
    
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
