//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_EC_CHECKLIST
    {
        public int MAST_EC_ID { get; set; }
        public int MAST_STATE_CODE { get; set; }
        public byte MAST_PMGSY_SCHEME { get; set; }
        public int IMS_YEAR { get; set; }
        public int IMS_BATCH { get; set; }
        public int MAST_AGENCY_CODE { get; set; }
        public string IMS_EC_TYPE { get; set; }
        public string IMS_CN_READY { get; set; }
        public string IMS_DRRP_OMMAS { get; set; }
        public string IMS_CNCUPL_READY { get; set; }
        public string IMS_DP_APPROVAL { get; set; }
        public string IMS_SLSC_PROCEEDING { get; set; }
        public string IMS_DPR_SCRUTINY { get; set; }
        public string IMS_PCI_REGISTER { get; set; }
        public string IMS_UNSEALED { get; set; }
        public string IMS_MP_DATA { get; set; }
        public string IMS_MAINT_YEARWISE { get; set; }
        public string IMS_ESTIMATE_SSR { get; set; }
        public Nullable<System.DateTime> IMS_SSR_DATE { get; set; }
        public string IMS_DPR_STA { get; set; }
        public string IMS_NIT_UPLOADED { get; set; }
        public string IMS_WORKS_CAPACITY { get; set; }
        public string IMS_IPAI_ACCOUNTS { get; set; }
        public string IMS_LWE_MHA { get; set; }
        public string IMS_WB_BATCH_SIZE { get; set; }
        public string IMS_WB_ECOP { get; set; }
        public string IMS_WB_STA_CLEARED { get; set; }
        public string IMS_CE_REMARKS { get; set; }
        public string IMS_CN_READY_NRRDA { get; set; }
        public string IMS_DRRP_OMMAS_NRRDA { get; set; }
        public string IMS_CNCUPL_READY_NRRDA { get; set; }
        public string IMS_DP_APPROVAL_NRRDA { get; set; }
        public string IMS_SLSC_PROCEEDING_NRRDA { get; set; }
        public string IMS_DPR_SCRUTINY_NRRDA { get; set; }
        public string IMS_PCI_REGISTER_NRRDA { get; set; }
        public string IMS_UNSEALED_NRRDA { get; set; }
        public string IMS_MP_DATA_NRRDA { get; set; }
        public string IMS_MAINT_YEARWISE_NRRDA { get; set; }
        public string IMS_ESTIMATE_SSR_NRRDA { get; set; }
        public Nullable<System.DateTime> IMS_SSR_DATE_NRRDA { get; set; }
        public string IMS_DPR_STA_NRRDA { get; set; }
        public string IMS_NIT_UPLOADED_NRRDA { get; set; }
        public string IMS_WORKS_CAPACITY_NRRDA { get; set; }
        public string IMS_IPAI_ACCOUNTS_NRRDA { get; set; }
        public string IMS_LWE_MHA_NRRDA { get; set; }
        public string IMS_WB_BATCH_SIZE_NRRDA { get; set; }
        public string IMS_WB_ECOP_NRRDA { get; set; }
        public string IMS_WB_STA_CLEARED_NRRDA { get; set; }
        public string IMS_NRRDA_REMARKS { get; set; }
        public Nullable<System.DateTime> IMS_CN_APPROVAL_DATE { get; set; }
        public Nullable<System.DateTime> IMS_EC_FINALIZE_DATE { get; set; }
        public string IMS_EC_LOCK { get; set; }
        public string IMS_EC_NRRDA_LOCK { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_AGENCY MASTER_AGENCY { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_EC_PDF_GENERATED IMS_EC_PDF_GENERATED { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
