//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_SANCTION_FOREST_CLEARANCE
    {
        public int IMS_FOREST_CLR_ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public string IMS_IS_FOREST_CLR_REQ { get; set; }
        public string IMS_IS_FOREST_CLR_OBT { get; set; }
        public string IMS_FOREST_CLR_FILE_NAME { get; set; }
        public Nullable<System.DateTime> IMS_FOREST_CLR_FILE_UPLOAD_DATE { get; set; }
        public int USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
