//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MABProgressLogDetails
    {
        public int LogID { get; set; }
        public string UserName { get; set; }
        public string MobileNo { get; set; }
        public string IMEINo { get; set; }
        public string OSVersion { get; set; }
        public string ModelName { get; set; }
        public string NetworkProvider { get; set; }
        public Nullable<System.DateTime> LoginDateTime { get; set; }
        public string AppVersion { get; set; }
        public string IPAddress { get; set; }
    }
}
