//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAINE_REPACKAGE_DETAILS
    {
        public int REPACKAGE_ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public string IMS_MAINT_REPACKAGE_ID { get; set; }
        public Nullable<decimal> START_CHAINAGE { get; set; }
        public Nullable<decimal> END_CHAINAGE { get; set; }
        public string ENTRY_BY { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    }
}
