//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANE_IMS_INSPECTION
    {
        public int IMS_PR_ROAD_CODE { get; set; }
        public int IMS_INSPECTION_CODE { get; set; }
        public int MAST_OFFICER_CODE { get; set; }
        public System.DateTime MANE_INSP_DATE { get; set; }
        public Nullable<System.DateTime> MANE_RECTIFICATION_DATE { get; set; }
        public string MANE_RECTIFICATION_STATUS { get; set; }
        public string MANE_REMARKS { get; set; }
    
        public virtual ADMIN_NODAL_OFFICERS ADMIN_NODAL_OFFICERS { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
