//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANE_EMARG_CONTRACT
    {
        public int IMS_PR_ROAD_CODE { get; set; }
        public int MANE_PR_CONTRACT_CODE { get; set; }
        public int EMARG_ID { get; set; }
        public int MAST_CON_ID { get; set; }
        public string MANE_AGREEMENT_NUMBER { get; set; }
        public Nullable<int> MANE_CONTRACT_NUMBER { get; set; }
        public Nullable<int> MANE_CONTRACT_ID { get; set; }
        public Nullable<System.DateTime> MANE_AGREEMENT_DATE { get; set; }
        public Nullable<System.DateTime> MANE_CONSTR_COMP_DATE { get; set; }
        public Nullable<System.DateTime> MANE_MAINTENANCE_START_DATE { get; set; }
        public Nullable<System.DateTime> MANE_MAINTENANCE_END_DATE { get; set; }
        public Nullable<decimal> MANE_YEAR1_AMOUNT { get; set; }
        public Nullable<decimal> MANE_YEAR2_AMOUNT { get; set; }
        public Nullable<decimal> MANE_YEAR3_AMOUNT { get; set; }
        public Nullable<decimal> MANE_YEAR4_AMOUNT { get; set; }
        public Nullable<decimal> MANE_YEAR5_AMOUNT { get; set; }
        public Nullable<decimal> MANE_YEAR6_AMOUNT { get; set; }
        public string MANE_CONTRACT_STATUS { get; set; }
        public string MANE_INCOMPLETE_REASON { get; set; }
        public Nullable<decimal> MANE_VALUE_WORK_DONE { get; set; }
        public string MANE_CONTRACT_FINALIZED { get; set; }
        public string MANE_LOCK_STATUS { get; set; }
        public string MANE_AGREEMENT_TYPE { get; set; }
        public decimal MANE_COMPLETED_LENGTH { get; set; }
        public int MANE_TRAFFIC_CATEGORY { get; set; }
        public int MANE_CARRIAGE_WAY { get; set; }
        public string MANE_IMS_ROAD_FINALIZE { get; set; }
        public string MANE_IMS_PACKAGE_FINALIZE { get; set; }
        public string IS_PUSHED_TO_EMARG { get; set; }
        public Nullable<System.DateTime> PUSHED_DATE_TO_EMARG { get; set; }
        public string IS_RECEIVED_BY_EMARG { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE_BY_EMARG { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
        public string IS_DEACTIVATED { get; set; }
        public string MAINTENANCE_PR_CONTRACT_CODE { get; set; }
    
        public virtual EMARG_ROAD_DETAILS EMARG_ROAD_DETAILS { get; set; }
        public virtual MASTER_CARRIAGE MASTER_CARRIAGE { get; set; }
        public virtual MASTER_CONTRACTOR MASTER_CONTRACTOR { get; set; }
        public virtual MASTER_TRAFFIC_TYPE MASTER_TRAFFIC_TYPE { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
