//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANE_IMS_TECH
    {
        public int IMS_PR_ROAD_CODE { get; set; }
        public int MANE_PR_CONTRACT_CODE { get; set; }
        public int IMS_SEGMENT_NO { get; set; }
        public decimal IMS_START_CHAINAGE { get; set; }
        public decimal IMS_END_CHAINAGE { get; set; }
        public int MAST_LAYER_CODE { get; set; }
        public int MAST_TECH_CODE { get; set; }
        public decimal IMS_TECH_COST { get; set; }
        public decimal IMS_LAYER_COST { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MANE_IMS_CONTRACT MANE_IMS_CONTRACT { get; set; }
        public virtual MASTER_EXECUTION_ITEM MASTER_EXECUTION_ITEM { get; set; }
        public virtual MASTER_TECHNOLOGY MASTER_TECHNOLOGY { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
