//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANE_IMS_PROGRESS_FILES
    {
        public int MANE_IMS_FILE_ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_DESC { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public System.DateTime FILE_UPLOAD_DATE { get; set; }
        public Nullable<decimal> START_CHAINAGE { get; set; }
        public Nullable<decimal> END_CHAINAGE { get; set; }
        public Nullable<decimal> SEGMENT_LENGTH { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
