//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANE_ER_PCI_INDEX
    {
        public int MAST_ER_ROAD_CODE { get; set; }
        public int MANE_SEGMENT_NO { get; set; }
        public int MANE_PCI_YEAR { get; set; }
        public Nullable<decimal> MANE_STR_CHAIN { get; set; }
        public Nullable<decimal> MANE_END_CHAIN { get; set; }
        public int MANE_PCIINDEX { get; set; }
        public Nullable<int> MANE_SURFACE_TYPE { get; set; }
        public Nullable<System.DateTime> MANE_PCI_DATE { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_EXISTING_ROADS MASTER_EXISTING_ROADS { get; set; }
        public virtual MASTER_SURFACE MASTER_SURFACE { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
