//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANE_CN_CONTRACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MANE_CN_CONTRACT()
        {
            this.IMS_UNLOCK_DETAILS = new HashSet<IMS_UNLOCK_DETAILS>();
        }
    
        public int PLAN_CN_ROAD_CODE { get; set; }
        public int MANE_CN_CONTRACT_CODE { get; set; }
        public int MAST_CON_ID { get; set; }
        public string MANE_AGREEMENT_NUMBER { get; set; }
        public System.DateTime MANE_AGREEMENT_DATE { get; set; }
        public Nullable<System.DateTime> MANE_CONSTR_COMP_DATE { get; set; }
        public System.DateTime MANE_MAINTENANCE_START_DATE { get; set; }
        public decimal MANE_YEAR1_AMOUNT { get; set; }
        public decimal MANE_YEAR2_AMOUNT { get; set; }
        public decimal MANE_YEAR3_AMOUNT { get; set; }
        public decimal MANE_YEAR4_AMOUNT { get; set; }
        public decimal MANE_YEAR5_AMOUNT { get; set; }
        public Nullable<System.DateTime> MANE_HANDOVER_DATE { get; set; }
        public string MANE_HANDOVER_TO { get; set; }
        public Nullable<int> MANE_RENEWAL_YEAR { get; set; }
        public string MANE_CONTRACT_STATUS { get; set; }
        public string MANE_INCOMPLETE_REASON { get; set; }
        public string MANE_CONTRACT_FINALIZED { get; set; }
        public string MANE_LOCK_STATUS { get; set; }
        public string MANE_FIRST_AGREEMENT { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_CONTRACTOR MASTER_CONTRACTOR { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual PLAN_ROAD PLAN_ROAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_UNLOCK_DETAILS> IMS_UNLOCK_DETAILS { get; set; }
    }
}
