//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_STREAMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_STREAMS()
        {
            this.ACC_AUTH_REQUEST_DETAILS = new HashSet<ACC_AUTH_REQUEST_DETAILS>();
            this.OFP_REQUEST_MASTER = new HashSet<OFP_REQUEST_MASTER>();
            this.IMS_SANCTIONED_PROJECTS = new HashSet<IMS_SANCTIONED_PROJECTS>();
        }
    
        public int MAST_STREAM_CODE { get; set; }
        public string MAST_STREAM_NAME { get; set; }
        public string MAST_STREAM_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_AUTH_REQUEST_DETAILS> ACC_AUTH_REQUEST_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFP_REQUEST_MASTER> OFP_REQUEST_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_SANCTIONED_PROJECTS> IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
