//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_BLOCK_LOCALE
    {
        public int MAST_BLOCK_CODE { get; set; }
        public int MAST_DISTRICT_CODE { get; set; }
        public string MAST_BLOCK_HINDI { get; set; }
        public string MAST_BLOCK_ACTIVE { get; set; }
    }
}
