//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_STATUS
    {
        public int STATUS_ID { get; set; }
        public string STATUS_TYPE { get; set; }
        public string STATUS_DESC { get; set; }
        public bool IS_VALID { get; set; }
    }
}
