//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_FACILITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_FACILITY()
        {
            this.FACILITY_IMAGE_DELETION = new HashSet<FACILITY_IMAGE_DELETION>();
        }
    
        public int MASTER_FACILITY_ID { get; set; }
        public int MASTER_FACILITY_CATEGORY_ID { get; set; }
        public int MASTER_FACILITY_SUB_CATEGORY_ID { get; set; }
        public string MASTER_FACILITY_DESC { get; set; }
        public string ADDRESS { get; set; }
        public int PINCODE { get; set; }
        public Nullable<System.DateTime> FILE_UPLOAD_DATE { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<System.DateTime> FINALIZED_DATE { get; set; }
        public string IS_FINALIZED { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACILITY_IMAGE_DELETION> FACILITY_IMAGE_DELETION { get; set; }
    }
}
