//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_MONTH
    {
        public short MAST_MONTH_CODE { get; set; }
        public string MAST_MONTH_SHORT_NAME { get; set; }
        public string MAST_MONTH_FULL_NAME { get; set; }
    }
}
