//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAST_HAB_DETAILS_CSV_PMGSY3
    {
        public int MAST_HAB_CSV_ID { get; set; }
        public int MAST_HAB_CSV_FILE_ID { get; set; }
        public int MAST_HAB_CSV_ER_CODE { get; set; }
        public int MAST_HAB_CSV_HAB_CODE { get; set; }
        public int MAST_HAB_CSV_BLOCK_CODE { get; set; }
        public int USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MAST_HAB_CSV_PMGSY3 MAST_HAB_CSV_PMGSY3 { get; set; }
        public virtual MASTER_BLOCK MASTER_BLOCK { get; set; }
        public virtual MASTER_EXISTING_ROADS MASTER_EXISTING_ROADS { get; set; }
        public virtual MASTER_HABITATIONS MASTER_HABITATIONS { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
