//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_HABITATIONS_DETAILS
    {
        public int MAST_HAB_CODE { get; set; }
        public int MAST_YEAR { get; set; }
        public int MAST_HAB_TOT_POP { get; set; }
        public int MAST_HAB_SCST_POP { get; set; }
        public string MAST_HAB_CONNECTED { get; set; }
        public string MAST_SCHEME { get; set; }
        public string MAST_PRIMARY_SCHOOL { get; set; }
        public string MAST_MIDDLE_SCHOOL { get; set; }
        public string MAST_HIGH_SCHOOL { get; set; }
        public string MAST_INTERMEDIATE_SCHOOL { get; set; }
        public string MAST_ITI { get; set; }
        public string MAST_DEGREE_COLLEGE { get; set; }
        public string MAST_HEALTH_SERVICE { get; set; }
        public string MAST_DISPENSARY { get; set; }
        public string MAST_MCW_CENTERS { get; set; }
        public string MAST_PHCS { get; set; }
        public string MAST_VETNARY_HOSPITAL { get; set; }
        public string MAST_TELEGRAPH_OFFICE { get; set; }
        public string MAST_TELEPHONE_CONNECTION { get; set; }
        public string MAST_MINING { get; set; }
        public string MAST_BUS_SERVICE { get; set; }
        public string MAST_RAILWAY_STATION { get; set; }
        public string MAST_ELECTRICTY { get; set; }
        public string MAST_ELECTRICITY_ADD { get; set; }
        public string MAST_PANCHAYAT_HQ { get; set; }
        public string MAST_BLOCK_HQ { get; set; }
        public string MAST_SUB_TEHSIL { get; set; }
        public string MAST_TOURIST_PLACE { get; set; }
        public string MAST_PETROL_PUMP { get; set; }
        public string MAST_PUMP_ADD { get; set; }
        public string MAST_MANDI { get; set; }
        public string MAST_WAREHOUSE { get; set; }
        public string MAST_RETAIL_SHOP { get; set; }
        public decimal MAST_HAB_WEIGHTAGE { get; set; }
        public string MAST_LOCK_STATUS { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_CENSUS_YEAR MASTER_CENSUS_YEAR { get; set; }
        public virtual MASTER_HABITATIONS MASTER_HABITATIONS { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
