//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_FACILITY_CATEGORY
    {
        public int MASTER_FACILITY_CATEGORT_ID { get; set; }
        public Nullable<int> MASTER_FACILITY_PARENT_ID { get; set; }
        public string MASTER_FACILITY_CATEGORY_NAME { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    }
}
