//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_FUND_SHARING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_FUND_SHARING()
        {
            this.MASTER_STATE_FUND_SHARING_MAPPING = new HashSet<MASTER_STATE_FUND_SHARING_MAPPING>();
        }
    
        public int MAST_SHARE_CODE { get; set; }
        public string MAST_SHARE_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_STATE_FUND_SHARING_MAPPING> MASTER_STATE_FUND_SHARING_MAPPING { get; set; }
    }
}
