//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_SLSC_GB_MEETING
    {
        public int SLSC_GB_CODE { get; set; }
        public int MAST_STATE_CODE { get; set; }
        public string SLSC_GB { get; set; }
        public System.DateTime MEETING_DATE { get; set; }
        public string FILE_TYPE { get; set; }
        public string FILE_NAME { get; set; }
        public System.DateTime FILE_UPLOAD_DATE { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_STATE MASTER_STATE { get; set; }
    }
}
