//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_EXISTING_ROADS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_EXISTING_ROADS()
        {
            this.IMS_LOCK_DETAILS = new HashSet<IMS_LOCK_DETAILS>();
            this.MANE_CN_PCI_INDEX_PMGSY3 = new HashSet<MANE_CN_PCI_INDEX_PMGSY3>();
            this.MANE_ER_PCI_INDEX = new HashSet<MANE_ER_PCI_INDEX>();
            this.MAST_HAB_DETAILS_CSV_PMGSY3 = new HashSet<MAST_HAB_DETAILS_CSV_PMGSY3>();
            this.MAST_TRACE_DRRP_SCORE_PMGSY3 = new HashSet<MAST_TRACE_DRRP_SCORE_PMGSY3>();
            this.MASTER_ER_CBR_VALUE = new HashSet<MASTER_ER_CBR_VALUE>();
            this.MASTER_ER_CBR_VALUE_PMGSY3 = new HashSet<MASTER_ER_CBR_VALUE_PMGSY3>();
            this.MASTER_ER_CDWORKS_ROAD = new HashSet<MASTER_ER_CDWORKS_ROAD>();
            this.MASTER_ER_CDWORKS_ROAD_PMGSY3 = new HashSet<MASTER_ER_CDWORKS_ROAD_PMGSY3>();
            this.MASTER_ER_HABITATION_ROAD = new HashSet<MASTER_ER_HABITATION_ROAD>();
            this.MASTER_ER_HABITATION_ROAD_PMGSY3 = new HashSet<MASTER_ER_HABITATION_ROAD_PMGSY3>();
            this.MASTER_ER_MAPROAD_PMGSY3 = new HashSet<MASTER_ER_MAPROAD_PMGSY3>();
            this.MASTER_ER_SURFACE_TYPES = new HashSet<MASTER_ER_SURFACE_TYPES>();
            this.MASTER_ER_SURFACE_TYPES_PMGSY3 = new HashSet<MASTER_ER_SURFACE_TYPES_PMGSY3>();
            this.MASTER_ER_TRAFFIC_INTENSITY = new HashSet<MASTER_ER_TRAFFIC_INTENSITY>();
            this.MASTER_ER_TRAFFIC_INTENSITY_PMGSY3 = new HashSet<MASTER_ER_TRAFFIC_INTENSITY_PMGSY3>();
            this.PLAN_ROAD_MRL_PMGSY3 = new HashSet<PLAN_ROAD_MRL_PMGSY3>();
            this.PLAN_ROAD_DRRP = new HashSet<PLAN_ROAD_DRRP>();
            this.PLAN_ROAD_LOG = new HashSet<PLAN_ROAD_LOG>();
            this.MASTER_DRRP_ROAD = new HashSet<MASTER_DRRP_ROAD>();
            this.PLAN_ROAD = new HashSet<PLAN_ROAD>();
            this.IMS_UNLOCK_DETAILS = new HashSet<IMS_UNLOCK_DETAILS>();
        }
    
        public int MAST_ER_ROAD_CODE { get; set; }
        public byte MAST_PMGSY_SCHEME { get; set; }
        public int MAST_STATE_CODE { get; set; }
        public int MAST_DISTRICT_CODE { get; set; }
        public int MAST_BLOCK_CODE { get; set; }
        public string MAST_ER_ROAD_NUMBER { get; set; }
        public int MAST_ROAD_CAT_CODE { get; set; }
        public string MAST_ER_ROAD_NAME { get; set; }
        public decimal MAST_ER_ROAD_STR_CHAIN { get; set; }
        public decimal MAST_ER_ROAD_END_CHAIN { get; set; }
        public Nullable<decimal> MAST_ER_ROAD_C_WIDTH { get; set; }
        public Nullable<decimal> MAST_ER_ROAD_F_WIDTH { get; set; }
        public Nullable<decimal> MAST_ER_ROAD_L_WIDTH { get; set; }
        public string MAST_ER_ROAD_TYPE { get; set; }
        public Nullable<int> MAST_SOIL_TYPE_CODE { get; set; }
        public Nullable<int> MAST_TERRAIN_TYPE_CODE { get; set; }
        public string MAST_CORE_NETWORK { get; set; }
        public string MAST_IS_BENEFITTED_HAB { get; set; }
        public Nullable<int> MAST_NOHABS_REASON { get; set; }
        public int MAST_ER_ROAD_OWNER { get; set; }
        public Nullable<int> MAST_CONS_YEAR { get; set; }
        public Nullable<int> MAST_RENEW_YEAR { get; set; }
        public Nullable<int> MAST_CD_WORKS_NUM { get; set; }
        public string MAST_LOCK_STATUS { get; set; }
        public Nullable<int> MAST_ER_ROAD_CODE_PMGSY1 { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_LOCK_DETAILS> IMS_LOCK_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANE_CN_PCI_INDEX_PMGSY3> MANE_CN_PCI_INDEX_PMGSY3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANE_ER_PCI_INDEX> MANE_ER_PCI_INDEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAST_HAB_DETAILS_CSV_PMGSY3> MAST_HAB_DETAILS_CSV_PMGSY3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAST_TRACE_DRRP_SCORE_PMGSY3> MAST_TRACE_DRRP_SCORE_PMGSY3 { get; set; }
        public virtual MASTER_AGENCY MASTER_AGENCY { get; set; }
        public virtual MASTER_BLOCK MASTER_BLOCK { get; set; }
        public virtual MASTER_DISTRICT MASTER_DISTRICT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_CBR_VALUE> MASTER_ER_CBR_VALUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_CBR_VALUE_PMGSY3> MASTER_ER_CBR_VALUE_PMGSY3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_CDWORKS_ROAD> MASTER_ER_CDWORKS_ROAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_CDWORKS_ROAD_PMGSY3> MASTER_ER_CDWORKS_ROAD_PMGSY3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_HABITATION_ROAD> MASTER_ER_HABITATION_ROAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_HABITATION_ROAD_PMGSY3> MASTER_ER_HABITATION_ROAD_PMGSY3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_MAPROAD_PMGSY3> MASTER_ER_MAPROAD_PMGSY3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_SURFACE_TYPES> MASTER_ER_SURFACE_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_SURFACE_TYPES_PMGSY3> MASTER_ER_SURFACE_TYPES_PMGSY3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_TRAFFIC_INTENSITY> MASTER_ER_TRAFFIC_INTENSITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_TRAFFIC_INTENSITY_PMGSY3> MASTER_ER_TRAFFIC_INTENSITY_PMGSY3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAN_ROAD_MRL_PMGSY3> PLAN_ROAD_MRL_PMGSY3 { get; set; }
        public virtual MASTER_REASON MASTER_REASON { get; set; }
        public virtual MASTER_ROAD_CATEGORY MASTER_ROAD_CATEGORY { get; set; }
        public virtual MASTER_SOIL_TYPE MASTER_SOIL_TYPE { get; set; }
        public virtual MASTER_STATE MASTER_STATE { get; set; }
        public virtual MASTER_TERRAIN_TYPE MASTER_TERRAIN_TYPE { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAN_ROAD_DRRP> PLAN_ROAD_DRRP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAN_ROAD_LOG> PLAN_ROAD_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_DRRP_ROAD> MASTER_DRRP_ROAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAN_ROAD> PLAN_ROAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_UNLOCK_DETAILS> IMS_UNLOCK_DETAILS { get; set; }
    }
}
