//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_BATCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_BATCH()
        {
            this.IMS_FREEZE_DETAILS = new HashSet<IMS_FREEZE_DETAILS>();
            this.IMS_GENERATED_INVOICE = new HashSet<IMS_GENERATED_INVOICE>();
            this.IMS_GENERATED_INVOICE_PTA = new HashSet<IMS_GENERATED_INVOICE_PTA>();
            this.IMS_SANCTIONED_PROJECTS_PDF = new HashSet<IMS_SANCTIONED_PROJECTS_PDF>();
            this.MRD_CLEARANCE_LETTERS = new HashSet<MRD_CLEARANCE_LETTERS>();
            this.MRD_DROPPED_LETTERS = new HashSet<MRD_DROPPED_LETTERS>();
            this.OFP_REQUEST_MASTER = new HashSet<OFP_REQUEST_MASTER>();
            this.IMS_UNLOCK_DETAILS = new HashSet<IMS_UNLOCK_DETAILS>();
        }
    
        public int MAST_BATCH_CODE { get; set; }
        public string MAST_BATCH_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_FREEZE_DETAILS> IMS_FREEZE_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_GENERATED_INVOICE> IMS_GENERATED_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_GENERATED_INVOICE_PTA> IMS_GENERATED_INVOICE_PTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_SANCTIONED_PROJECTS_PDF> IMS_SANCTIONED_PROJECTS_PDF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MRD_CLEARANCE_LETTERS> MRD_CLEARANCE_LETTERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MRD_DROPPED_LETTERS> MRD_DROPPED_LETTERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFP_REQUEST_MASTER> OFP_REQUEST_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_UNLOCK_DETAILS> IMS_UNLOCK_DETAILS { get; set; }
    }
}
