//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_QM_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_QM_ITEM()
        {
            this.QUALITY_QM_OBSERVATION_DETAIL = new HashSet<QUALITY_QM_OBSERVATION_DETAIL>();
            this.QUALITY_QM_TE_REMARK_DETAILS = new HashSet<QUALITY_QM_TE_REMARK_DETAILS>();
        }
    
        public int MAST_ITEM_NO { get; set; }
        public string MAST_QM_TYPE { get; set; }
        public int MAST_ITEM_CODE { get; set; }
        public int MAST_SUB_ITEM_CODE { get; set; }
        public string MAST_ITEM_NAME { get; set; }
        public string MAST_ITEM_ACTIVE { get; set; }
        public System.DateTime MAST_ITEM_ACTIVATION_DATE { get; set; }
        public Nullable<System.DateTime> MAST_ITEM_DEACTIVATION_DATE { get; set; }
        public string MAST_ITEM_STATUS { get; set; }
        public Nullable<int> MAST_GRADE_CODE { get; set; }
    
        public virtual MASTER_GRADE_TYPE MASTER_GRADE_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_OBSERVATION_DETAIL> QUALITY_QM_OBSERVATION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_TE_REMARK_DETAILS> QUALITY_QM_TE_REMARK_DETAILS { get; set; }
    }
}
