//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAST_HAB_CSV_PMGSY3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAST_HAB_CSV_PMGSY3()
        {
            this.MAST_HAB_DETAILS_CSV_PMGSY3 = new HashSet<MAST_HAB_DETAILS_CSV_PMGSY3>();
        }
    
        public int MAST_HAB_CSV_FILE_ID { get; set; }
        public int MAST_BLOCK_CODE { get; set; }
        public string MAST_HAB_CSV_FILE_NAME { get; set; }
        public Nullable<System.DateTime> MAST_HAB_CSV_FILE_UPLOAD_DATE { get; set; }
        public string MAST_HAB_CSV_FILE_FINALIZED { get; set; }
        public Nullable<System.DateTime> MAST_HAB_CSV_FILE_FINALIZED_DATE { get; set; }
        public Nullable<int> MAST_HAB_CSV_HAB_FINALIZED_BY { get; set; }
        public string MAST_MAP_UNMAP { get; set; }
        public Nullable<System.DateTime> MAST_MAP_UNMAP_DATE { get; set; }
        public int USERID { get; set; }
        public string IPADD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAST_HAB_DETAILS_CSV_PMGSY3> MAST_HAB_DETAILS_CSV_PMGSY3 { get; set; }
    }
}
