//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_TERRAIN_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_TERRAIN_TYPE()
        {
            this.MASTER_EXISTING_ROADS = new HashSet<MASTER_EXISTING_ROADS>();
            this.MASTER_EXISTING_ROADS_LOG = new HashSet<MASTER_EXISTING_ROADS_LOG>();
            this.MASTER_EXISTING_ROADS_Temp = new HashSet<MASTER_EXISTING_ROADS_Temp>();
            this.QUALITY_QM_EFORM = new HashSet<QUALITY_QM_EFORM>();
        }
    
        public int MAST_TERRAIN_TYPE_CODE { get; set; }
        public string MAST_TERRAIN_TYPE_NAME { get; set; }
        public Nullable<int> MAST_TERRAIN_SLOP_FROM { get; set; }
        public Nullable<int> MAST_TERRAIN_SLOP_TO { get; set; }
        public decimal MAST_TERRAIN_ROADWAY_WIDTH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_EXISTING_ROADS> MASTER_EXISTING_ROADS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_EXISTING_ROADS_LOG> MASTER_EXISTING_ROADS_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_EXISTING_ROADS_Temp> MASTER_EXISTING_ROADS_Temp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_EFORM> QUALITY_QM_EFORM { get; set; }
    }
}
