//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_PROFILE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_PROFILE()
        {
            this.ADMIN_NODAL_OFFICERS = new HashSet<ADMIN_NODAL_OFFICERS>();
        }
    
        public int MAST_PROFILE_CODE { get; set; }
        public string MAST_PROFILE_NAME { get; set; }
        public string MAST_PROFILE_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMIN_NODAL_OFFICERS> ADMIN_NODAL_OFFICERS { get; set; }
    }
}
