//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_TAXES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_TAXES()
        {
            this.IMS_GENERATED_INVOICE = new HashSet<IMS_GENERATED_INVOICE>();
            this.IMS_GENERATED_INVOICE_PTA = new HashSet<IMS_GENERATED_INVOICE_PTA>();
        }
    
        public int MAST_TDS_ID { get; set; }
        public decimal MAST_TDS { get; set; }
        public decimal MAST_TDS_SC { get; set; }
        public System.DateTime MAST_EFFECTIVE_DATE { get; set; }
        public Nullable<decimal> SERVICE_TAX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_GENERATED_INVOICE> IMS_GENERATED_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_GENERATED_INVOICE_PTA> IMS_GENERATED_INVOICE_PTA { get; set; }
    }
}
