//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_SURFACE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_SURFACE()
        {
            this.MANE_CN_PCI_INDEX = new HashSet<MANE_CN_PCI_INDEX>();
            this.MANE_CN_PCI_INDEX_PMGSY3 = new HashSet<MANE_CN_PCI_INDEX_PMGSY3>();
            this.MANE_ER_PCI_INDEX = new HashSet<MANE_ER_PCI_INDEX>();
            this.MANE_IMS_PCI_INDEX = new HashSet<MANE_IMS_PCI_INDEX>();
            this.MASTER_ER_SURFACE_TYPES = new HashSet<MASTER_ER_SURFACE_TYPES>();
            this.MASTER_ER_SURFACE_TYPES_PMGSY3 = new HashSet<MASTER_ER_SURFACE_TYPES_PMGSY3>();
            this.IMS_SANCTIONED_PROJECTS = new HashSet<IMS_SANCTIONED_PROJECTS>();
        }
    
        public int MAST_SURFACE_CODE { get; set; }
        public string MAST_SURFACE_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANE_CN_PCI_INDEX> MANE_CN_PCI_INDEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANE_CN_PCI_INDEX_PMGSY3> MANE_CN_PCI_INDEX_PMGSY3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANE_ER_PCI_INDEX> MANE_ER_PCI_INDEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANE_IMS_PCI_INDEX> MANE_IMS_PCI_INDEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_SURFACE_TYPES> MASTER_ER_SURFACE_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_SURFACE_TYPES_PMGSY3> MASTER_ER_SURFACE_TYPES_PMGSY3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_SANCTIONED_PROJECTS> IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
