//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAST_DISTRICT_ADJACEND
    {
        public int DISTRICT_CODE { get; set; }
        public int DISTRICT1 { get; set; }
        public Nullable<int> DISTRICT2 { get; set; }
        public Nullable<int> DISTRICT3 { get; set; }
        public Nullable<int> DISTRICT4 { get; set; }
        public Nullable<int> DISTRICT5 { get; set; }
        public Nullable<int> DISTRICT6 { get; set; }
    }
}
