//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_MODULE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_MODULE()
        {
            this.TKT_TG_MODULE_MAPPING = new HashSet<TKT_TG_MODULE_MAPPING>();
            this.TKT_TICKET_MASTER = new HashSet<TKT_TICKET_MASTER>();
        }
    
        public int MAST_MODULE_CODE { get; set; }
        public string MAST_MODULE_NAME { get; set; }
        public Nullable<int> MAST_MODULE_PARENT { get; set; }
        public Nullable<int> FORWARD_TO_ROLE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKT_TG_MODULE_MAPPING> TKT_TG_MODULE_MAPPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKT_TICKET_MASTER> TKT_TICKET_MASTER { get; set; }
    }
}
