//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_CDWORKS_TYPE_CONSTRUCTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_CDWORKS_TYPE_CONSTRUCTION()
        {
            this.MASTER_ER_CDWORKS_ROAD_PMGSY3 = new HashSet<MASTER_ER_CDWORKS_ROAD_PMGSY3>();
            this.MASTER_ER_CDWORKS_ROAD = new HashSet<MASTER_ER_CDWORKS_ROAD>();
        }
    
        public int MAST_CDWORKS_CODE { get; set; }
        public string MAST_CDWORKS_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_CDWORKS_ROAD_PMGSY3> MASTER_ER_CDWORKS_ROAD_PMGSY3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_ER_CDWORKS_ROAD> MASTER_ER_CDWORKS_ROAD { get; set; }
    }
}
