//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_GRADE_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_GRADE_TYPE()
        {
            this.MASTER_QM_ITEM = new HashSet<MASTER_QM_ITEM>();
            this.QUALITY_PIU_OBSERVATION_MASTER = new HashSet<QUALITY_PIU_OBSERVATION_MASTER>();
            this.QUALITY_QM_OBSERVATION_DETAIL = new HashSet<QUALITY_QM_OBSERVATION_DETAIL>();
            this.QUALITY_QM_OBSERVATION_DETAIL1 = new HashSet<QUALITY_QM_OBSERVATION_DETAIL>();
            this.QUALITY_QM_OBSERVATION_MASTER = new HashSet<QUALITY_QM_OBSERVATION_MASTER>();
        }
    
        public int MAST_GRADE_CODE { get; set; }
        public string MAST_GRADE_NAME { get; set; }
        public string MAST_GRADE_SHORT_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_QM_ITEM> MASTER_QM_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_PIU_OBSERVATION_MASTER> QUALITY_PIU_OBSERVATION_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_OBSERVATION_DETAIL> QUALITY_QM_OBSERVATION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_OBSERVATION_DETAIL> QUALITY_QM_OBSERVATION_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_OBSERVATION_MASTER> QUALITY_QM_OBSERVATION_MASTER { get; set; }
    }
}
