//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_ER_CDWORKS_ROAD
    {
        public int MAST_ER_ROAD_CODE { get; set; }
        public int MAST_CD_NUMBER { get; set; }
        public int MAST_CDWORKS_CODE { get; set; }
        public Nullable<decimal> MAST_CD_LENGTH { get; set; }
        public Nullable<decimal> MAST_CD_DISCHARGE { get; set; }
        public Nullable<decimal> MAST_CD_CHAINAGE { get; set; }
        public Nullable<int> MAST_CONSTRUCT_YEAR { get; set; }
        public Nullable<int> MAST_REHAB_YEAR { get; set; }
        public Nullable<decimal> MAST_ER_SPAN { get; set; }
        public Nullable<decimal> MAST_CARRIAGE_WAY { get; set; }
        public string MAST_IS_FOOTPATH { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_CDWORKS_TYPE_CONSTRUCTION MASTER_CDWORKS_TYPE_CONSTRUCTION { get; set; }
        public virtual MASTER_EXISTING_ROADS MASTER_EXISTING_ROADS { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
