//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPR_FILE_UPLOADED
    {
        public int MPR_FILE_ID { get; set; }
        public int MAST_STATE_CODE { get; set; }
        public string MPR_FILE_NAME { get; set; }
        public string MPR_FILE_DESC { get; set; }
        public Nullable<System.DateTime> MPR_FILE_UPLOAD_DATE { get; set; }
        public Nullable<int> MPR_FILE_TYPE { get; set; }
    
        public virtual MASTER_STATE MASTER_STATE { get; set; }
    }
}
