//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRD_PUBLICATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MRD_PUBLICATIONS()
        {
            this.MRD_PUBLICATION_FILES = new HashSet<MRD_PUBLICATION_FILES>();
        }
    
        public int PUBLICATION_CODE { get; set; }
        public int PUBLICATION_CAT_CODE { get; set; }
        public string PUBLICATION_TITLE { get; set; }
        public string PUBLICATION_DESCRIPTION { get; set; }
        public string PUBLICATION_AUTHOR { get; set; }
        public System.DateTime PUBLICATION_DATE { get; set; }
        public string PUBLICATION_VOLUME { get; set; }
        public string PUBLICATION_NAME { get; set; }
        public string PUBLICATION_PAGINATION { get; set; }
        public string PUBLICATION_PERIOD { get; set; }
        public string PUBLICATION_STATUS { get; set; }
        public string PUBLICATION_IS_FINALIZED { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_PUBLICATION_CATEGORY MASTER_PUBLICATION_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MRD_PUBLICATION_FILES> MRD_PUBLICATION_FILES { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
