//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NQM_TRAVEL_CLAIM_DETAILS
    {
        public int TRAVEL_CLAIM_ID { get; set; }
        public int TOUR_CLAIM_ID { get; set; }
        public System.DateTime START_DATE_OF_TRAVEL { get; set; }
        public int START_HOURS { get; set; }
        public int START_MINUTES { get; set; }
        public System.DateTime END_DATE_OF_TRAVEL { get; set; }
        public int END_HOURS { get; set; }
        public int END_MINUTES { get; set; }
        public string DEPARTURE_FROM { get; set; }
        public string ARRIVAL_AT { get; set; }
        public int MODE_OF_TRAVEL { get; set; }
        public string TRAVEL_CLASS { get; set; }
        public decimal AMOUNT_CLAIMED { get; set; }
        public System.DateTime DATE_OF_CLAIM { get; set; }
        public Nullable<decimal> AMOUNT_PASSED_CQC { get; set; }
        public string REMARK_CQC { get; set; }
        public Nullable<System.DateTime> DATE_OF_MODIFICATION_CQC { get; set; }
        public Nullable<decimal> AMOUNT_PASSED_FIN1 { get; set; }
        public string REMARK_FIN1 { get; set; }
        public Nullable<System.DateTime> DATE_OF_MODIFICATION_FIN1 { get; set; }
        public Nullable<decimal> AMOUNT_PASSED_FIN2 { get; set; }
        public string REMARK_FIN2 { get; set; }
        public Nullable<System.DateTime> DATE_OF_MODIFICATION_FIN2 { get; set; }
        public string UPLOADED_TICKET_NAME { get; set; }
        public string UPLOADED_TICKET_PATH { get; set; }
        public string BOARDING_PASS_NAME { get; set; }
        public string BOARDING_PASS_PATH { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual NQM_TOUR_CLAIM_MODE_OF_TRAVEL NQM_TOUR_CLAIM_MODE_OF_TRAVEL { get; set; }
        public virtual NQM_TOUR_CLAIM_MASTER NQM_TOUR_CLAIM_MASTER { get; set; }
    }
}
