//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NQM_TOUR_PERMISSION_DETAILS
    {
        public int ID { get; set; }
        public int TOUR_CLAIM_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime DATE_OF_CLAIM { get; set; }
        public string REMARK { get; set; }
        public string PERMISSION_DOCUMENT_NAME { get; set; }
        public string PERMISSION_DOCUMENT_PATH { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual NQM_TOUR_CLAIM_MASTER NQM_TOUR_CLAIM_MASTER { get; set; }
    }
}
