//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMMAS_GEPNIC_UNIQUE_REF_AVAILABILITY
    {
        public int ID { get; set; }
        public long REF_NO { get; set; }
        public string IS_AVAILABLE { get; set; }
        public Nullable<System.DateTime> GENERATED_DATE { get; set; }
    }
}
