//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMMAS_GEPNIC_AOC_DETAILS
    {
        public int AOC_ID { get; set; }
        public int TENDER_ID { get; set; }
        public int GEPNIC_BID_ID { get; set; }
        public System.DateTime CONTRACT_DATE { get; set; }
        public string CONTRACT_NUMBER { get; set; }
        public decimal AWARDED_VALUE { get; set; }
        public System.DateTime GENERATED_DATE { get; set; }
        public string BIDDER_NAME { get; set; }
    
        public virtual OMMAS_GEPNIC_TENDER_WORKITEM_DETAILS OMMAS_GEPNIC_TENDER_WORKITEM_DETAILS { get; set; }
    }
}
