//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMMAS_LDG_DISTRICT_MAPPING
    {
        public int MAST_DISTRICT_CODE { get; set; }
        public int MAST_DISTRICT_LDG_CODE { get; set; }
    
        public virtual MASTER_DISTRICT MASTER_DISTRICT { get; set; }
    }
}
