//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMMAS_GEPNIC_TENDERINFO_BY_PDATE
    {
        public int TINFOID { get; set; }
        public string T_ID { get; set; }
        public string T_REF_NO { get; set; }
        public string T_TITLE { get; set; }
        public string T_PRE_QUAL { get; set; }
        public string T_LOCATION { get; set; }
        public string T_PINCODE { get; set; }
        public string T_CURRENCY { get; set; }
        public Nullable<decimal> T_FEE { get; set; }
        public Nullable<decimal> T_VALUE { get; set; }
        public Nullable<decimal> T_EMD { get; set; }
        public Nullable<System.DateTime> T_PUB_DATE { get; set; }
        public Nullable<System.DateTime> T_PREBID_DATE { get; set; }
        public Nullable<System.DateTime> T_DOC_START_DATE { get; set; }
        public Nullable<System.DateTime> T_DOC_END_DATE { get; set; }
        public Nullable<System.DateTime> T_BIDSUB_START_DATE { get; set; }
        public Nullable<System.DateTime> T_BIDSUB_END_DATE { get; set; }
        public Nullable<System.DateTime> T_BID_OPEN_DATE { get; set; }
        public string T_INVITING_OFFICER { get; set; }
        public string T_INVITING_OFF_ADDRESS { get; set; }
        public string T_PROD_CAT { get; set; }
        public string T_PROD_SUB_CAT { get; set; }
        public string T_FORM_CONTRACT { get; set; }
        public string T_RETURN_URL { get; set; }
        public string T_REMARKS { get; set; }
        public string T_ORGNAME { get; set; }
        public System.DateTime GENERATED_DATE { get; set; }
        public string T_DESC { get; set; }
        public string T_TENDER_TYPE { get; set; }
        public string T_TENDER_CATEGORY { get; set; }
    }
}
