//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMMAS_GEPNIC_TENDER_CORRIGENDUM_DETAILS
    {
        public int CORR_ID { get; set; }
        public int TENDER_ID { get; set; }
        public string CORR_TYPE { get; set; }
        public System.DateTime CORR_PUB_DATE { get; set; }
        public string CORR_PUB_BY { get; set; }
        public System.DateTime GENERATED_DATE { get; set; }
        public string CORR_NAME { get; set; }
    
        public virtual OMMAS_GEPNIC_TENDER_WORKITEM_DETAILS OMMAS_GEPNIC_TENDER_WORKITEM_DETAILS { get; set; }
    }
}
