//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFMS_OMMAS_PAYMENT_MAPPING
    {
        public long POPM_ID { get; set; }
        public long BILL_ID { get; set; }
        public string BATCH_ID { get; set; }
        public System.DateTime BILL_DATE { get; set; }
        public string PAYMENT_REQ_FILENAME { get; set; }
        public System.DateTime PAYMENT_REQ_FILE_GEN_DATE { get; set; }
        public string ACK_RECEVIED_FILENAME { get; set; }
        public string ACK_BILL_STATUS { get; set; }
        public string REJECTION_CODE { get; set; }
        public string REJECTION_NARRATION { get; set; }
        public string BANK_ACK_RECEVIED_FILENAME { get; set; }
        public string BANK_ACK_BILL_STATUS { get; set; }
        public string BANK_ACK_REJECTION_CODE { get; set; }
        public string BANK_ACK_REJECTION_NARRATION { get; set; }
        public Nullable<System.DateTime> ACK_RECEIVED_DATE { get; set; }
        public Nullable<System.DateTime> BANK_ACK_RECEIVED_DATE { get; set; }
        public string BANK_ACK_INSTRID { get; set; }
        public string BANK_ACK_CRETXNID { get; set; }
        public Nullable<System.DateTime> BANK_ACK_TXNDATE { get; set; }
        public Nullable<bool> PLACED_ON_SFTP { get; set; }
        public Nullable<System.DateTime> DATE_OF_PLACING { get; set; }
        public Nullable<bool> COPIED_TO_BACKUP { get; set; }
        public Nullable<bool> DELETED_FROM_SOURCE { get; set; }
        public Nullable<System.DateTime> DATE_OF_DELETION { get; set; }
        public string CHKSUM { get; set; }
    
        public virtual ACC_BILL_MASTER ACC_BILL_MASTER { get; set; }
    }
}
