//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFMS_OMMAS_CONTRACTOR_MAPPING
    {
        public int POCM_ID { get; set; }
        public int MAST_CON_ID { get; set; }
        public int MAST_ACCOUNT_ID { get; set; }
        public int MAST_LGD_STATE_CODE { get; set; }
        public Nullable<int> MAST_LGD_DISTRICT_CODE { get; set; }
        public string MAST_CON_COMPANY_NAME { get; set; }
        public string MAST_BANK_NAME { get; set; }
        public string MAST_IFSC_CODE { get; set; }
        public string MAST_ACCOUNT_NUMBER { get; set; }
        public string BATCH_ID { get; set; }
        public string STATUS { get; set; }
        public string REJECTION_CODE { get; set; }
        public string PFMS_CON_ID { get; set; }
        public string ACK_FILE_NAME { get; set; }
        public Nullable<System.DateTime> ACK_RECV_DATE { get; set; }
        public Nullable<int> MAST_AGENCY_CODE { get; set; }
        public string PFMS_CON_NAME { get; set; }
        public string PFMS_IFSC_CODE { get; set; }
        public string PFMS_STATUS { get; set; }
    
        public virtual MASTER_CONTRACTOR MASTER_CONTRACTOR { get; set; }
    }
}
