//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_ROAD_HABITATION_PMGSY3
    {
        public int PLAN_CN_ROAD_HAB_ID { get; set; }
        public int PLAN_CN_ROAD_CODE { get; set; }
        public int MAST_HAB_CODE { get; set; }
        public string MAST_HAB_CODE_DIRECT { get; set; }
        public string MAST_HAB_CODE_VERIFIED { get; set; }
        public string PLAN_CN_HAB_FINALIZED { get; set; }
        public Nullable<System.DateTime> PLAN_CN_HAB_FIN_DATE { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_HABITATIONS MASTER_HABITATIONS { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual PLAN_ROAD PLAN_ROAD { get; set; }
    }
}
