//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_ROAD_LOG
    {
        public int PLAN_CN_ROAD_CODE { get; set; }
        public byte MAST_PMGSY_SCHEME { get; set; }
        public int MAST_ER_ROAD_CODE { get; set; }
        public string PLAN_CN_ROAD_NUMBER { get; set; }
        public int MAST_STATE_CODE { get; set; }
        public int MAST_DISTRICT_CODE { get; set; }
        public int MAST_BLOCK_CODE { get; set; }
        public string PLAN_RD_NAME { get; set; }
        public string PLAN_RD_ROUTE { get; set; }
        public Nullable<decimal> PLAN_RD_FROM_CHAINAGE { get; set; }
        public Nullable<decimal> PLAN_RD_TO_CHAINAGE { get; set; }
        public string PLAN_RD_LENG { get; set; }
        public Nullable<decimal> PLAN_RD_LENGTH { get; set; }
        public Nullable<decimal> PLAN_RD_TOTAL_LEN { get; set; }
        public string PLAN_RD_FROM_TYPE { get; set; }
        public string PLAN_RD_TO_TYPE { get; set; }
        public Nullable<int> PLAN_RD_FROM_HAB { get; set; }
        public Nullable<int> PLAN_RD_TO_HAB { get; set; }
        public Nullable<int> PLAN_RD_BLOCK_FROM_CODE { get; set; }
        public Nullable<int> PLAN_RD_BLOCK_TO_CODE { get; set; }
        public Nullable<int> PLAN_RD_NUM_FROM { get; set; }
        public Nullable<int> PLAN_RD_NUM_TO { get; set; }
        public string PLAN_RD_FROM { get; set; }
        public string PLAN_RD_TO { get; set; }
        public string PLAN_LOCK_STATUS { get; set; }
        public int NEW_MAST_DISTRICT_CODE { get; set; }
        public int NEW_MAST_BLOCK_CODE { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_BLOCK MASTER_BLOCK { get; set; }
        public virtual MASTER_BLOCK MASTER_BLOCK1 { get; set; }
        public virtual MASTER_BLOCK MASTER_BLOCK2 { get; set; }
        public virtual MASTER_DISTRICT MASTER_DISTRICT { get; set; }
        public virtual MASTER_EXISTING_ROADS MASTER_EXISTING_ROADS { get; set; }
        public virtual MASTER_HABITATIONS MASTER_HABITATIONS { get; set; }
        public virtual MASTER_HABITATIONS MASTER_HABITATIONS1 { get; set; }
        public virtual MASTER_STATE MASTER_STATE { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
