//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMIS_PROGRESS_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PMIS_PROGRESS_MASTER()
        {
            this.PMIS_PROGRESS_DETAILS = new HashSet<PMIS_PROGRESS_DETAILS>();
        }
    
        public int PROGRESS_MASTER_ID { get; set; }
        public int PLAN_ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public decimal COMPLETION_LENGTH { get; set; }
        public string PROJECT_STATUS_ { get; set; }
        public string IS_LATEST { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int BASELINE_NO { get; set; }
        public int USERID { get; set; }
        public string IPADD { get; set; }
        public string REMARKS { get; set; }
    
        public virtual PMIS_PLAN_MASTER PMIS_PLAN_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMIS_PROGRESS_DETAILS> PMIS_PROGRESS_DETAILS { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
