//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMIS_CHAINAGEWISE_COMPLETION_DETAILS
    {
        public int COMPL_ID { get; set; }
        public decimal CHAINAGE_FROM { get; set; }
        public decimal CHAINAGE_TO { get; set; }
        public string ACT_EARTHWORK { get; set; }
        public string ACT_SUBGRADE { get; set; }
        public string ACT_GRSUBBASE { get; set; }
        public string ACT_WBM_GRADING2 { get; set; }
        public string ACT_WBM_GRADING3 { get; set; }
        public string ACT_WETMIX_MACADAM { get; set; }
        public string ACT_BIT_MACADAM { get; set; }
        public string ACT_SURFACE_COURSE { get; set; }
        public Nullable<int> PLAN_ID { get; set; }
        public int BASELINE_NO { get; set; }
        public string IS_VALID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int COMPL_MONTH { get; set; }
        public int COMPL_YEAR { get; set; }
        public int USERID { get; set; }
        public string IPADD { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
    
        public virtual PMIS_PLAN_MASTER PMIS_PLAN_MASTER { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
