//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMIS_FDR_STABILIZE_CHAINAGE_WISE_DETAIL
    {
        public int ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public decimal CHAINAGE_FROM { get; set; }
        public decimal CHAINAGE_TO { get; set; }
        public Nullable<decimal> F_START_CHAINAGE { get; set; }
        public Nullable<decimal> F_END_CHAINAGE { get; set; }
        public Nullable<System.DateTime> F_CHAINAGE_DATE { get; set; }
        public Nullable<decimal> S_START_CHAINAGE { get; set; }
        public Nullable<decimal> S_END_CHAINAGE { get; set; }
        public Nullable<System.DateTime> S_CHAINAGE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public string IS_LATEST { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
