//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QM_PROFICIENCY_TEST_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QM_PROFICIENCY_TEST_MASTER()
        {
            this.QM_PROFICIENCY_TEST_SCORE = new HashSet<QM_PROFICIENCY_TEST_SCORE>();
        }
    
        public int EXAM_ID { get; set; }
        public System.DateTime DATE_OF_EXAM { get; set; }
        public string INSTITUTE_NAME { get; set; }
        public string MONITOR_TYPE { get; set; }
        public Nullable<int> STATE_CODE { get; set; }
        public int USERID { get; set; }
        public string IPADD { get; set; }
        public System.DateTime DATA_ENTRY_DATE { get; set; }
        public string IS_FINALIZED { get; set; }
        public Nullable<System.DateTime> DATE_OF_FINALIZATION { get; set; }
        public string UPLOADED_FILE_NAME { get; set; }
        public string UPLOADED_FILE_PATH { get; set; }
    
        public virtual UM_User_Master UM_User_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QM_PROFICIENCY_TEST_SCORE> QM_PROFICIENCY_TEST_SCORE { get; set; }
    }
}
