//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QM_QCR_DETAILS
    {
        public int QCR_ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_PATH { get; set; }
        public System.DateTime FILE_UPLOADED_DATE { get; set; }
        public string UPLOAD_REMARK { get; set; }
        public string IS_LATEST { get; set; }
        public int USERID { get; set; }
        public string IPADD { get; set; }
        public string IS_FINALIZE { get; set; }
        public string GRADE_SE { get; set; }
        public string GRADE_SQC { get; set; }
    
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
