//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUALITY_INSPECTION_REPORT_FILE
    {
        public int FILE_ID { get; set; }
        public int QM_OBSERVATION_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_DESCRIPTION { get; set; }
        public string FILE_TYPE { get; set; }
        public System.DateTime FILE_UPLOAD_DATE { get; set; }
        public int USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual QUALITY_QM_OBSERVATION_MASTER QUALITY_QM_OBSERVATION_MASTER { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
