//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUALITY_QM_EFORM
    {
        public int QUALITY_EFORM_ID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public int TECHNICAL_SANTIONED_CODT { get; set; }
        public int FLEXIBLE_PAVEMENT_LENGTH { get; set; }
        public int CC_PAVEMENT_LENGTH { get; set; }
        public int MAST_TERRAIN_TYPE_CODE { get; set; }
        public string QC_REGISTER_PARTA { get; set; }
        public string QC_REGISTER_PARTB { get; set; }
        public int USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_TERRAIN_TYPE MASTER_TERRAIN_TYPE { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
