//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUALITY_QM_LAB_DETAILS
    {
        public int QM_LAB_FILE_ID { get; set; }
        public int QM_LAB_ID { get; set; }
        public string QM_LAB_FILE_NAME { get; set; }
        public string QM_LAB_FILE_DESC { get; set; }
        public System.DateTime QM_LAB_FILE_UPLOAD_DATE { get; set; }
        public decimal QM_LAB_FILE_LATITUDE { get; set; }
        public decimal QM_LAB_FILE_LONGITUDE { get; set; }
        public string QM_LAB_IMAGE_FIRST { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
        public int REGISTERD_USER { get; set; }
    
        public virtual MABProgressUserDetails MABProgressUserDetails { get; set; }
        public virtual QUALITY_QM_LAB_MASTER QUALITY_QM_LAB_MASTER { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
