//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUALITY_QM_JOINT_INSPECTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUALITY_QM_JOINT_INSPECTION()
        {
            this.QUALITY_QM_JOINT_INSPECTION_FILE = new HashSet<QUALITY_QM_JOINT_INSPECTION_FILE>();
            this.QUALITY_QM_JOINT_INSPECTION_ATR = new HashSet<QUALITY_QM_JOINT_INSPECTION_ATR>();
        }
    
        public int QM_JNT_INSP_CODE { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public System.DateTime IMS_JNT_INSP_DATE { get; set; }
        public string QM_JNT_REP_MP_NAME { get; set; }
        public string QM_JNT_REP_MLA_NAME { get; set; }
        public string QM_JNT_REP_GPR_NAME { get; set; }
        public string QM_JNT_REP_OR_NAME { get; set; }
        public string QM_JNT_AGO_SE_NAME { get; set; }
        public string QM_JNT_AGO_PIU_NAME { get; set; }
        public string QM_JNT_AGO_AE_NAME { get; set; }
        public string QM_JNT_AGO_DO_NAME { get; set; }
        public string QM_JNT_CON_REP_AVL { get; set; }
        public string QM_JNT_CON_REP_NAME { get; set; }
        public string QM_JNT_SRV_CON_TRG_HAB { get; set; }
        public string QM_JNT_WORK_PRG_SAT { get; set; }
        public string QM_JNT_CD_WRK_SUFF { get; set; }
        public string QM_JNT_REASON { get; set; }
        public string QM_JNT_INSP_OVERALL { get; set; }
        public string QM_JNT_INSP_REMARKS { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_JOINT_INSPECTION_FILE> QUALITY_QM_JOINT_INSPECTION_FILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_JOINT_INSPECTION_ATR> QUALITY_QM_JOINT_INSPECTION_ATR { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
