//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUALITY_QM_NOTIFICATIONS
    {
        public int USER_ID { get; set; }
        public int MESSAGE_ID { get; set; }
        public string MESSAGE_TEXT { get; set; }
        public string MESSAGE_TYPE { get; set; }
        public bool IS_DOWNLOAD { get; set; }
        public System.DateTime TIME_STAMP { get; set; }
        public Nullable<int> BROADCAST_ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    }
}
