//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUALITY_QM_TEAM
    {
        public int QM_TEAM_ID { get; set; }
        public string QM_TEAM_CODE { get; set; }
        public int ADMIN_SCHEDULE_CODE { get; set; }
        public string IS_TEAM_LEADER { get; set; }
        public string TEAM_ACTIVE_STATUS { get; set; }
    
        public virtual QUALITY_QM_SCHEDULE QUALITY_QM_SCHEDULE { get; set; }
    }
}
