//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUALITY_QM_COMPLAIN_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUALITY_QM_COMPLAIN_DETAIL()
        {
            this.QUALITY_QM_COMPLAIN_DETAIL_FILE = new HashSet<QUALITY_QM_COMPLAIN_DETAIL_FILE>();
        }
    
        public int DetailId { get; set; }
        public int CompIainId { get; set; }
        public int StageId { get; set; }
        public string Remarks { get; set; }
        public string FileName { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Action { get; set; }
        public int StageLevel { get; set; }
    
        public virtual QUALITY_QM_COMPLAIN QUALITY_QM_COMPLAIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALITY_QM_COMPLAIN_DETAIL_FILE> QUALITY_QM_COMPLAIN_DETAIL_FILE { get; set; }
        public virtual QUALITY_QM_COMPLAIN_ITEM QUALITY_QM_COMPLAIN_ITEM { get; set; }
    }
}
