//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCTRC_CONTACT_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RCTRC_CONTACT_DETAILS()
        {
            this.RCTRC_CONTACT_KEY_AREA = new HashSet<RCTRC_CONTACT_KEY_AREA>();
            this.RCTRC_CONTACT_PERFORMANCE = new HashSet<RCTRC_CONTACT_PERFORMANCE>();
            this.RCTRC_CONTACT_SUGGESTION = new HashSet<RCTRC_CONTACT_SUGGESTION>();
            this.RCTRC_CONTACT_TRAININGS = new HashSet<RCTRC_CONTACT_TRAININGS>();
            this.RCTRC_CONTACT_TRG_REQ = new HashSet<RCTRC_CONTACT_TRG_REQ>();
            this.RCTRC_CONTACT_WORK_AREA = new HashSet<RCTRC_CONTACT_WORK_AREA>();
        }
    
        public int RCTRC_Contact_Id { get; set; }
        public string RCTRC_Contact_Name { get; set; }
        public string RCTRC_Contact_eMail { get; set; }
        public Nullable<int> STATE_CODE { get; set; }
        public Nullable<int> DISTRICT_CODE { get; set; }
        public string STATE { get; set; }
        public string DISTRICT { get; set; }
        public string RCTRC_Contact_Password_ENC { get; set; }
        public string RCTRC_Contact_Mobile { get; set; }
        public string RCTRC_Contact_Phone { get; set; }
        public string RCTRC_Contact_Address { get; set; }
        public string RCTRC_GENDER { get; set; }
        public System.DateTime RCTRC_Contact_DOB { get; set; }
        public Nullable<int> RCTRC_Contact_Designation { get; set; }
        public string RCTRC_Contact_Designation_Text { get; set; }
        public System.DateTime RCTRC_Contact_DOJ { get; set; }
        public Nullable<int> RCTRC_Contact_Deputatoin { get; set; }
        public int RCTRC_Contact_Graduation { get; set; }
        public string RCTRC_Contact_Graduation_Text { get; set; }
        public System.DateTime RCTRC_Contact_Grad_Comp { get; set; }
        public Nullable<int> RCTRC_Contact_PG { get; set; }
        public string RCTRC_Contact_PG_Text { get; set; }
        public Nullable<System.DateTime> RCTRC_Contact_PG_Comp { get; set; }
        public string RCTRC_Contact_CompAtHome { get; set; }
        public string RCTRC_Contact_CompAtOffice { get; set; }
        public string RCTRC_REMARKS { get; set; }
        public string RCTRC_Contact_Password { get; set; }
        public Nullable<int> USERID { get; set; }
    
        public virtual MASTER_DISTRICT MASTER_DISTRICT { get; set; }
        public virtual MASTER_STATE MASTER_STATE { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCTRC_CONTACT_KEY_AREA> RCTRC_CONTACT_KEY_AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCTRC_CONTACT_PERFORMANCE> RCTRC_CONTACT_PERFORMANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCTRC_CONTACT_SUGGESTION> RCTRC_CONTACT_SUGGESTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCTRC_CONTACT_TRAININGS> RCTRC_CONTACT_TRAININGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCTRC_CONTACT_TRG_REQ> RCTRC_CONTACT_TRG_REQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCTRC_CONTACT_WORK_AREA> RCTRC_CONTACT_WORK_AREA { get; set; }
    }
}
