//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCTRC_UM_User_Profile
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string LandlineNumber { get; set; }
        public string Mobile_IMEI_Number { get; set; }
        public short PasswordQuestionID { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual RCTRC_UM_Security_Question_Master RCTRC_UM_Security_Question_Master { get; set; }
        public virtual RCTRC_UM_User_Master RCTRC_UM_User_Master { get; set; }
    }
}
