//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCTRC_CONTACT_TRG_REQ
    {
        public int RCTRC_CONTACT_TRG_REQ_ID { get; set; }
        public int RCTRC_Contact_Id { get; set; }
        public int RCTRC_TRAINING_ID { get; set; }
        public string RCTRC_TRG_RPD { get; set; }
        public string RCTRC_TRG_EYC { get; set; }
        public string RCTRC_TRG_FAI { get; set; }
        public System.DateTime RCTRC_TRG_ENTRY_DATE { get; set; }
        public Nullable<int> USERID { get; set; }
    
        public virtual RCTRC_CONTACT_DETAILS RCTRC_CONTACT_DETAILS { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
