//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCTRC_UM_Module_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RCTRC_UM_Module_Master()
        {
            this.RCTRC_UM_Action_Master = new HashSet<RCTRC_UM_Action_Master>();
            this.RCTRC_UM_Action_Master1 = new HashSet<RCTRC_UM_Action_Master>();
        }
    
        public short ModuleID { get; set; }
        public string ModuleName { get; set; }
        public bool IsSubModule { get; set; }
        public short ParentID { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCTRC_UM_Action_Master> RCTRC_UM_Action_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCTRC_UM_Action_Master> RCTRC_UM_Action_Master1 { get; set; }
    }
}
