//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCTRC_UM_Level_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RCTRC_UM_Level_Master()
        {
            this.RCTRC_UM_Level_Combination = new HashSet<RCTRC_UM_Level_Combination>();
            this.RCTRC_UM_Role_Level_Mapping = new HashSet<RCTRC_UM_Role_Level_Mapping>();
            this.RCTRC_UM_User_Log = new HashSet<RCTRC_UM_User_Log>();
            this.RCTRC_UM_User_Master = new HashSet<RCTRC_UM_User_Master>();
        }
    
        public short LevelID { get; set; }
        public string LevelName { get; set; }
        public short ParentID { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCTRC_UM_Level_Combination> RCTRC_UM_Level_Combination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCTRC_UM_Role_Level_Mapping> RCTRC_UM_Role_Level_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCTRC_UM_User_Log> RCTRC_UM_User_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCTRC_UM_User_Master> RCTRC_UM_User_Master { get; set; }
    }
}
