//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCTRC_ADMIN_QUALITY_MONITORS
    {
        public int ADMIN_QM_CODE { get; set; }
        public string ADMIN_QM_TYPE { get; set; }
        public Nullable<int> MAST_STATE_CODE { get; set; }
        public string ADMIN_QM_FNAME { get; set; }
        public string ADMIN_QM_MNAME { get; set; }
        public string ADMIN_QM_LNAME { get; set; }
        public int ADMIN_QM_DESG { get; set; }
        public string ADMIN_QM_ADDRESS1 { get; set; }
        public string ADMIN_QM_ADDRESS2 { get; set; }
        public Nullable<int> MAST_DISTRICT_CODE { get; set; }
        public Nullable<int> MAST_STATE_CODE_ADDR { get; set; }
        public string ADMIN_QM_PIN { get; set; }
        public string ADMIN_QM_STD1 { get; set; }
        public string ADMIN_QM_STD2 { get; set; }
        public string ADMIN_QM_PHONE1 { get; set; }
        public string ADMIN_QM_PHONE2 { get; set; }
        public string ADMIN_QM_STD_FAX { get; set; }
        public string ADMIN_QM_FAX { get; set; }
        public string ADMIN_QM_MOBILE1 { get; set; }
        public string ADMIN_QM_MOBILE2 { get; set; }
        public string ADMIN_QM_EMAIL { get; set; }
        public string ADMIN_QM_PAN { get; set; }
        public string ADMIN_QM_PAN_FILE { get; set; }
        public string ADMIN_QM_EMPANELLED { get; set; }
        public Nullable<int> ADMIN_QM_EMPANELLED_YEAR { get; set; }
        public string ADMIN_QM_IMAGE { get; set; }
        public string ADMIN_QM_DOCPATH { get; set; }
        public string ADMIN_QM_AADHAR_NO { get; set; }
        public string ADMIN_QM_REMARKS { get; set; }
        public Nullable<int> ADMIN_USER_ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
        public Nullable<int> OLD_ADMIN_QM_CODE { get; set; }
        public string ADMIN_QM_SERVICE_TYPE { get; set; }
        public Nullable<System.DateTime> ADMIN_QM_BIRTH_DATE { get; set; }
        public Nullable<int> ADMIN_QM_EMPANELLED_MONTH { get; set; }
        public string ADMIN_QM_DEEMPANEL_REMARKS { get; set; }
        public Nullable<int> ADMIN_QM_DEPARTMENT { get; set; }
    
        public virtual MASTER_DISTRICT MASTER_DISTRICT { get; set; }
        public virtual MASTER_STATE MASTER_STATE { get; set; }
        public virtual RCTRC_MASTER_DESIGNATION RCTRC_MASTER_DESIGNATION { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual UM_User_Master UM_User_Master1 { get; set; }
    }
}
