//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCTRC_MASTER_SUGGESTION
    {
        public int RCTRC_SUGG_ID { get; set; }
        public string RCTRC_SUGGESTION { get; set; }
        public string RCTRC_SUGG_ACTIVE { get; set; }
        public System.DateTime RCTRC_SUGG_ACTIVATION_DATE { get; set; }
        public Nullable<System.DateTime> RCTRC_SUGG_DEACTIVATION_DATE { get; set; }
    }
}
