//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REAT_CONTRACTOR_DETAILS
    {
        public int DETAIL_ID { get; set; }
        public Nullable<long> FILE_ID { get; set; }
        public int MAST_CON_ID { get; set; }
        public int MAST_ACCOUNT_ID { get; set; }
        public int MAST_LGD_STATE_CODE { get; set; }
        public Nullable<int> MAST_LGD_DISTRICT_CODE { get; set; }
        public string MAST_CON_COMPANY_NAME { get; set; }
        public string MAST_BANK_NAME { get; set; }
        public string MAST_IFSC_CODE { get; set; }
        public string MAST_ACCOUNT_NUMBER { get; set; }
        public string BATCH_ID { get; set; }
        public string ommas_STATUS { get; set; }
        public string REJECTION_CODE { get; set; }
        public string REAT_CON_ID { get; set; }
        public string ACK_FILE_NAME { get; set; }
        public Nullable<System.DateTime> ACK_RECV_DATE { get; set; }
        public Nullable<int> ADMIN_ND_CODE { get; set; }
        public Nullable<int> MAST_AGENCY_CODE { get; set; }
        public string reat_CON_NAME { get; set; }
        public string reat_IFSC_CODE { get; set; }
        public string reat_STATUS { get; set; }
        public string PURPOSRE { get; set; }
        public string ACCOUNT_ACTION { get; set; }
        public Nullable<int> UPDATED_VENDOR_ID { get; set; }
    
        public virtual ADMIN_DEPARTMENT ADMIN_DEPARTMENT { get; set; }
        public virtual MASTER_AGENCY MASTER_AGENCY { get; set; }
        public virtual REAT_DATA_SEND_DETAILS REAT_DATA_SEND_DETAILS { get; set; }
    }
}
