//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REAT_OB_DETAILS
    {
        public int OB_ID { get; set; }
        public long FILE_ID { get; set; }
        public int ADMIN_ND_CODE { get; set; }
        public string FUND_TYPE { get; set; }
        public string BATCH_ID { get; set; }
        public string BANK_ACC_NO { get; set; }
        public string BANK_NAME { get; set; }
        public string IFSC_CODE { get; set; }
        public decimal OB_AMOUNT { get; set; }
        public System.DateTime OB_DATE { get; set; }
        public string OB_STATUS { get; set; }
        public string TRAN_NO { get; set; }
        public int TRAN_EFFECT { get; set; }
        public string OB_FILE_NAME { get; set; }
        public Nullable<System.DateTime> OB_FILE_DATE { get; set; }
        public string REAT_RESPONSE { get; set; }
        public Nullable<System.DateTime> RESPONSE_RECEIVED_DATE { get; set; }
        public string RECEIVED_RESPONSE { get; set; }
        public string RECEIVED_FILE_NAME { get; set; }
        public int UserId { get; set; }
        public string IPADD { get; set; }
    
        public virtual ADMIN_DEPARTMENT ADMIN_DEPARTMENT { get; set; }
        public virtual REAT_DATA_SEND_DETAILS REAT_DATA_SEND_DETAILS { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
