//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REAT_FUND_RECEIPT_CONFIGURATION
    {
        public int CONFIG_ID { get; set; }
        public int ADMIN_ND_CODE { get; set; }
        public short MONTH { get; set; }
        public short YEAR { get; set; }
        public string FUND_TYPE { get; set; }
    
        public virtual ADMIN_DEPARTMENT ADMIN_DEPARTMENT { get; set; }
    }
}
