//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARGET_HAB_LENGTH
    {
        public int TARGET_ID { get; set; }
        public int MAST_STATE_CODE { get; set; }
        public int TARGET_YEAR { get; set; }
        public decimal LENGTH_TARGET { get; set; }
        public int HABITATION_TARGET { get; set; }
        public decimal EXPENDITURE_TARGET { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_STATE MASTER_STATE { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
