//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEND_CORR_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEND_CORR_MASTER()
        {
            this.TEND_CORR_DETAILS = new HashSet<TEND_CORR_DETAILS>();
        }
    
        public int TEND_CORR_CODE { get; set; }
        public int TEND_NIT_CODE { get; set; }
        public string TEND_CORR_NUMBER { get; set; }
        public Nullable<System.DateTime> TEND_ISSUE_START_DATE { get; set; }
        public Nullable<System.DateTime> TEND_ISSUE_END_DATE { get; set; }
        public Nullable<System.DateTime> TEND_SUBMIT_LAST_DATE { get; set; }
        public Nullable<decimal> TEND_TENDER_AMOUNT { get; set; }
        public string TEND_TENDER_TYPE { get; set; }
        public string TEND_PRE_BID_DETAILS { get; set; }
        public string TEND_INVITING_AUTHORITY { get; set; }
        public string TEND_INVITING_ORG { get; set; }
        public string CONT_REGN_WITH_ORG { get; set; }
        public Nullable<System.DateTime> CONT_REGN_VALIDITY_DATE { get; set; }
        public string TEND_DD_ISSUE_IN_FAVOUR { get; set; }
        public string TEND_DD_PAYABLE_AT { get; set; }
        public Nullable<decimal> TEND_AMOUNT_PER_PACKAGE { get; set; }
        public string TEND_DOC_INSP_OFFICE { get; set; }
        public Nullable<System.DateTime> TEND_INSP_START_DATE { get; set; }
        public Nullable<System.DateTime> TEND_INSP_END_DATE { get; set; }
        public Nullable<System.DateTime> TEND_PUBLICATION_DATE { get; set; }
        public string TEND_ITEM_RATE { get; set; }
        public string TEND_PUBLISH_TENDER { get; set; }
        public Nullable<int> TEND_COLLABORATION { get; set; }
        public string TEND_LOCK_STATUS { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_FUNDING_AGENCY MASTER_FUNDING_AGENCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEND_CORR_DETAILS> TEND_CORR_DETAILS { get; set; }
        public virtual TEND_NIT_MASTER TEND_NIT_MASTER { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
    }
}
