//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEND_AGREEMENT_BG_RENEWAL
    {
        public int TEND_AGREEMENT_CODE { get; set; }
        public int TEND_BG_CODE { get; set; }
        public string TEND_BG_BANK_NAME { get; set; }
        public decimal TEND_BG_AMOUNT { get; set; }
        public System.DateTime TEND_BG_ISSUE_DATE { get; set; }
        public System.DateTime TEND_BG_EXPIRY_DATE { get; set; }
        public string TEND_BG_STATUS { get; set; }
        public Nullable<System.DateTime> TEND_BG_VERIFIED_DATE { get; set; }
        public string TEND_BG_VERIFIED_BY { get; set; }
        public string TEND_BG_FILE_NAME { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual TEND_AGREEMENT_MASTER TEND_AGREEMENT_MASTER { get; set; }
    }
}
