//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UM_MENU_SCHEME_TYPE_COMBINATION
    {
        public int Group_id { get; set; }
        public short Mast_Pmgsy_Scheme { get; set; }
    }
}
