//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UM_Role_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UM_Role_Master()
        {
            this.CONTRACTOR_GRIEVANCE_ROLE_MAPPING = new HashSet<CONTRACTOR_GRIEVANCE_ROLE_MAPPING>();
            this.TECH_AGENCY_SCRUTINY_RESTRICTED = new HashSet<TECH_AGENCY_SCRUTINY_RESTRICTED>();
            this.TKT_TICKET_APPROVAL = new HashSet<TKT_TICKET_APPROVAL>();
            this.TKT_TICKET_DETAIL = new HashSet<TKT_TICKET_DETAIL>();
            this.UM_Role_Action_Mapping = new HashSet<UM_Role_Action_Mapping>();
            this.UM_Role_Level_Mapping = new HashSet<UM_Role_Level_Mapping>();
            this.UM_Role_Menu_Mapping = new HashSet<UM_Role_Menu_Mapping>();
            this.UM_User_Role_Mapping = new HashSet<UM_User_Role_Mapping>();
            this.TKT_ROLE_TYPE_FORWARDING = new HashSet<TKT_ROLE_TYPE_FORWARDING>();
            this.TKT_TG_MODULE_MAPPING = new HashSet<TKT_TG_MODULE_MAPPING>();
        }
    
        public short RoleID { get; set; }
        public string RoleName { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRACTOR_GRIEVANCE_ROLE_MAPPING> CONTRACTOR_GRIEVANCE_ROLE_MAPPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TECH_AGENCY_SCRUTINY_RESTRICTED> TECH_AGENCY_SCRUTINY_RESTRICTED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKT_TICKET_APPROVAL> TKT_TICKET_APPROVAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKT_TICKET_DETAIL> TKT_TICKET_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_Role_Action_Mapping> UM_Role_Action_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_Role_Level_Mapping> UM_Role_Level_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_Role_Menu_Mapping> UM_Role_Menu_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_User_Role_Mapping> UM_User_Role_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKT_ROLE_TYPE_FORWARDING> TKT_ROLE_TYPE_FORWARDING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKT_TG_MODULE_MAPPING> TKT_TG_MODULE_MAPPING { get; set; }
    }
}
