//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTS_UNFREEZE_WORKS
    {
        public int VTS_UID { get; set; }
        public int IMS_PR_ROAD_CODE { get; set; }
        public string IS_UNFREEZED { get; set; }
        public int UNFREEZED_BY { get; set; }
        public System.DateTime UNFREEZED_DATE { get; set; }
        public int USER_ID { get; set; }
        public string IP_ADD { get; set; }
    
        public virtual IMS_SANCTIONED_PROJECTS IMS_SANCTIONED_PROJECTS { get; set; }
    }
}
