//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMGSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTS_ROADWISE_GPS_VEHICLE_COUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VTS_ROADWISE_GPS_VEHICLE_COUNT()
        {
            this.VTS_VEHICLEWISE_GPS_DETAILS = new HashSet<VTS_VEHICLEWISE_GPS_DETAILS>();
        }
    
        public long VEHICLE_ID { get; set; }
        public Nullable<long> VTS_GPS_ID { get; set; }
        public Nullable<int> VEHICLE_TYPE_ID { get; set; }
        public Nullable<int> NO_OF_VEHICLES { get; set; }
        public Nullable<System.DateTime> DATE_OF_INSTALLATION { get; set; }
        public Nullable<System.DateTime> DATE_OF_SUBMISSION { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual UM_User_Master UM_User_Master { get; set; }
        public virtual VTS_VEHICLE_MASTER VTS_VEHICLE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VTS_VEHICLEWISE_GPS_DETAILS> VTS_VEHICLEWISE_GPS_DETAILS { get; set; }
        public virtual VTS_ROADWISE_GPS_AVAILABILITY VTS_ROADWISE_GPS_AVAILABILITY { get; set; }
    }
}
